[package]
name = "leptonic-theme"
version = { workspace = true }
edition = "2024"
rust-version = "1.85.0"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic-theme"
description = """
The optional atom theme (SCSS) of leptonic, the Leptos hooks and atoms library.
"""
categories = ["gui"]
keywords = ["leptos", "components", "component-library", "theming", "css"]

[dependencies]
anyhow = { version = "1.0.104", default-features = false, features = ["std"] }
include_dir = { version = "0.7.4", default-features = false }

[dev-dependencies]
assertr = { version = "0.7.1", default-features = false, features = ["std"] }

[lints]
workspace = true
