[package]
name = "leptonic-theme"
version = { workspace = true }
edition = "2024"
rust-version = "1.85.0"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic-theme"
description = """
Theme builder for the Leptonic component library.
"""
categories = ["gui"]
keywords = ["leptos", "components", "component-library", "theming", "css"]

[dependencies]
anyhow = "1.0.100"
include_dir = "0.7.4"
indoc = "2.0.7"

[lints]
workspace = true
