// The `_phantom: PhantomData<K>` prop on child atoms triggers `used_underscore_binding`
// in code generated by the `#[component]` macro, which we cannot control.
#![allow(clippy::used_underscore_binding)]

use std::{collections::HashSet, marker::PhantomData};

use leptos::{context::Provider, portal::Portal, prelude::*};

use crate::{
    hooks::{
        FocusStrategy, IntoAttrs, Keyed, PlacementX, PlacementY, Selection, SelectionKey,
        SelectionMode, UseFieldDescriptionProps, UseFieldErrorMessageProps,
        UseFormValidationStateReturn, UseHiddenSelectInput, UseHiddenSelectReturn, UseOverlayInput,
        UseOverlayPositionInput, UseOverlayPositionReturn, UseOverlayReturn, UseSelectHiddenProps,
        UseSelectInput, UseSelectLabelProps, UseSelectMenuConfig, UseSelectReturn,
        UseSelectTriggerProps, UseSelectionStateReturn, ValidateFn, ValidationBehavior,
        use_hidden_select, use_overlay, use_overlay_position, use_select,
    },
    utils::{CapturedElement, classes::Classes, locale::WritingDirection, styles::Styles},
};

/// Context shared from [`Select`] to all child select atoms.
#[derive(Clone)]
#[allow(dead_code)]
pub struct SelectCtx<K: SelectionKey> {
    // -- State signals (all Copy) --
    /// Whether the menu is open.
    pub is_open: Signal<bool>,
    /// The currently selected keys.
    pub selected_keys: Signal<Selection<K>>,
    /// The display value for the selected item(s).
    pub display_value: Signal<Option<String>>,
    /// Whether the trigger is focused.
    pub is_focused: Signal<bool>,
    /// Whether the select is invalid.
    pub is_invalid: Signal<bool>,
    /// Validation error messages.
    pub validation_errors: Signal<Vec<String>>,
    /// The current focus strategy for the listbox.
    pub focus_strategy: Signal<Option<FocusStrategy>>,
    /// The currently focused key in the listbox.
    pub focused_key: Signal<Option<K>>,

    // -- Callbacks (all Copy) --
    /// Open the menu.
    pub open: Callback<()>,
    /// Close the menu.
    pub close: Callback<()>,
    /// Toggle the menu.
    pub toggle: Callback<()>,
    /// Set the selected keys programmatically.
    pub set_selected_keys: Callback<Selection<K>>,
    /// Get the stable DOM element ID for a listbox option.
    pub get_option_id: Callback<K, String>,

    // -- For child atom composition --
    /// The selection state for wiring `use_option`.
    pub selection_state: UseSelectionStateReturn<K>,
    /// Full validation state.
    pub validation: UseFormValidationStateReturn,

    // -- Pre-stored hook outputs (StoredValue is Copy) --
    trigger_props: StoredValue<UseSelectTriggerProps>,
    label_props: StoredValue<UseSelectLabelProps>,
    description_props: StoredValue<UseFieldDescriptionProps>,
    error_message_props: StoredValue<UseFieldErrorMessageProps>,
    hidden_select_props: StoredValue<UseSelectHiddenProps>,
    value_id: StoredValue<String>,
    menu_config: StoredValue<UseSelectMenuConfig<K>>,
    trigger_element: CapturedElement,
    trigger_id: StoredValue<String>,
    listbox_id: StoredValue<String>,
    label_id: StoredValue<String>,
}

impl<K: SelectionKey> SelectCtx<K> {
    /// Returns the menu configuration for wiring to a [`ListBox`](super::listbox::ListBox).
    pub fn menu_config(&self) -> UseSelectMenuConfig<K> {
        self.menu_config.get_value()
    }
}

// Manual Copy impl: derive(Copy) would add `K: Copy` which is too restrictive.
// All fields are Copy (Signal, Callback, StoredValue, CapturedElement,
// UseSelectionStateReturn, UseFormValidationStateReturn).
impl<K: SelectionKey> Copy for SelectCtx<K> {}

/// A headless select root atom.
///
/// Calls `use_select` and provides [`SelectCtx`] to all children via context.
/// Compose with [`SelectTrigger`], [`SelectValue`], [`SelectLabel`],
/// [`SelectPopover`], [`HiddenSelect`], and [`ListBox`](super::listbox::ListBox).
#[component]
#[allow(
    clippy::too_many_lines,
    clippy::implicit_hasher,
    clippy::fn_params_excessive_bools
)]
pub fn Select<V: Keyed + Clone + Send + Sync + 'static>(
    /// All available items.
    #[prop(into)]
    items: Signal<Vec<V>>,
    /// The selection mode (single or multiple).
    #[prop(into, optional)]
    selection_mode: SelectionMode,
    /// Whether the select is disabled.
    #[prop(into, optional)]
    disabled: Signal<bool>,
    /// Whether the select is required.
    #[prop(into, optional)]
    is_required: bool,
    /// Controlled selected keys.
    #[prop(into, optional)]
    selected_keys: Option<Signal<Selection<V::Key>>>,
    /// Default selected keys (uncontrolled).
    #[prop(into, optional)]
    default_selected_keys: Option<Selection<V::Key>>,
    /// Callback when selection changes.
    #[prop(into, optional)]
    on_selection_change: Option<Callback<Selection<V::Key>>>,
    /// Keys that cannot be selected.
    #[prop(into, optional)]
    disabled_keys: Option<Signal<HashSet<V::Key>>>,
    /// A function to get the text value for a key.
    #[prop(into, optional)]
    get_text_value: Option<Callback<V::Key, String>>,
    /// Whether the menu is open (controlled).
    #[prop(into, optional)]
    is_open: Option<Signal<bool>>,
    /// The default open state (uncontrolled).
    #[prop(into, optional)]
    default_open: bool,
    /// Callback when open state changes.
    #[prop(into, optional)]
    on_open_change: Option<Callback<bool>>,
    /// Whether to allow opening the menu when the collection is empty.
    #[prop(into, optional)]
    allows_empty_collection: bool,
    /// Visible label text.
    #[prop(into, optional)]
    label: Option<&'static str>,
    /// Accessibility label (when no visible label is present).
    #[prop(into, optional)]
    aria_label: Option<&'static str>,
    /// The ID of an element that labels the select.
    #[prop(into, optional)]
    aria_labelledby: Option<String>,
    /// Whether a description element is rendered.
    #[prop(into, optional)]
    has_description: bool,
    /// Controlled invalid state.
    #[prop(into, optional)]
    is_invalid: Option<Signal<bool>>,
    /// Custom validation function.
    #[prop(into, optional)]
    validate: Option<ValidateFn<Selection<V::Key>>>,
    /// Validation behavior mode.
    #[prop(into, optional)]
    validation_behavior: ValidationBehavior,
    /// The name attribute for form submission.
    #[prop(into, optional)]
    name: Option<&'static str>,
    /// Callback when the trigger receives focus.
    #[prop(into, optional)]
    on_focus: Option<Callback<()>>,
    /// Callback when the trigger loses focus.
    #[prop(into, optional)]
    on_blur: Option<Callback<()>>,
    /// Callback when focus state changes.
    #[prop(into, optional)]
    on_focus_change: Option<Callback<bool>>,
    /// User keydown handler.
    #[prop(into, optional)]
    on_key_down: Option<Callback<web_sys::KeyboardEvent>>,
    /// User keyup handler.
    #[prop(into, optional)]
    on_key_up: Option<Callback<web_sys::KeyboardEvent>>,
    /// Placeholder text when nothing is selected.
    #[prop(into, optional)]
    placeholder: Option<&'static str>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: Children,
) -> impl IntoView {
    // Convert items to keys via the Keyed trait.
    // For self-keyed types (e.g., String), this is zero-cost.
    let keys = V::items_to_keys(items);

    let UseSelectReturn {
        trigger_props,
        value_props: _,
        label_props,
        description_props,
        error_message_props,
        hidden_select_props,
        trigger_id,
        listbox_id,
        label_id,
        value_id,
        is_open: open_signal,
        selected_keys: selected_keys_signal,
        display_value,
        is_focused: focused_signal,
        focus_strategy,
        focused_key,
        is_invalid: invalid_signal,
        validation_errors,
        validation,
        selection_state,
        open,
        close,
        toggle,
        set_selected_keys,
        get_option_id,
        trigger_element,
        menu_config,
    } = use_select(UseSelectInput {
        selection_mode,
        is_disabled: disabled,
        is_required,
        selected_keys,
        default_selected_keys,
        on_selection_change,
        disabled_keys: disabled_keys.unwrap_or_else(|| Signal::derive(HashSet::new)),
        items: keys,
        get_text_value,
        is_open,
        default_open,
        on_open_change,
        allows_empty_collection,
        label,
        aria_label,
        aria_labelledby,
        has_description,
        is_invalid,
        validate,
        validation_behavior,
        name,
        on_focus,
        on_blur,
        on_focus_change,
        on_key_down,
        on_key_up,
        placeholder,
    });

    let ctx = SelectCtx {
        is_open: open_signal,
        selected_keys: selected_keys_signal,
        display_value,
        is_focused: focused_signal,
        is_invalid: invalid_signal,
        validation_errors,
        focus_strategy,
        focused_key,
        open,
        close,
        toggle,
        set_selected_keys,
        get_option_id,
        selection_state,
        validation,
        trigger_props: StoredValue::new(trigger_props),
        label_props: StoredValue::new(label_props),
        description_props: StoredValue::new(description_props),
        error_message_props: StoredValue::new(error_message_props),
        hidden_select_props: StoredValue::new(hidden_select_props),
        value_id: StoredValue::new(value_id),
        menu_config: StoredValue::new(menu_config),
        trigger_element,
        trigger_id: StoredValue::new(trigger_id),
        listbox_id: StoredValue::new(listbox_id),
        label_id: StoredValue::new(label_id),
    };

    view! {
        <Provider value=ctx>
            <div class=classes style=styles>
                {children()}
            </div>
        </Provider>
    }
}

/// The trigger button for a select. Spreads ARIA attributes from `use_select`.
///
/// Exposes `data-open` and `data-invalid` for CSS styling.
#[component]
pub fn SelectTrigger<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: Children,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let trigger_attrs = ctx.trigger_props.get_value().into_attrs();

    let data_open = Signal::derive(move || ctx.is_open.get().then_some("true"));
    let data_invalid = Signal::derive(move || ctx.is_invalid.get().then_some("true"));

    view! {
        <div
            {..trigger_attrs}
            class=classes
            style=styles
            attr:data-open=data_open
            attr:data-invalid=data_invalid
        >
            {children()}
        </div>
    }
}

/// Displays the selected value text. Renders a `<span>` with the value ID for
/// ARIA association.
#[component]
#[allow(clippy::needless_pass_by_value)]
pub fn SelectValue<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// Placeholder text when nothing is selected.
    #[prop(into, optional)]
    placeholder: Option<String>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let value_id = ctx.value_id.get_value();
    let display_value = ctx.display_value;

    view! {
        <span id=value_id class=classes style=styles>
            {move || {
                display_value
                    .get()
                    .unwrap_or_else(|| placeholder.clone().unwrap_or_default())
            }}
        </span>
    }
}

/// A label for the select. Renders a `<label>` with proper ARIA associations
/// and a click handler that focuses the trigger.
#[component]
pub fn SelectLabel<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: Children,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let label_attrs = ctx.label_props.get_value().into_attrs();

    view! {
        <label {..label_attrs} class=classes style=styles>
            {children()}
        </label>
    }
}

/// A description element wired to the select's `aria-describedby`.
#[component]
pub fn SelectDescription<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: Children,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let desc_attrs = ctx.description_props.get_value().into_attrs();

    view! {
        <div {..desc_attrs} class=classes style=styles>
            {children()}
        </div>
    }
}

/// An error message element that only renders when the select is invalid.
#[component]
pub fn SelectErrorMessage<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: ChildrenFn,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let error_attrs = ctx.error_message_props.get_value().into_attrs();
    let is_invalid = ctx.is_invalid;

    let children = StoredValue::new(children);

    view! {
        <Show when=move || is_invalid.get()>
            <div {..error_attrs.clone()} class=classes.clone() style=styles.clone()>
                {(children.get_value())()}
            </div>
        </Show>
    }
}

/// The dropdown overlay for a select. Uses `use_overlay` and `use_overlay_position`
/// for dismiss behavior and positioning relative to the trigger.
///
/// Renders via `<Portal>` and only mounts children when the select is open.
#[component]
pub fn SelectPopover<K: SelectionKey>(
    #[prop(optional)] _phantom: PhantomData<K>,
    /// Horizontal placement relative to the trigger.
    #[prop(into)]
    placement_x: Signal<PlacementX>,
    /// Vertical placement relative to the trigger.
    #[prop(into)]
    placement_y: Signal<PlacementY>,
    /// Writing direction for RTL support.
    #[prop(into)]
    writing_direction: Signal<WritingDirection>,
    /// CSS classes.
    #[prop(into, optional)]
    classes: Classes,
    /// CSS styles.
    #[prop(into, optional)]
    styles: Styles,
    children: ChildrenFn,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();

    let UseOverlayReturn {
        props: overlay_props,
        underlay_props: _,
        id: _,
        overlay_element: _,
    } = use_overlay(UseOverlayInput {
        is_open: ctx.is_open,
        on_close: Callback::new(move |()| ctx.close.run(())),
        is_dismissable: true,
        should_close_on_blur: false,
        is_keyboard_dismiss_disabled: false,
        should_close_on_interact_outside: None,
    });

    let UseOverlayPositionReturn {
        props: overlay_pos_props,
        resolved_placement_x: _,
        resolved_placement_y: _,
    } = use_overlay_position(UseOverlayPositionInput {
        target: ctx.trigger_element,
        placement_x,
        placement_y,
        writing_direction,
        offset: 0.0.into(),
        cross_offset: 0.0.into(),
        container_padding: 12.0.into(),
        should_flip: true.into(),
        max_height: None,
        is_open: ctx.is_open,
    });

    let overlay_attrs = overlay_props.into_attrs();
    let (overlay_pos_attrs, overlay_pos_styles) = overlay_pos_props.into_parts();
    let styles = overlay_pos_styles.merge(styles);

    view! {
        <Portal>
            {
                let overlay_attrs = overlay_attrs.clone();
                let overlay_pos_attrs = overlay_pos_attrs.clone();
                let children = children.clone();
                let classes = classes.clone();
                let styles = styles.clone();
                view! {
                    <Show when=move || ctx.is_open.get()>
                        <div
                            {..overlay_attrs.clone()}
                            {..overlay_pos_attrs.clone()}
                            class=classes.clone()
                            style=styles.clone()
                        >
                            {children()}
                        </div>
                    </Show>
                }
            }
        </Portal>
    }
}

/// A visually-hidden form element for browser form submission and autofill.
///
/// Renders a native `<select>` (when items <= 300) or `<input type="hidden">`
/// (when items > 300) inside a visually-hidden container.
#[component]
pub fn HiddenSelect<K: SelectionKey>(
    /// Override key-to-value serialization for form submission.
    #[prop(into, optional)]
    key_to_value: Option<Callback<K, String>>,
    /// Override text display for native `<option>` elements.
    #[prop(into, optional)]
    get_text_value: Option<Callback<K, String>>,
    /// The `form` attribute to associate with a specific form.
    #[prop(into, optional)]
    form: Option<&'static str>,
    /// The `autocomplete` attribute.
    #[prop(into, optional)]
    auto_complete: Option<&'static str>,
) -> impl IntoView {
    let ctx = expect_context::<SelectCtx<K>>();
    let hidden_props = ctx.hidden_select_props.get_value();
    let mc = ctx.menu_config();

    let UseHiddenSelectReturn {
        container_props,
        input_props,
        select_props,
        value: _,
        use_native_select,
        options,
    } = use_hidden_select(UseHiddenSelectInput {
        name: hidden_props.name,
        is_disabled: hidden_props.disabled,
        is_required: hidden_props.required,
        selected_keys: ctx.selected_keys,
        selection_mode: hidden_props.selection_mode,
        key_to_value,
        trigger_id: ctx.trigger_id.get_value(),
        label: None,
        validation_behavior: hidden_props.validation_behavior,
        form,
        auto_complete,
        items: mc.items,
        get_text_value,
        on_change: None,
        default_selected_keys: None,
        on_reset: None,
        validation_state: Some(ctx.validation),
    });

    let container_attrs = container_props.into_attrs();
    let select_attrs = StoredValue::new(select_props.into_attrs());
    let input_attrs = StoredValue::new(input_props.into_attrs());

    view! {
        <div style="position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0;" {..container_attrs}>
            <Show when=move || use_native_select.get()>
                <select {..select_attrs.get_value()}>
                    <For
                        each=move || options.get()
                        key=|opt| opt.key_value.clone()
                        children=move |opt| {
                            view! {
                                <option value=opt.key_value.clone() selected=opt.is_selected>
                                    {opt.text.clone()}
                                </option>
                            }
                        }
                    />
                </select>
            </Show>
            <Show when=move || !use_native_select.get()>
                <input {..input_attrs.get_value()} />
            </Show>
        </div>
    }
}
