// Upstream: react-aria-components/src/Slider.tsx @ 99e6102368
use std::sync::Arc;

use leptos::{context::Provider, ev, prelude::*};
use leptos_classes::Classes;

use super::{
    field::{FieldContext, LabelContext},
    visually_hidden::VisuallyHidden,
};
use crate::{
    IntoAttrs, Orientation, Out, ValueBinding,
    atoms::field::LabelPresence,
    hooks::{
        focus::{UseFocusRingInput, use_focus_ring},
        form::{UseLabelProps, ValidityStateSnapshot},
        interactions::{UseHoverInput, use_hover},
        slider::{
            ComputedSliderMark, SliderMarkPlacement, UseSliderInput, UseSliderMarksInput,
            UseSliderOutputAttrs, UseSliderReturn, UseSliderStateInput, UseSliderThumbInput,
            UseSliderThumbReturn, UseSliderTrackAttrs, use_slider, use_slider_marks,
            use_slider_state, use_slider_thumb,
        },
    },
    utils::{
        data_attributes::flag, default_class::with_default_class, fraction::Fraction,
        number_formatter::NumberFormatOptions, number_value::NumberValue, styles::Styles,
    },
};

// =============================================================================
// REACT-ARIA DEVIATIONS
// =============================================================================
//
// ## API DIFFERENCES
// - `Slider` is generic over its value type (as `use_slider_state`); its children reach it through
//   a context of plain `f64` positions and formatted labels, so they need no type parameter.
// - Values are a `Vec` (`default_values`, or `values` + `set_values`).
// - Render props become `data-*` attributes plus plain children; `SliderOutput` shows the
//   formatted values without children.
// - Label, description and error message are the field parts (C14): `Label`, `Description`,
//   `FieldError` inside the slider. A `Label` inside a `SliderThumb` names that thumb (as
//   upstream's thumb `LabelContext`).
// - `is_required` also on the `Slider` (every thumb; react-aria-components: per thumb only).
//
// ## DIFFERENT BEHAVIOR
// - `SliderFill` sets its position and its size along the track, not its size across it
//   (react-aria-components: 100%, as a default style that a `style` prop replaces): CSS sizes it.
//
// ## ADDITIONS
// - `SliderThumbTooltip` (a thumb's value, shown as `SliderPopover` says), `SliderMarks`/`SliderMark`
//   (marks along the track, `use_slider_marks`).
//
// =============================================================================

/// What the slider's parts need, without its value type.
#[derive(Clone)]
struct SliderContext {
    orientation: Signal<Orientation>,
    is_disabled: Signal<bool>,
    /// The thumbs' positions on the track.
    percents: Signal<Vec<Fraction>>,
    /// The first thumb's bounds, as `f64`.
    first_thumb_bounds: Signal<(f64, f64)>,
    /// Where a value (as `f64`) is on the track.
    value_percent: Callback<f64, Fraction>,
    /// The values, formatted for an output.
    formatted: Signal<String>,
    track: StoredValue<(UseSliderTrackAttrs, Styles)>,
    output: StoredValue<UseSliderOutputAttrs>,
    /// Creates thumb `index` (in the thumb's reactive owner).
    thumb: Arc<dyn Fn(ThumbOptions) -> (UseSliderThumbReturn, Signal<String>) + Send + Sync>,
    /// The range, step and values as `f64`, and a formatter, for marks.
    marks: Arc<dyn Fn(SliderMarkPlacement) -> Signal<Vec<ComputedSliderMark>> + Send + Sync>,
}

/// A thumb's settings, without the slider's value type.
struct ThumbOptions {
    index: usize,
    is_disabled: Signal<bool>,
    is_required: Signal<bool>,
    is_invalid: Signal<bool>,
    name: Option<String>,
    form: Option<String>,
    has_label: Signal<bool>,
    aria_label: MaybeProp<String>,
    aria_labelledby: Option<String>,
    aria_describedby: Option<String>,
    aria_errormessage: Option<String>,
    aria_details: Option<String>,
}

fn expect_slider() -> Option<SliderContext> {
    let context = use_context::<SliderContext>();
    if context.is_none() {
        crate::utils::dev_warn!("Slider parts must be inside a <Slider>.");
    }
    context
}

/// A slider: thumbs on a track picking values from a range. Put a `SliderTrack` with
/// `SliderThumb`s (one per value, each with its `index`) and optionally a `Label` and a
/// `SliderOutput` inside it.
///
/// The value type comes from `values` or `default_values` (with typed literals: `vec![30_u8]`);
/// the bounds' conversions (`into`) can't tell it.
///
/// ```ignore
/// <Slider min_value=0 max_value=100 default_values=vec![30_u8]>
///     <Label>"Volume"</Label>
///     <SliderOutput/>
///     <SliderTrack><SliderThumb/></SliderTrack>
/// </Slider>
/// ```
///
/// Data attributes: `data-orientation`, `data-disabled`.
///
/// Default class: `leptonic-Slider`.
#[component]
#[allow(clippy::too_many_lines)]
pub fn Slider<T: NumberValue>(
    /// The group's id (thumb ids derive from it). Generated by default.
    #[prop(into, optional)]
    id: Option<String>,
    #[prop(into)] min_value: Signal<T>,
    #[prop(into)] max_value: Signal<T>,
    /// The step between values. Default: 1.
    #[prop(into, default = Signal::stored(T::ONE))]
    step: Signal<T>,
    /// The initial values, one per thumb. Default: one thumb at `min_value`.
    #[prop(optional)]
    default_values: Option<Vec<T>>,
    /// The values, replacing `default_values` (controlled; any signal or value).
    #[prop(into, optional)]
    values: Option<Signal<Vec<T>>>,
    /// Receives the new values (an `RwSignal`, `WriteSignal`, closure, `Callback`, ...).
    #[prop(into, optional)]
    set_values: Option<Out<Vec<T>>>,
    #[prop(into, default = Signal::stored(Orientation::Horizontal))] orientation: Signal<
        Orientation,
    >,
    #[prop(into, optional)] is_disabled: Signal<bool>,
    /// Whether a value is required (`aria-required` on every thumb).
    #[prop(into, optional)]
    is_required: Signal<bool>,
    /// Whether the value is invalid (shows a `FieldError`).
    #[prop(into, optional)]
    is_invalid: Signal<bool>,
    /// How values are formatted for assistive technology and the output.
    #[prop(into, optional)]
    format_options: Signal<NumberFormatOptions>,
    /// Names the slider when it has no `Label`.
    #[prop(into, optional)]
    aria_label: MaybeProp<String>,
    #[prop(into, optional)] aria_labelledby: Option<String>,
    /// Further elements describing every thumb (next to a `Description`).
    #[prop(into, optional)]
    aria_describedby: Option<String>,
    /// Elements with details about every thumb.
    #[prop(into, optional)]
    aria_details: Option<String>,
    /// Called with the values whenever they change, also while dragging.
    #[prop(into, optional)]
    on_change: Option<Callback<Vec<T>>>,
    /// Called with the values when the user stops dragging.
    #[prop(into, optional)]
    on_change_end: Option<Callback<Vec<T>>>,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
    children: Children,
) -> impl IntoView {
    let classes = with_default_class("leptonic-Slider", classes);
    let label_presence = LabelPresence::new(aria_label, aria_labelledby.as_ref());
    let has_label = label_presence.has_label;
    let (value, on_change) = ValueBinding::from_state_props(values, set_values, on_change);
    let state = use_slider_state(UseSliderStateInput {
        default_values,
        value,
        min_value,
        max_value,
        step,
        is_disabled,
        orientation,
        format_options,
        value_label: None,
        page_size: None,
        on_change,
        on_change_end,
    });
    let slider = use_slider(UseSliderInput {
        state,
        id,
        has_label,
        aria_label,
        aria_labelledby,
        aria_describedby,
        aria_details,
    });
    let UseSliderReturn {
        label_props,
        description_props,
        error_message_props,
        group_props,
        track_props,
        output_props,
        data,
        track_element,
    } = slider;

    let label = LabelContext::span(UseLabelProps {
        id: label_props.id,
        html_for: None,
    })
    .with_on_click(label_props.on_click)
    .with_presence(label_presence);
    let field = FieldContext {
        description: description_props,
        error_message: error_message_props,
        is_invalid,
        validation_errors: Signal::default(),
        validation_details: Signal::stored(ValidityStateSnapshot::default()),
    };

    let thumb_data = StoredValue::new(data);
    let context = SliderContext {
        orientation,
        is_disabled,
        percents: Signal::derive(move || {
            (0..state.thumb_count())
                .map(|index| state.thumb_percent(index))
                .collect()
        }),
        first_thumb_bounds: Signal::derive(move || {
            (
                state.thumb_min_value(0).to_f64(),
                state.thumb_max_value(0).to_f64(),
            )
        }),
        value_percent: Callback::new(move |value: f64| {
            let (min, max) = (min_value.get().to_f64(), max_value.get().to_f64());
            if max == min {
                Fraction::ZERO
            } else {
                Fraction::new((value - min) / (max - min))
            }
        }),
        formatted: Signal::derive(move || state.formatted_values()),
        track: StoredValue::new(track_props.into_parts()),
        output: StoredValue::new(output_props.into_attrs()),
        thumb: Arc::new(move |options: ThumbOptions| {
            let ThumbOptions {
                index,
                is_disabled,
                is_required: thumb_required,
                is_invalid: thumb_invalid,
                name,
                form,
                has_label,
                aria_label,
                aria_labelledby,
                aria_describedby,
                aria_errormessage,
                aria_details,
            } = options;
            let thumb = use_slider_thumb(UseSliderThumbInput {
                state,
                slider: thumb_data.get_value(),
                track: track_element,
                index,
                is_disabled,
                name,
                form,
                has_label,
                aria_label,
                aria_labelledby,
                aria_describedby,
                aria_errormessage,
                aria_details,
                is_required: Signal::derive(move || is_required.get() || thumb_required.get()),
                is_invalid: Signal::derive(move || is_invalid.get() || thumb_invalid.get()),
            });
            (
                thumb,
                Signal::derive(move || state.thumb_value_label(index)),
            )
        }),
        marks: Arc::new(move |marks| {
            use_slider_marks(UseSliderMarksInput {
                min_value: Signal::derive(move || min_value.get().to_f64()),
                max_value: Signal::derive(move || max_value.get().to_f64()),
                step: Signal::derive(move || step.get().to_f64()),
                values: Signal::derive(move || {
                    state
                        .values
                        .with(|v| v.iter().map(|v| v.to_f64()).collect())
                }),
                marks,
                format: Callback::new(move |value: f64| {
                    T::from_f64(value)
                        .map_or_else(|| value.to_string(), |value| state.format_value(value))
                }),
            })
        }),
    };

    view! {
        <Provider value=context>
            <Provider value=label><Provider value=field>
                <div
                    {..group_props.into_attrs()}
                    class=classes
                    style=styles
                    data-orientation=move || orientation.get().as_str()
                    data-disabled=flag(is_disabled)
                >
                    {children()}
                </div>
            </Provider></Provider>
        </Provider>
    }
}

/// The track of the [`Slider`] around it: pressing it moves the closest thumb there.
///
/// Data attributes: `data-hovered`, `data-orientation`, `data-disabled`.
///
/// Default class: `leptonic-SliderTrack`.
#[component]
pub fn SliderTrack(
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
    children: Children,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderTrack", classes);
    let Some(slider) = expect_slider() else {
        return children().into_any();
    };
    // Hovered also while disabled (react-aria-components).
    let hover = use_hover(UseHoverInput::default());
    let (attrs, track_styles) = slider.track.get_value();
    let orientation = slider.orientation;
    view! {
        <div
            {..attrs}
            {..hover.props.into_attrs()}
            class=classes
            style=track_styles.merge(styles)
            data-hovered=flag(hover.is_hovered)
            data-orientation=move || orientation.get().as_str()
            data-disabled=flag(slider.is_disabled)
        >
            {children()}
        </div>
    }
    .into_any()
}

/// The filled part of the track: from `offset` (default: the start) to the thumb, or between the
/// first and the last thumb. Put it in the `SliderTrack` and size it across the track with CSS
/// (e.g. `height: 100%`).
///
/// Data attributes: `data-hovered`, `data-orientation`, `data-disabled`.
///
/// Default class: `leptonic-SliderFill`.
#[component]
pub fn SliderFill(
    /// Where the fill of a one-thumb slider starts, as a value of the range (e.g. 0 in a range
    /// from -10 to 10). Default: the start.
    #[prop(into, optional)]
    offset: MaybeProp<f64>,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderFill", classes);
    let Some(slider) = expect_slider() else {
        return ().into_any();
    };
    let SliderContext {
        orientation,
        is_disabled,
        percents,
        first_thumb_bounds,
        value_percent,
        ..
    } = slider;
    // Hovered also while disabled (react-aria-components).
    let hover = use_hover(UseHoverInput::default());
    // In percent: (start, size).
    let span = Signal::derive(move || {
        let (min, max) = first_thumb_bounds.get();
        let offset = offset
            .get()
            .map_or(min, |offset| offset.clamp(min.min(max), max.max(min)));
        percents.with(|percents| {
            let start = if percents.len() > 1 {
                percents[0]
            } else {
                value_percent.run(offset)
            }
            .as_percent();
            let end = percents
                .last()
                .copied()
                .unwrap_or(Fraction::ZERO)
                .as_percent();
            (start.min(end), (start.max(end) - start.min(end)).max(0.0))
        })
    });
    let vertical = move || orientation.get() == Orientation::Vertical;
    let percent = |value: f64| format!("{value}%");
    let styles = Styles::new()
        .add_unchecked("position", "absolute")
        .add_optional_unchecked("inset-inline-start", move || {
            (!vertical()).then(|| percent(span.get().0))
        })
        .add_optional_unchecked("width", move || {
            (!vertical()).then(|| percent(span.get().1))
        })
        .add_optional_unchecked("bottom", move || vertical().then(|| percent(span.get().0)))
        .add_optional_unchecked("height", move || vertical().then(|| percent(span.get().1)))
        .merge(styles);
    view! {
        <div
            {..hover.props.into_attrs()}
            class=classes
            style=styles
            data-hovered=flag(hover.is_hovered)
            data-orientation=move || orientation.get().as_str()
            data-disabled=flag(is_disabled)
        />
    }
    .into_any()
}

/// What a thumb's tooltip needs.
#[derive(Debug, Clone, Copy)]
struct SliderThumbContext {
    is_hovered: Signal<bool>,
    is_dragging: Signal<bool>,
    /// The formatted value.
    label: Signal<String>,
}

/// A thumb of the [`Slider`] around it, inside its `SliderTrack`: dragged with a pointer, moved
/// with the keyboard through its visually hidden `<input type="range">`. A `Label` inside it
/// names this thumb (next to the slider's label).
///
/// Data attributes: `data-dragging`, `data-hovered`, `data-focused`, `data-focus-visible`,
/// `data-disabled`.
///
/// Default class: `leptonic-SliderThumb`.
#[component]
pub fn SliderThumb(
    /// The thumb's value in the slider's values.
    #[prop(optional)]
    index: usize,
    /// Disables this thumb only.
    #[prop(into, optional)]
    is_disabled: Signal<bool>,
    /// Whether this thumb's value is required (next to the slider's `is_required`).
    #[prop(into, optional)]
    is_required: Signal<bool>,
    /// Whether this thumb's value is invalid (next to the slider's `is_invalid`).
    #[prop(into, optional)]
    is_invalid: Signal<bool>,
    /// The input's name, for forms.
    #[prop(into, optional)]
    name: Option<String>,
    #[prop(into, optional)] form: Option<String>,
    /// Names this thumb next to the slider's label (e.g. "Minimum").
    #[prop(into, optional)]
    aria_label: MaybeProp<String>,
    #[prop(into, optional)] aria_labelledby: Option<String>,
    /// Further elements describing this thumb (next to the slider's description).
    #[prop(into, optional)]
    aria_describedby: Option<String>,
    /// The element with this thumb's error message.
    #[prop(into, optional)]
    aria_errormessage: Option<String>,
    /// Further elements with details about this thumb.
    #[prop(into, optional)]
    aria_details: Option<String>,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
    #[prop(optional)] children: Option<Children>,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderThumb", classes);
    let Some(slider) = expect_slider() else {
        return ().into_any();
    };
    // A `Label` inside the thumb names it (react-aria-components' `LabelContext` of the thumb).
    let label_presence = LabelPresence::new(aria_label, aria_labelledby.as_ref());
    // Hovered unless this thumb is disabled (react-aria-components' `useHover(props)`: the
    // slider's `is_disabled` doesn't count).
    let hover = use_hover(UseHoverInput {
        is_disabled,
        ..UseHoverInput::default()
    });
    let (thumb, label) = (slider.thumb)(ThumbOptions {
        index,
        is_disabled,
        is_required,
        is_invalid,
        name,
        form,
        has_label: label_presence.has_label,
        aria_label,
        aria_labelledby,
        aria_describedby,
        aria_errormessage,
        aria_details,
    });
    let UseSliderThumbReturn {
        thumb_props,
        input_props,
        label_props,
        is_dragging,
        is_disabled,
        is_focused,
    } = thumb;
    let thumb_label = LabelContext::label(label_props).with_presence(label_presence);
    let focus_ring = use_focus_ring(UseFocusRingInput::default());
    let is_focus_visible = focus_ring.is_focus_visible;
    let input_focus = (
        focus_ring.props.on_focus.into_on(ev::focus),
        focus_ring.props.on_blur.into_on(ev::blur),
    );
    let (thumb_attrs, thumb_styles) = thumb_props.into_parts();
    let thumb_context = SliderThumbContext {
        is_hovered: hover.is_hovered,
        is_dragging,
        label,
    };

    view! {
        <div
            {..thumb_attrs}
            {..hover.props.into_attrs()}
            class=classes
            style=thumb_styles.merge(styles)
            data-dragging=flag(is_dragging)
            data-hovered=flag(hover.is_hovered)
            data-focused=flag(is_focused)
            data-focus-visible=flag(is_focus_visible)
            data-disabled=flag(is_disabled)
        >
            <VisuallyHidden>
                <input {..input_props.into_attrs()} {..input_focus} />
            </VisuallyHidden>
            <Provider value=thumb_context>
                <Provider value=thumb_label>{children.map(|children| children())}</Provider>
            </Provider>
        </div>
    }
    .into_any()
}

/// When a [`SliderThumbTooltip`] shows.
#[derive(Default, Debug, Clone, Copy, PartialEq, Eq)]
pub enum SliderPopover {
    #[default]
    Never,
    /// While the pointer is over the thumb.
    OnHover,
    /// While the thumb is dragged.
    OnDrag,
    /// While the pointer is over the thumb or it is dragged.
    OnHoverOrDrag,
    Always,
}

/// A tooltip with the value of the `SliderThumb` around it. Shown as `popover` says: style it
/// hidden without `data-visible`.
///
/// Default class: `leptonic-SliderThumbTooltip`.
#[component]
pub fn SliderThumbTooltip(
    #[prop(optional)] popover: SliderPopover,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderThumbTooltip", classes);
    let Some(thumb) = use_context::<SliderThumbContext>() else {
        crate::utils::dev_warn!("A <SliderThumbTooltip> must be inside a <SliderThumb>.");
        return ().into_any();
    };
    let visible = Signal::derive(move || match popover {
        SliderPopover::Never => false,
        SliderPopover::OnHover => thumb.is_hovered.get(),
        SliderPopover::OnDrag => thumb.is_dragging.get(),
        SliderPopover::OnHoverOrDrag => thumb.is_hovered.get() || thumb.is_dragging.get(),
        SliderPopover::Always => true,
    });
    // The input announces the value: the tooltip only shows it.
    view! {
        <div class=classes style=styles data-visible=flag(visible) aria-hidden="true">
            {thumb.label}
        </div>
    }
    .into_any()
}

/// An `<output>` with the formatted values of the [`Slider`] around it ("10", "10 – 20").
///
/// Data attributes: `data-orientation`, `data-disabled`.
///
/// Default class: `leptonic-SliderOutput`.
#[component]
pub fn SliderOutput(
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderOutput", classes);
    let Some(slider) = expect_slider() else {
        return ().into_any();
    };
    let orientation = slider.orientation;
    view! {
        <output
            {..slider.output.get_value()}
            class=classes
            style=styles
            data-orientation=move || orientation.get().as_str()
            data-disabled=flag(slider.is_disabled)
        >
            {slider.formatted}
        </output>
    }
    .into_any()
}

/// The marks of the [`Slider`] around it; render each with a [`SliderMark`].
///
/// Default class: `leptonic-SliderMarks`.
#[component]
pub fn SliderMarks<C, V>(
    #[prop(into)] marks: SliderMarkPlacement,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
    children: C,
) -> impl IntoView
where
    C: Fn(Signal<Vec<ComputedSliderMark>>) -> V,
    V: IntoView + 'static,
{
    let classes = with_default_class("leptonic-SliderMarks", classes);
    let Some(slider) = expect_slider() else {
        return ().into_any();
    };
    let computed = (slider.marks)(marks);
    view! { <div class=classes style=styles aria-hidden="true">{children(computed)}</div> }
        .into_any()
}

/// A mark placed along the track, as the fill: `inset-inline-start` in percent when horizontal
/// (mirrored right to left), `bottom` when vertical.
///
/// Data attributes: `data-in-range` while selected, `data-orientation`.
///
/// Default class: `leptonic-SliderMark`.
#[component]
pub fn SliderMark(
    mark: ComputedSliderMark,
    #[prop(into, optional)] classes: Classes,
    #[prop(into, optional)] styles: Styles,
    children: Children,
) -> impl IntoView {
    let classes = with_default_class("leptonic-SliderMark", classes);
    let Some(SliderContext { orientation, .. }) = expect_slider() else {
        return ().into_any();
    };
    let vertical = move || orientation.get() == Orientation::Vertical;
    let in_range = {
        let mark = mark.clone();
        move || mark.is_in_range().then_some("true")
    };
    let position = format!("{}%", mark.percentage.as_percent());
    let bottom = position.clone();
    let styles = Styles::new()
        .add_unchecked("position", "absolute")
        .add_optional_unchecked("inset-inline-start", move || {
            (!vertical()).then(|| position.clone())
        })
        .add_optional_unchecked("bottom", move || vertical().then(|| bottom.clone()))
        .merge(styles);
    view! {
        <div
            class=classes
            style=styles
            data-in-range=in_range
            data-orientation=move || orientation.get().as_str()
        >
            {children()}
        </div>
    }
    .into_any()
}
