[workspace]
resolver = "2"
members = ["leptonic", "leptonic-theme"]
exclude = ["examples", "testing"]

[workspace.package]
version = "0.5.0"

[workspace.dependencies]
leptonic = { path = "./leptonic", default-features = false }
leptonic_theme = { path = "./leptonic-theme", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

# overrides
[workspace.lints.clippy]
option_if_let_else = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
must_use_candidate = { level = "allow", priority = 1 }
wildcard_imports = { level = "allow", priority = 1 }
