// Generated by scripts/port-intl-strings.py from react-aria-components/intl/*.json @ 99e6102368. Do not edit.
//! Localized messages of the atoms (react-aria-components).

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Select an item", "Resizer", "DropZone", "Color swatches"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "حدد عنصرًا",
            "أداة تغيير الحجم",
            "DropZone",
            "تغييرات الألوان",
        ],
    ),
    (
        "bg-BG",
        &[
            "Изберете предмет",
            "Преоразмерител",
            "DropZone",
            "Цветови мостри",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Vyberte položku",
            "Změna velikosti",
            "Místo pro přetažení",
            "Vzorky barev",
        ],
    ),
    (
        "da-DK",
        &[
            "Vælg et element",
            "Størrelsesændring",
            "DropZone",
            "Farveprøver",
        ],
    ),
    (
        "de-DE",
        &[
            "Element wählen",
            "Größenanpassung",
            "Ablegebereich",
            "Farbfelder",
        ],
    ),
    (
        "el-GR",
        &[
            "Επιλέξτε ένα αντικείμενο",
            "Αλλαγή μεγέθους",
            "DropZone",
            "Χρωματικά δείγματα",
        ],
    ),
    (
        "es-ES",
        &[
            "Seleccionar un artículo",
            "Cambiador de tamaño",
            "DropZone",
            "Muestras de colores",
        ],
    ),
    (
        "et-EE",
        &[
            "Valige üksus",
            "Suuruse muutja",
            "DropZone",
            "Värvinäidised",
        ],
    ),
    (
        "fi-FI",
        &["Valitse kohde", "Koon muuttaja", "DropZone", "Värimallit"],
    ),
    (
        "fr-FR",
        &[
            "Sélectionner un élément",
            "Redimensionneur",
            "DropZone",
            "Échantillons de couleurs",
        ],
    ),
    (
        "he-IL",
        &["בחר פריט", "שינוי גודל", "DropZone", "דוגמיות צבע"],
    ),
    (
        "hr-HR",
        &[
            "Odaberite stavku",
            "Promjena veličine",
            "Zona spuštanja",
            "Uzorci boja",
        ],
    ),
    (
        "hu-HU",
        &[
            "Válasszon ki egy elemet",
            "Átméretező",
            "DropZone",
            "Színtárak",
        ],
    ),
    (
        "it-IT",
        &[
            "Seleziona un elemento",
            "Ridimensionamento",
            "Zona di rilascio",
            "Campioni di colore",
        ],
    ),
    (
        "ja-JP",
        &[
            "項目を選択",
            "サイズ変更ツール",
            "ドロップゾーン",
            "カラースウォッチ",
        ],
    ),
    (
        "ko-KR",
        &["항목 선택", "크기 조정기", "드롭 영역", "색상 견본"],
    ),
    (
        "lt-LT",
        &[
            "Pasirinkite elementą",
            "Dydžio keitiklis",
            "„DropZone“",
            "Spalvų pavyzdžiai",
        ],
    ),
    (
        "lv-LV",
        &[
            "Izvēlēties vienumu",
            "Izmēra mainītājs",
            "DropZone",
            "Krāsu paraugi",
        ],
    ),
    (
        "nb-NO",
        &[
            "Velg et element",
            "Størrelsesendrer",
            "Droppsone",
            "Fargekart",
        ],
    ),
    (
        "nl-NL",
        &["Selecteer een item", "Resizer", "DropZone", "kleurstalen"],
    ),
    (
        "pl-PL",
        &[
            "Wybierz element",
            "Zmiana rozmiaru",
            "Strefa upuszczania",
            "Próbki kolorów",
        ],
    ),
    (
        "pt-BR",
        &[
            "Selecione um item",
            "Redimensionador",
            "DropZone",
            "Amostras de cores",
        ],
    ),
    (
        "pt-PT",
        &[
            "Selecione um item",
            "Redimensionador",
            "DropZone",
            "Amostras de cores",
        ],
    ),
    (
        "ro-RO",
        &[
            "Selectați un element",
            "Instrument de redimensionare",
            "Zonă de plasare",
            "Specimene de culoare",
        ],
    ),
    (
        "ru-RU",
        &[
            "Выберите элемент",
            "Средство изменения размера",
            "DropZone",
            "Цветовые образцы",
        ],
    ),
    (
        "sk-SK",
        &[
            "Vyberte položku",
            "Nástroj na zmenu veľkosti",
            "DropZone",
            "Vzorkovníky farieb",
        ],
    ),
    (
        "sl-SI",
        &[
            "Izberite element",
            "Spreminjanje velikosti",
            "DropZone",
            "Barvne palete",
        ],
    ),
    (
        "sr-SP",
        &[
            "Izaberite stavku",
            "Promena veličine",
            "DropZone",
            "Uzorci boje",
        ],
    ),
    (
        "sv-SE",
        &[
            "Välj en artikel",
            "Storleksändrare",
            "DropZone",
            "Färgrutor",
        ],
    ),
    (
        "tr-TR",
        &[
            "Bir öğe seçin",
            "Yeniden boyutlandırıcı",
            "Bırakma Bölgesi",
            "Renk örnekleri",
        ],
    ),
    (
        "uk-UA",
        &[
            "Виберіть елемент",
            "Засіб змінення розміру",
            "DropZone",
            "Зразки кольорів",
        ],
    ),
    (
        "zh-CN",
        &["选择一个项目", "尺寸调整器", "放置区域", "颜色色板"],
    ),
    ("zh-TW", &["選取項目", "大小調整器", "放置區", "色票"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "selectPlaceholder",
        "tableResizer",
        "dropzoneLabel",
        "colorSwatchPicker",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of the atoms (react-aria-components), in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct AtomStrings(Strings);

impl LocalizedStrings for AtomStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl AtomStrings {
    /// en-US: `Select an item`
    #[must_use]
    pub fn select_placeholder(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `Resizer`
    #[must_use]
    pub fn table_resizer(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `DropZone`
    #[must_use]
    pub fn dropzone_label(&self) -> String {
        self.0.format(2, &[])
    }
    /// en-US: `Color swatches`
    #[must_use]
    pub fn color_swatch_picker(&self) -> String {
        self.0.format(3, &[])
    }
}
