// Generated by scripts/port-intl-strings.py from react-aria/intl/breadcrumbs/*.json @ 99e6102368. Do not edit.
//! Localized messages of breadcrumbs.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Breadcrumbs"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["عناصر الواجهة"]),
    ("bg-BG", &["Трохи хляб"]),
    ("cs-CZ", &["Popis cesty"]),
    ("da-DK", &["Brødkrummer"]),
    ("de-DE", &["Breadcrumbs"]),
    ("el-GR", &["Πλοηγήσεις breadcrumb"]),
    ("es-ES", &["Migas de pan"]),
    ("et-EE", &["Lingiread"]),
    ("fi-FI", &["Navigointilinkit"]),
    ("fr-FR", &["Chemin de navigation"]),
    ("he-IL", &["שבילי ניווט"]),
    ("hr-HR", &["Navigacijski putovi"]),
    ("hu-HU", &["Morzsamenü"]),
    ("it-IT", &["Breadcrumb"]),
    ("ja-JP", &["パンくずリスト"]),
    ("ko-KR", &["탐색 표시"]),
    ("lt-LT", &["Naršymo kelias"]),
    ("lv-LV", &["Atpakaļceļi"]),
    ("nb-NO", &["Navigasjonsstier"]),
    ("nl-NL", &["Broodkruimels"]),
    ("pl-PL", &["Struktura nawigacyjna"]),
    ("pt-BR", &["Caminho detalhado"]),
    ("pt-PT", &["Categorias"]),
    ("ro-RO", &["Miez de pâine"]),
    ("ru-RU", &["Навигация"]),
    ("sk-SK", &["Navigačné prvky Breadcrumbs"]),
    ("sl-SI", &["Drobtine"]),
    ("sr-SP", &["Putanje navigacije"]),
    ("sv-SE", &["Sökvägar"]),
    ("tr-TR", &["İçerik haritaları"]),
    ("uk-UA", &["Навігаційна стежка"]),
    ("zh-CN", &["导航栏"]),
    ("zh-TW", &["導覽列"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["breadcrumbs"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of breadcrumbs, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct BreadcrumbsStrings(Strings);

impl LocalizedStrings for BreadcrumbsStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl BreadcrumbsStrings {
    /// en-US: `Breadcrumbs`
    #[must_use]
    pub fn breadcrumbs(&self) -> String {
        self.0.format(0, &[])
    }
}
