// Generated by scripts/port-intl-strings.py from react-aria/intl/calendar/*.json @ 99e6102368. Do not edit.
//! Localized messages of calendars.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Previous",
    "Next",
    "Selected Date: {date}",
    "Selected Range: {dateRange}",
    "Today, {date}",
    "Today, {date} selected",
    "{date} selected",
    "Click to start selecting date range",
    "Click to finish selecting date range",
    "First available date",
    "Last available date",
    "{startDate} to {endDate}",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "السابق",
            "التالي",
            "تاريخ محدد: {date}",
            "المدى الزمني المحدد: {dateRange}",
            "اليوم، {date}",
            "اليوم، {date} محدد",
            "{date} المحدد",
            "انقر لبدء عملية تحديد نطاق التاريخ",
            "انقر لإنهاء عملية تحديد نطاق التاريخ",
            "أول تاريخ متاح",
            "آخر تاريخ متاح",
            "{startDate} إلى {endDate}",
        ],
    ),
    (
        "bg-BG",
        &[
            "Назад",
            "Напред",
            "Избрана дата: {date}",
            "Избран диапазон: {dateRange}",
            "Днес, {date}",
            "Днес, {date} са избрани",
            "Избрано е {date}",
            "Натиснете, за да пристъпите към избора на времеви интервал",
            "Натиснете, за да довършите избора на времеви интервал",
            "Първа налична дата",
            "Последна налична дата",
            "{startDate} до {endDate}",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Předchozí",
            "Další",
            "Vybrané datum: {date}",
            "Vybrané období: {dateRange}",
            "Dnes, {date}",
            "Dnes, vybráno {date}",
            "Vybráno {date}",
            "Kliknutím zahájíte výběr rozsahu dat",
            "Kliknutím dokončíte výběr rozsahu dat",
            "První dostupné datum",
            "Poslední dostupné datum",
            "{startDate} až {endDate}",
        ],
    ),
    (
        "da-DK",
        &[
            "Forrige",
            "Næste",
            "Valgt dato: {date}",
            "Valgt interval: {dateRange}",
            "I dag, {date}",
            "I dag, {date} valgt",
            "{date} valgt",
            "Klik for at starte valg af datoområde",
            "Klik for at fuldføre valg af datoområde",
            "Første ledige dato",
            "Sidste ledige dato",
            "{startDate} til {endDate}",
        ],
    ),
    (
        "de-DE",
        &[
            "Zurück",
            "Weiter",
            "Ausgewähltes Datum: {date}",
            "Ausgewählter Bereich: {dateRange}",
            "Heute, {date}",
            "Heute, {date} ausgewählt",
            "{date} ausgewählt",
            "Klicken, um die Auswahl des Datumsbereichs zu beginnen",
            "Klicken, um die Auswahl des Datumsbereichs zu beenden",
            "Erstes verfügbares Datum",
            "Letztes verfügbares Datum",
            "{startDate} bis {endDate}",
        ],
    ),
    (
        "el-GR",
        &[
            "Προηγούμενο",
            "Επόμενο",
            "Επιλεγμένη ημερομηνία: {date}",
            "Επιλεγμένο εύρος: {dateRange}",
            "Σήμερα, {date}",
            "Σήμερα, επιλέχτηκε {date}",
            "Επιλέχθηκε {date}",
            "Κάντε κλικ για να ξεκινήσετε την επιλογή εύρους ημερομηνιών",
            "Κάντε κλικ για να ολοκληρώσετε την επιλογή εύρους ημερομηνιών",
            "Πρώτη διαθέσιμη ημερομηνία",
            "Τελευταία διαθέσιμη ημερομηνία",
            "{startDate} έως {endDate}",
        ],
    ),
    (
        "es-ES",
        &[
            "Anterior",
            "Siguiente",
            "Fecha seleccionada: {date}",
            "Intervalo seleccionado: {dateRange}",
            "Hoy, {date}",
            "Hoy, {date} seleccionado",
            "{date} seleccionado",
            "Haga clic para comenzar a seleccionar un rango de fechas",
            "Haga clic para terminar de seleccionar rango de fechas",
            "Primera fecha disponible",
            "Última fecha disponible",
            "{startDate} a {endDate}",
        ],
    ),
    (
        "et-EE",
        &[
            "Eelmine",
            "Järgmine",
            "Valitud kuupäev: {date}",
            "Valitud vahemik: {dateRange}",
            "Täna, {date}",
            "Täna, {date} valitud",
            "{date} valitud",
            "Klõpsake kuupäevavahemiku valimiseks",
            "Klõpsake kuupäevavahemiku valimise lõpetamiseks",
            "Esimene saadaolev kuupäev",
            "Viimane saadaolev kuupäev",
            "{startDate} kuni {endDate}",
        ],
    ),
    (
        "fi-FI",
        &[
            "Edellinen",
            "Seuraava",
            "Valittu päivämäärä: {date}",
            "Valittu aikaväli: {dateRange}",
            "Tänään, {date}",
            "Tänään, {date} valittu",
            "{date} valittu",
            "Aloita päivämääräalueen valinta napsauttamalla tätä.",
            "Lopeta päivämääräalueen valinta napsauttamalla tätä.",
            "Ensimmäinen varattavissa oleva päivämäärä",
            "Viimeinen varattavissa oleva päivämäärä",
            "{startDate} – {endDate}",
        ],
    ),
    (
        "fr-FR",
        &[
            "Précédent",
            "Suivant",
            "Date sélectionnée\u{a0}: {date}",
            "Plage sélectionnée\u{a0}: {dateRange}",
            "Aujourd'hui, {date}",
            "Aujourd’hui, {date} sélectionné",
            "{date} sélectionné",
            "Cliquer pour commencer à sélectionner la plage de dates",
            "Cliquer pour finir de sélectionner la plage de dates",
            "Première date disponible",
            "Dernière date disponible",
            "{startDate} à {endDate}",
        ],
    ),
    (
        "he-IL",
        &[
            "הקודם",
            "הבא",
            "תאריך נבחר: {date}",
            "טווח נבחר: {dateRange}",
            "היום, {date}",
            "היום, {date} נבחר",
            "{date} נבחר",
            "לחץ כדי להתחיל בבחירת טווח התאריכים",
            "חץ כדי לסיים את בחירת טווח התאריכים",
            "תאריך פנוי ראשון",
            "תאריך פנוי אחרון",
            "{startDate} עד {endDate}",
        ],
    ),
    (
        "hr-HR",
        &[
            "Prethodni",
            "Sljedeći",
            "Odabrani datum: {date}",
            "Odabrani raspon: {dateRange}",
            "Danas, {date}",
            "Danas, odabran {date}",
            "{date} odabran",
            "Kliknite da započnete raspon odabranih datuma",
            "Kliknite da dovršite raspon odabranih datuma",
            "Prvi raspoloživi datum",
            "Posljednji raspoloživi datum",
            "{startDate} do {endDate}",
        ],
    ),
    (
        "hu-HU",
        &[
            "Előző",
            "Következő",
            "Kijelölt dátum: {date}",
            "Kijelölt tartomány: {dateRange}",
            "Ma, {date}",
            "Ma, {date} kijelölve",
            "{date} kiválasztva",
            "Kattintson a dátumtartomány kijelölésének indításához",
            "Kattintson a dátumtartomány kijelölésének befejezéséhez",
            "Az első elérhető dátum",
            "Utolsó elérhető dátum",
            "{startDate}–{endDate}",
        ],
    ),
    (
        "it-IT",
        &[
            "Precedente",
            "Successivo",
            "Data selezionata: {date}",
            "Intervallo selezionato: {dateRange}",
            "Oggi, {date}",
            "Oggi, {date} selezionata",
            "{date} selezionata",
            "Fai clic per selezionare l’intervallo di date",
            "Fai clic per completare la selezione dell’intervallo di date",
            "Prima data disponibile",
            "Ultima data disponibile",
            "Da {startDate} a {endDate}",
        ],
    ),
    (
        "ja-JP",
        &[
            "前へ",
            "次へ",
            "選択した日付 : {date}",
            "選択範囲 : {dateRange}",
            "本日、{date}",
            "本日、{date} を選択",
            "{date} を選択",
            "クリックして日付範囲の選択を開始",
            "クリックして日付範囲の選択を終了",
            "最初の利用可能日",
            "最終利用可能日",
            "{startDate} から {endDate}",
        ],
    ),
    (
        "ko-KR",
        &[
            "이전",
            "다음",
            "선택 일자: {date}",
            "선택 범위: {dateRange}",
            "오늘, {date}",
            "오늘, {date} 선택됨",
            "{date} 선택됨",
            "날짜 범위 선택을 시작하려면 클릭하십시오.",
            "날짜 범위 선택을 완료하려면 클릭하십시오.",
            "처음으로 사용 가능한 일자",
            "마지막으로 사용 가능한 일자",
            "{startDate} ~ {endDate}",
        ],
    ),
    (
        "lt-LT",
        &[
            "Ankstesnis",
            "Paskesnis",
            "Pasirinkta data: {date}",
            "Pasirinktas intervalas: {dateRange}",
            "Šiandien, {date}",
            "Šiandien, pasirinkta {date}",
            "Pasirinkta {date}",
            "Spustelėkite, kad pradėtumėte pasirinkti datų intervalą",
            "Spustelėkite, kad baigtumėte pasirinkti datų intervalą",
            "Pirmoji galima data",
            "Paskutinė galima data",
            "Nuo {startDate} iki {endDate}",
        ],
    ),
    (
        "lv-LV",
        &[
            "Atpakaļ",
            "Tālāk",
            "Atlasītais datums: {date}",
            "Atlasītais diapazons: {dateRange}",
            "Šodien, {date}",
            "Atlasīta šodiena, {date}",
            "Atlasīts: {date}",
            "Noklikšķiniet, lai sāktu datumu diapazona atlasi",
            "Noklikšķiniet, lai pabeigtu datumu diapazona atlasi",
            "Pirmais pieejamais datums",
            "Pēdējais pieejamais datums",
            "No {startDate} līdz {endDate}",
        ],
    ),
    (
        "nb-NO",
        &[
            "Forrige",
            "Neste",
            "Valgt dato: {date}",
            "Valgt område: {dateRange}",
            "I dag, {date}",
            "I dag, {date} valgt",
            "{date} valgt",
            "Klikk for å starte valg av datoområde",
            "Klikk for å fullføre valg av datoområde",
            "Første tilgjengelige dato",
            "Siste tilgjengelige dato",
            "{startDate} til {endDate}",
        ],
    ),
    (
        "nl-NL",
        &[
            "Vorige",
            "Volgende",
            "Geselecteerde datum: {date}",
            "Geselecteerd bereik: {dateRange}",
            "Vandaag, {date}",
            "Vandaag, {date} geselecteerd",
            "{date} geselecteerd",
            "Klik om het datumbereik te selecteren",
            "Klik om de selectie van het datumbereik te voltooien",
            "Eerste beschikbare datum",
            "Laatste beschikbare datum",
            "{startDate} tot {endDate}",
        ],
    ),
    (
        "pl-PL",
        &[
            "Wstecz",
            "Dalej",
            "Wybrana data: {date}",
            "Wybrany zakres: {dateRange}",
            "Dzisiaj, {date}",
            "Dzisiaj wybrano {date}",
            "Wybrano {date}",
            "Kliknij, aby rozpocząć wybór zakresu dat",
            "Kliknij, aby zakończyć wybór zakresu dat",
            "Pierwsza dostępna data",
            "Ostatnia dostępna data",
            "{startDate} do {endDate}",
        ],
    ),
    (
        "pt-BR",
        &[
            "Anterior",
            "Próximo",
            "Data selecionada: {date}",
            "Intervalo selecionado: {dateRange}",
            "Hoje, {date}",
            "Hoje, {date} selecionado",
            "{date} selecionado",
            "Clique para iniciar a seleção do intervalo de datas",
            "Clique para concluir a seleção do intervalo de datas",
            "Primeira data disponível",
            "Última data disponível",
            "{startDate} a {endDate}",
        ],
    ),
    (
        "pt-PT",
        &[
            "Anterior",
            "Próximo",
            "Data selecionada: {date}",
            "Intervalo selecionado: {dateRange}",
            "Hoje, {date}",
            "Hoje, {date} selecionado",
            "{date} selecionado",
            "Clique para começar a selecionar o intervalo de datas",
            "Clique para terminar de selecionar o intervalo de datas",
            "Primeira data disponível",
            "Última data disponível",
            "{startDate} a {endDate}",
        ],
    ),
    (
        "ro-RO",
        &[
            "Înainte",
            "Următorul",
            "Dată selectată: {date}",
            "Interval selectat: {dateRange}",
            "Astăzi, {date}",
            "Azi, {date} selectată",
            "{date} selectată",
            "Apăsaţi pentru a începe selecţia razei pentru dată",
            "Apăsaţi pentru a finaliza selecţia razei pentru dată",
            "Prima dată disponibilă",
            "Ultima dată disponibilă",
            "De la {startDate} până la {endDate}",
        ],
    ),
    (
        "ru-RU",
        &[
            "Назад",
            "Далее",
            "Выбранная дата: {date}",
            "Выбранный диапазон: {dateRange}",
            "Сегодня, {date}",
            "Сегодня, выбрано {date}",
            "Выбрано {date}",
            "Щелкните, чтобы начать выбор диапазона дат",
            "Щелкните, чтобы завершить выбор диапазона дат",
            "Первая доступная дата",
            "Последняя доступная дата",
            "С {startDate} по {endDate}",
        ],
    ),
    (
        "sk-SK",
        &[
            "Predchádzajúce",
            "Nasledujúce",
            "Vybratý dátum: {date}",
            "Vybratý rozsah: {dateRange}",
            "Dnes {date}",
            "Vybratý dnešný dátum {date}",
            "Vybratý dátum {date}",
            "Kliknutím spustíte výber rozsahu dátumov",
            "Kliknutím dokončíte výber rozsahu dátumov",
            "Prvý dostupný dátum",
            "Posledný dostupný dátum",
            "Od {startDate} do {endDate}",
        ],
    ),
    (
        "sl-SI",
        &[
            "Nazaj",
            "Naprej",
            "Izbrani datum: {date}",
            "Izbrano območje: {dateRange}",
            "Danes, {date}",
            "Danes, {date} izbrano",
            "{date} izbrano",
            "Kliknite za začetek izbire datumskega obsega",
            "Kliknite za dokončanje izbire datumskega obsega",
            "Prvi razpoložljivi datum",
            "Zadnji razpoložljivi datum",
            "{startDate} do {endDate}",
        ],
    ),
    (
        "sr-SP",
        &[
            "Prethodni",
            "Sledeći",
            "Izabrani datum: {date}",
            "Izabrani period: {dateRange}",
            "Danas, {date}",
            "Danas, izabran {date}",
            "{date} izabran",
            "Kliknite da započnete opseg izabranih datuma",
            "Kliknite da dovršite opseg izabranih datuma",
            "Prvi raspoloživi datum",
            "Zadnji raspoloživi datum",
            "{startDate} do {endDate}",
        ],
    ),
    (
        "sv-SE",
        &[
            "Föregående",
            "Nästa",
            "Valt datum: {date}",
            "Valt intervall: {dateRange}",
            "Idag, {date}",
            "Idag, {date} har valts",
            "{date} har valts",
            "Klicka för att välja datumintervall",
            "Klicka för att avsluta val av datumintervall",
            "Första tillgängliga datum",
            "Sista tillgängliga datum",
            "{startDate} till {endDate}",
        ],
    ),
    (
        "tr-TR",
        &[
            "Önceki",
            "Sonraki",
            "Seçilen Tarih: {date}",
            "Seçilen Aralık: {dateRange}",
            "Bugün, {date}",
            "Bugün, {date} seçildi",
            "{date} seçildi",
            "Tarih aralığı seçimini başlatmak için tıklayın",
            "Tarih aralığı seçimini tamamlamak için tıklayın",
            "İlk müsait tarih",
            "Son müsait tarih",
            "{startDate} - {endDate}",
        ],
    ),
    (
        "uk-UA",
        &[
            "Попередній",
            "Наступний",
            "Вибрана дата: {date}",
            "Вибраний діапазон: {dateRange}",
            "Сьогодні, {date}",
            "Сьогодні, вибрано {date}",
            "Вибрано {date}",
            "Натисніть, щоб почати вибір діапазону дат",
            "Натисніть, щоб завершити вибір діапазону дат",
            "Перша доступна дата",
            "Остання доступна дата",
            "{startDate} — {endDate}",
        ],
    ),
    (
        "zh-CN",
        &[
            "上一页",
            "下一页",
            "选定的日期：{date}",
            "选定的范围：{dateRange}",
            "今天，即 {date}",
            "已选择今天，即 {date}",
            "已选择 {date}",
            "单击以开始选择日期范围",
            "单击以完成选择日期范围",
            "第一个可用日期",
            "最后一个可用日期",
            "{startDate} 至 {endDate}",
        ],
    ),
    (
        "zh-TW",
        &[
            "上一頁",
            "下一頁",
            "選定的日期：{date}",
            "選定的範圍：{dateRange}",
            "今天，{date}",
            "已選取今天，{date}",
            "已選取 {date}",
            "按一下以開始選取日期範圍",
            "按一下以完成選取日期範圍",
            "第一個可用日期",
            "最後一個可用日期",
            "{startDate} 至 {endDate}",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "previous",
        "next",
        "selectedDateDescription",
        "selectedRangeDescription",
        "todayDate",
        "todayDateSelected",
        "dateSelected",
        "startRangeSelectionPrompt",
        "finishRangeSelectionPrompt",
        "minimumDate",
        "maximumDate",
        "dateRange",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of calendars, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct CalendarStrings(Strings);

impl LocalizedStrings for CalendarStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl CalendarStrings {
    /// en-US: `Previous`
    #[must_use]
    pub fn previous(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `Next`
    #[must_use]
    pub fn next(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `Selected Date: {date}`
    #[must_use]
    pub fn selected_date_description(&self, date: &str) -> String {
        self.0.format(2, &[("date", Arg::Str(date))])
    }
    /// en-US: `Selected Range: {dateRange}`
    #[must_use]
    pub fn selected_range_description(&self, date_range: &str) -> String {
        self.0.format(3, &[("dateRange", Arg::Str(date_range))])
    }
    /// en-US: `Today, {date}`
    #[must_use]
    pub fn today_date(&self, date: &str) -> String {
        self.0.format(4, &[("date", Arg::Str(date))])
    }
    /// en-US: `Today, {date} selected`
    #[must_use]
    pub fn today_date_selected(&self, date: &str) -> String {
        self.0.format(5, &[("date", Arg::Str(date))])
    }
    /// en-US: `{date} selected`
    #[must_use]
    pub fn date_selected(&self, date: &str) -> String {
        self.0.format(6, &[("date", Arg::Str(date))])
    }
    /// en-US: `Click to start selecting date range`
    #[must_use]
    pub fn start_range_selection_prompt(&self) -> String {
        self.0.format(7, &[])
    }
    /// en-US: `Click to finish selecting date range`
    #[must_use]
    pub fn finish_range_selection_prompt(&self) -> String {
        self.0.format(8, &[])
    }
    /// en-US: `First available date`
    #[must_use]
    pub fn minimum_date(&self) -> String {
        self.0.format(9, &[])
    }
    /// en-US: `Last available date`
    #[must_use]
    pub fn maximum_date(&self) -> String {
        self.0.format(10, &[])
    }
    /// en-US: `{startDate} to {endDate}`
    #[must_use]
    pub fn date_range(&self, args: DateRangeArgs<'_>) -> String {
        self.0.format(
            11,
            &[
                ("startDate", Arg::Str(args.start_date)),
                ("endDate", Arg::Str(args.end_date)),
            ],
        )
    }
}

/// The arguments of [`CalendarStrings::date_range`].
#[derive(Debug, Clone, Copy)]
pub struct DateRangeArgs<'a> {
    pub start_date: &'a str,
    pub end_date: &'a str,
}
