// Generated by scripts/port-intl-strings.py from react-aria/intl/color/*.json @ 99e6102368. Do not edit.
//! Localized messages of the color hooks.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Color picker",
    "2D slider",
    "{name}: {value}",
    "{label}, {channelLabel}",
    "color swatch",
    "transparent",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "أداة انتقاء اللون",
            "مُنزلق 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "تغيير الألوان",
            "شفاف",
        ],
    ),
    (
        "bg-BG",
        &[
            "Средство за избиране на цвят",
            "2D плъзгач",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "цветна мостра",
            "прозрачен",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Výběr barvy",
            "2D posuvník",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "barevný vzorek",
            "průhledný",
        ],
    ),
    (
        "da-DK",
        &[
            "Farvevælger",
            "2D-skyder",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "farveprøve",
            "gennemsigtig",
        ],
    ),
    (
        "de-DE",
        &[
            "Farbwähler",
            "2D-Schieberegler",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "Farbfeld",
            "transparent",
        ],
    ),
    (
        "el-GR",
        &[
            "Επιλογέας χρωμάτων",
            "Ρυθμιστικό 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "χρωματικό δείγμα",
            "διαφανές",
        ],
    ),
    (
        "es-ES",
        &[
            "Selector de color",
            "Regulador 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "muestra de color",
            "transparente",
        ],
    ),
    (
        "et-EE",
        &[
            "Värvivalija",
            "2D-liugur",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "värvinäidis",
            "läbipaistev",
        ],
    ),
    (
        "fi-FI",
        &[
            "Värimuokkain",
            "2D-liukusäädin",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "värimalli",
            "läpinäkyvä",
        ],
    ),
    (
        "fr-FR",
        &[
            "Sélecteur de couleurs",
            "Curseur\u{a0}2D",
            "{name}\u{a0}: {value}",
            "{label}, {channelLabel}",
            "Échantillon de couleurs",
            "Transparent",
        ],
    ),
    (
        "he-IL",
        &[
            "בוחר הצבעים",
            "מחוון דו מימדי",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "דוגמית צבע",
            "שקוף",
        ],
    ),
    (
        "hr-HR",
        &[
            "Odabir boje",
            "2D klizač",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "uzorak boje",
            "transparentno",
        ],
    ),
    (
        "hu-HU",
        &[
            "Színválasztó",
            "2D-csúszka",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "színtár",
            "átlátszó",
        ],
    ),
    (
        "it-IT",
        &[
            "Selettore colore",
            "Cursore 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "campione di colore",
            "trasparente",
        ],
    ),
    (
        "ja-JP",
        &[
            "カラーピッカー",
            "2D スライダー",
            "{name} : {value}",
            "{label}、{channelLabel}",
            "カラースウォッチ",
            "透明",
        ],
    ),
    (
        "ko-KR",
        &[
            "색상 피커",
            "2D 슬라이더",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "색상 견본",
            "투명도",
        ],
    ),
    (
        "lt-LT",
        &[
            "Spalvų parinkiklis",
            "2D slankiklis",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "spalvų pavyzdys",
            "skaidrus",
        ],
    ),
    (
        "lv-LV",
        &[
            "Krāsu atlasītājs",
            "2D slīdnis",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "krāsu paraugs",
            "caurspīdīgs",
        ],
    ),
    (
        "nb-NO",
        &[
            "Fargevelger",
            "2D-glidebryter",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "fargekart",
            "gjennomsiktig",
        ],
    ),
    (
        "nl-NL",
        &[
            "Kleurkiezer",
            "2D-schuifregelaar",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "kleurstaal",
            "transparant",
        ],
    ),
    (
        "pl-PL",
        &[
            "Próbnik kolorów",
            "Suwak 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "próbka koloru",
            "przezroczysty",
        ],
    ),
    (
        "pt-BR",
        &[
            "Seletor de cores",
            "Controle deslizante 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "amostra de cores",
            "transparente",
        ],
    ),
    (
        "pt-PT",
        &[
            "Seletor de cores",
            "Controle deslizante 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "amostra de cor",
            "transparente",
        ],
    ),
    (
        "ro-RO",
        &[
            "Selector de culori",
            "Glisor 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "specimen de culoare",
            "transparent",
        ],
    ),
    (
        "ru-RU",
        &[
            "Палитра цветов",
            "Ползунок 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "цветовой образец",
            "прозрачный",
        ],
    ),
    (
        "sk-SK",
        &[
            "Výber farieb",
            "2D jazdec",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "vzorkovník farieb",
            "transparentný",
        ],
    ),
    (
        "sl-SI",
        &[
            "Izbirnik barv",
            "2D drsnik",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "barvna paleta",
            "prozorno",
        ],
    ),
    (
        "sr-SP",
        &[
            "Birač boja",
            "2D klizač",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "Uzorak boje",
            "providno",
        ],
    ),
    (
        "sv-SE",
        &[
            "Färgväljaren",
            "2D-reglage",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "färgruta",
            "genomskinlig",
        ],
    ),
    (
        "tr-TR",
        &[
            "Renk Seçici",
            "2D sürgü",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "renk örneği",
            "saydam",
        ],
    ),
    (
        "uk-UA",
        &[
            "Палітра кольорів",
            "Повзунок 2D",
            "{name}: {value}",
            "{label}, {channelLabel}",
            "зразок кольору",
            "прозорий",
        ],
    ),
    (
        "zh-CN",
        &[
            "拾色器",
            "2D 滑块",
            "{name}：{value}",
            "{label}、{channelLabel}",
            "颜色色板",
            "透明",
        ],
    ),
    (
        "zh-TW",
        &[
            "檢色器",
            "2D 滑桿",
            "{name}：{value}",
            "{label}，{channelLabel}",
            "色票",
            "透明",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "colorPicker",
        "twoDimensionalSlider",
        "colorNameAndValue",
        "colorInputLabel",
        "colorSwatch",
        "transparent",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of the color hooks, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct ColorStrings(Strings);

impl LocalizedStrings for ColorStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl ColorStrings {
    /// en-US: `Color picker`
    #[must_use]
    pub fn color_picker(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `2D slider`
    #[must_use]
    pub fn two_dimensional_slider(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `{name}: {value}`
    #[must_use]
    pub fn color_name_and_value(&self, args: ColorNameAndValueArgs<'_>) -> String {
        self.0.format(
            2,
            &[
                ("name", Arg::Str(args.name)),
                ("value", Arg::Str(args.value)),
            ],
        )
    }
    /// en-US: `{label}, {channelLabel}`
    #[must_use]
    pub fn color_input_label(&self, args: ColorInputLabelArgs<'_>) -> String {
        self.0.format(
            3,
            &[
                ("label", Arg::Str(args.label)),
                ("channelLabel", Arg::Str(args.channel_label)),
            ],
        )
    }
    /// en-US: `color swatch`
    #[must_use]
    pub fn color_swatch(&self) -> String {
        self.0.format(4, &[])
    }
    /// en-US: `transparent`
    #[must_use]
    pub fn transparent(&self) -> String {
        self.0.format(5, &[])
    }
}

/// The arguments of [`ColorStrings::color_name_and_value`].
#[derive(Debug, Clone, Copy)]
pub struct ColorNameAndValueArgs<'a> {
    pub name: &'a str,
    pub value: &'a str,
}

/// The arguments of [`ColorStrings::color_input_label`].
#[derive(Debug, Clone, Copy)]
pub struct ColorInputLabelArgs<'a> {
    pub label: &'a str,
    pub channel_label: &'a str,
}
