// Generated by scripts/port-intl-strings.py from react-aria/intl/combobox/*.json @ 99e6102368. Do not edit.
//! Localized messages of combo boxes.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "{isGroupChange, select, true {Entered group {groupTitle}, with {groupCount, plural, one {# option} other {# options}}. } other {}}{optionText}{isSelected, select, true {, selected} other {}}",
    "{optionCount, plural, one {# option} other {# options}} available.",
    "{optionText}, selected",
    "Show suggestions",
    "Suggestions",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "{isGroupChange, select, true {المجموعة المدخلة {groupTitle}, مع {groupCount, plural, one {# خيار} other {# خيارات}}. } other {}}{optionText}{isSelected, select, true {, محدد} other {}}",
            "{optionCount, plural, one {# خيار} other {# خيارات}} متاحة.",
            "{optionText}، محدد",
            "عرض المقترحات",
            "مقترحات",
        ],
    ),
    (
        "bg-BG",
        &[
            "{isGroupChange, select, true {Въведена група {groupTitle}, с {groupCount, plural, one {# опция} other {# опции}}. } other {}}{optionText}{isSelected, select, true {, избрани} other {}}",
            "{optionCount, plural, one {# опция} other {# опции}} на разположение.",
            "{optionText}, избрани",
            "Покажи предложения",
            "Предложения",
        ],
    ),
    (
        "cs-CZ",
        &[
            "{isGroupChange, select, true {Zadaná skupina „{groupTitle}“ {groupCount, plural, one {s # možností} other {se # možnostmi}}. } other {}}{optionText}{isSelected, select, true { (vybráno)} other {}}",
            "K dispozici {optionCount, plural, one {je # možnost} other {jsou/je # možnosti/-í}}.",
            "{optionText}, vybráno",
            "Zobrazit doporučení",
            "Návrhy",
        ],
    ),
    (
        "da-DK",
        &[
            "{isGroupChange, select, true {Angivet gruppe {groupTitle}, med {groupCount, plural, one {# mulighed} other {# muligheder}}. } other {}}{optionText}{isSelected, select, true {, valgt} other {}}",
            "{optionCount, plural, one {# mulighed tilgængelig} other {# muligheder tilgængelige}}.",
            "{optionText}, valgt",
            "Vis forslag",
            "Forslag",
        ],
    ),
    (
        "de-DE",
        &[
            "{isGroupChange, select, true {Eingetretene Gruppe {groupTitle}, mit {groupCount, plural, one {# Option} other {# Optionen}}. } other {}}{optionText}{isSelected, select, true {, ausgewählt} other {}}",
            "{optionCount, plural, one {# Option} other {# Optionen}} verfügbar.",
            "{optionText}, ausgewählt",
            "Empfehlungen anzeigen",
            "Empfehlungen",
        ],
    ),
    (
        "el-GR",
        &[
            "{isGroupChange, select, true {Εισαγμένη ομάδα {groupTitle}, με {groupCount, plural, one {# επιλογή} other {# επιλογές}}. } other {}}{optionText}{isSelected, select, true {, επιλεγμένο} other {}}",
            "{optionCount, plural, one {# επιλογή} other {# επιλογές }} διαθέσιμες.",
            "{optionText}, επιλέχθηκε",
            "Προβολή προτάσεων",
            "Προτάσεις",
        ],
    ),
    (
        "es-ES",
        &[
            "{isGroupChange, select, true {Se ha unido al grupo {groupTitle}, con {groupCount, plural, one {# opción} other {# opciones}}. } other {}}{optionText}{isSelected, select, true {, seleccionado} other {}}",
            "{optionCount, plural, one {# opción} other {# opciones}} disponible(s).",
            "{optionText}, seleccionado",
            "Mostrar sugerencias",
            "Sugerencias",
        ],
    ),
    (
        "et-EE",
        &[
            "{isGroupChange, select, true {Sisestatud rühm {groupTitle}, valikuga {groupCount, plural, one {# valik} other {# valikud}}. } other {}}{optionText}{isSelected, select, true {, valitud} other {}}",
            "{optionCount, plural, one {# valik} other {# valikud}} saadaval.",
            "{optionText}, valitud",
            "Kuva soovitused",
            "Soovitused",
        ],
    ),
    (
        "fi-FI",
        &[
            "{isGroupChange, select, true {Siirtyi ryhmään {groupTitle}, jossa {groupCount, plural, one {# vaihtoehto} other {# vaihtoehtoa}}.} other {}}{optionText}{isSelected, select, true {, valittu} other {}}",
            "{optionCount, plural, one {# vaihtoehto} other {# vaihtoehtoa}} saatavilla.",
            "{optionText}, valittu",
            "Näytä ehdotukset",
            "Ehdotukset",
        ],
    ),
    (
        "fr-FR",
        &[
            "{isGroupChange, select, true {Groupe {groupTitle} rejoint, avec {groupCount, plural, one {# option} other {# options}}. } other {}}{optionText}{isSelected, select, true {, sélectionné(s)} other {}}",
            "{optionCount, plural, one {# option} other {# options}} disponible(s).",
            "{optionText}, sélectionné",
            "Afficher les suggestions",
            "Suggestions",
        ],
    ),
    (
        "he-IL",
        &[
            "{isGroupChange, select, true {נכנס לקבוצה {groupTitle}, עם {groupCount, plural, one {אפשרות #} other {# אפשרויות}}. } other {}}{optionText}{isSelected, select, true {, נבחר} other {}}",
            "{optionCount, plural, one {אפשרות #} other {# אפשרויות}} במצב זמין.",
            "{optionText}, נבחר",
            "הצג הצעות",
            "הצעות",
        ],
    ),
    (
        "hr-HR",
        &[
            "{isGroupChange, select, true {Unesena skupina {groupTitle}, s {groupCount, plural, one {# opcijom} other {# opcije/a}}. } other {}}{optionText}{isSelected, select, true {, odabranih} other {}}",
            "Dostupno još: {optionCount, plural, one {# opcija} other {# opcije/a}}.",
            "{optionText}, odabrano",
            "Prikaži prijedloge",
            "Prijedlozi",
        ],
    ),
    (
        "hu-HU",
        &[
            "{isGroupChange, select, true {Belépett a(z) {groupTitle} csoportba, amely {groupCount, plural, one {# lehetőséget} other {# lehetőséget}} tartalmaz. } other {}}{optionText}{isSelected, select, true {, kijelölve} other {}}",
            "{optionCount, plural, one {# lehetőség} other {# lehetőség}} áll rendelkezésre.",
            "{optionText}, kijelölve",
            "Javaslatok megjelenítése",
            "Javaslatok",
        ],
    ),
    (
        "it-IT",
        &[
            "{isGroupChange, select, true {Ingresso nel gruppo {groupTitle}, con {groupCount, plural, one {# opzione} other {# opzioni}}. } other {}}{optionText}{isSelected, select, true {, selezionato} other {}}",
            "{optionCount, plural, one {# opzione disponibile} other {# opzioni disponibili}}.",
            "{optionText}, selezionato",
            "Mostra suggerimenti",
            "Suggerimenti",
        ],
    ),
    (
        "ja-JP",
        &[
            "{isGroupChange, select, true {入力されたグループ {groupTitle}、{groupCount, plural, one {# 個のオプション} other {# 個のオプション}}を含む。} other {}}{optionText}{isSelected, select, true {、選択済み} other {}}",
            "{optionCount, plural, one {# 個のオプション} other {# 個のオプション}}を利用できます。",
            "{optionText}、選択済み",
            "候補を表示",
            "候補",
        ],
    ),
    (
        "ko-KR",
        &[
            "{isGroupChange, select, true {입력한 그룹 {groupTitle}, {groupCount, plural, one {#개 옵션} other {#개 옵션}}. } other {}}{optionText}{isSelected, select, true {, 선택됨} other {}}",
            "{optionCount, plural, one {#개 옵션} other {#개 옵션}}을 사용할 수 있습니다.",
            "{optionText}, 선택됨",
            "제안 사항 표시",
            "제안",
        ],
    ),
    (
        "lt-LT",
        &[
            "{isGroupChange, select, true {Įvesta grupė {groupTitle}, su {groupCount, plural, one {# parinktimi} other {# parinktimis (-ių)}}. } other {}}{optionText}{isSelected, select, true {, pasirinkta} other {}}",
            "Yra {optionCount, plural, one {# parinktis} other {# parinktys (-ių)}}.",
            "{optionText}, pasirinkta",
            "Rodyti pasiūlymus",
            "Pasiūlymai",
        ],
    ),
    (
        "lv-LV",
        &[
            "{isGroupChange, select, true {Ievadīta grupa {groupTitle}, ar {groupCount, plural, one {# opciju} other {# opcijām}}. } other {}}{optionText}{isSelected, select, true {, atlasīta} other {}}",
            "Pieejamo opciju skaits: {optionCount, plural, one {# opcija} other {# opcijas}}.",
            "{optionText}, atlasīta",
            "Rādīt ieteikumus",
            "Ieteikumi",
        ],
    ),
    (
        "nb-NO",
        &[
            "{isGroupChange, select, true {Angitt gruppe {groupTitle}, med {groupCount, plural, one {# alternativ} other {# alternativer}}. } other {}}{optionText}{isSelected, select, true {, valgt} other {}}",
            "{optionCount, plural, one {# alternativ} other {# alternativer}} finnes.",
            "{optionText}, valgt",
            "Vis forslag",
            "Forslag",
        ],
    ),
    (
        "nl-NL",
        &[
            "{isGroupChange, select, true {Groep {groupTitle} ingevoerd met {groupCount, plural, one {# optie} other {# opties}}. } other {}}{optionText}{isSelected, select, true {, geselecteerd} other {}}",
            "{optionCount, plural, one {# optie} other {# opties}} beschikbaar.",
            "{optionText}, geselecteerd",
            "Suggesties weergeven",
            "Suggesties",
        ],
    ),
    (
        "pl-PL",
        &[
            "{isGroupChange, select, true {Dołączono do grupy {groupTitle}, z {groupCount, plural, one {# opcją} other {# opcjami}}. } other {}}{optionText}{isSelected, select, true {, wybrano} other {}}",
            "dostępna/dostępne(-nych) {optionCount, plural, one {# opcja} other {# opcje(-i)}}.",
            "{optionText}, wybrano",
            "Wyświetlaj sugestie",
            "Sugestie",
        ],
    ),
    (
        "pt-BR",
        &[
            "{isGroupChange, select, true {Grupo inserido {groupTitle}, com {groupCount, plural, one {# opção} other {# opções}}. } other {}}{optionText}{isSelected, select, true {, selecionado} other {}}",
            "{optionCount, plural, one {# opção} other {# opções}} disponível.",
            "{optionText}, selecionado",
            "Mostrar sugestões",
            "Sugestões",
        ],
    ),
    (
        "pt-PT",
        &[
            "{isGroupChange, select, true {Grupo introduzido {groupTitle}, com {groupCount, plural, one {# opção} other {# opções}}. } other {}}{optionText}{isSelected, select, true {, selecionado} other {}}",
            "{optionCount, plural, one {# opção} other {# opções}} disponível.",
            "{optionText}, selecionado",
            "Apresentar sugestões",
            "Sugestões",
        ],
    ),
    (
        "ro-RO",
        &[
            "{isGroupChange, select, true {Grup {groupTitle} introdus, cu {groupCount, plural, one {# opțiune} other {# opțiuni}}. } other {}}{optionText}{isSelected, select, true {, selectat} other {}}",
            "{optionCount, plural, one {# opțiune} other {# opțiuni}} disponibile.",
            "{optionText}, selectat",
            "Afișare sugestii",
            "Sugestii",
        ],
    ),
    (
        "ru-RU",
        &[
            "{isGroupChange, select, true {Введенная группа {groupTitle}, с {groupCount, plural, one {# параметром} other {# параметрами}}. } other {}}{optionText}{isSelected, select, true {, выбранными} other {}}",
            "{optionCount, plural, one {# параметр} other {# параметров}} доступно.",
            "{optionText}, выбрано",
            "Показать предложения",
            "Предложения",
        ],
    ),
    (
        "sk-SK",
        &[
            "{isGroupChange, select, true {Zadaná skupina {groupTitle}, s {groupCount, plural, one {# možnosťou} other {# možnosťami}}. } other {}}{optionText}{isSelected, select, true {, vybraté} other {}}",
            "{optionCount, plural, one {# možnosť} other {# možnosti/-í}} k dispozícii.",
            "{optionText}, vybraté",
            "Zobraziť návrhy",
            "Návrhy",
        ],
    ),
    (
        "sl-SI",
        &[
            "{isGroupChange, select, true {Vnesena skupina {groupTitle}, z {groupCount, plural, one {# opcija} other {# opcije}}. } other {}}{optionText}{isSelected, select, true {, izbrano} other {}}",
            "Na voljo je {optionCount, plural, one {# opcija} other {# opcije}}.",
            "{optionText}, izbrano",
            "Prikaži predloge",
            "Predlogi",
        ],
    ),
    (
        "sr-SP",
        &[
            "{isGroupChange, select, true {Unesena grupa {groupTitle}, s {groupCount, plural, one {# opcijom} other {# optione/a}}. } other {}}{optionText}{isSelected, select, true {, izabranih} other {}}",
            "Dostupno još: {optionCount, plural, one {# opcija} other {# opcije/a}}.",
            "{optionText}, izabrano",
            "Prikaži predloge",
            "Predlozi",
        ],
    ),
    (
        "sv-SE",
        &[
            "{isGroupChange, select, true {Ingick i gruppen {groupTitle} med {groupCount, plural, one {# alternativ} other {# alternativ}}. } other {}}{optionText}{isSelected, select, true {, valda} other {}}",
            "{optionCount, plural, one {# alternativ} other {# alternativ}} tillgängliga.",
            "{optionText}, valda",
            "Visa förslag",
            "Förslag",
        ],
    ),
    (
        "tr-TR",
        &[
            "{isGroupChange, select, true {Girilen grup {groupTitle}, ile {groupCount, plural, one {# seçenek} other {# seçenekler}}. } other {}}{optionText}{isSelected, select, true {, seçildi} other {}}",
            "{optionCount, plural, one {# seçenek} other {# seçenekler}} kullanılabilir.",
            "{optionText}, seçildi",
            "Önerileri göster",
            "Öneriler",
        ],
    ),
    (
        "uk-UA",
        &[
            "{isGroupChange, select, true {Введена група {groupTitle}, з {groupCount, plural, one {# параметр} other {# параметри(-ів)}}. } other {}}{optionText}{isSelected, select, true {, вибрано} other {}}",
            "{optionCount, plural, one {# параметр} other {# параметри(-ів)}} доступно.",
            "{optionText}, вибрано",
            "Показати пропозиції",
            "Пропозиції",
        ],
    ),
    (
        "zh-CN",
        &[
            "{isGroupChange, select, true {进入了 {groupTitle} 组，其中有 {groupCount, plural, one {# 个选项} other {# 个选项}}. } other {}}{optionText}{isSelected, select, true {, 已选择} other {}}",
            "有 {optionCount, plural, one {# 个选项} other {# 个选项}}可用。",
            "{optionText}, 已选择",
            "显示建议",
            "建议",
        ],
    ),
    (
        "zh-TW",
        &[
            "{isGroupChange, select, true {輸入的群組 {groupTitle}, 有 {groupCount, plural, one {# 選項} other {# 選項}}. } other {}}{optionText}{isSelected, select, true {, 已選取} other {}}",
            "{optionCount, plural, one {# 選項} other {# 選項}} 可用。",
            "{optionText}, 已選取",
            "顯示建議",
            "建議",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "focusAnnouncement",
        "countAnnouncement",
        "selectedAnnouncement",
        "buttonLabel",
        "listboxLabel",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of combo boxes, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct ComboBoxStrings(Strings);

impl LocalizedStrings for ComboBoxStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl ComboBoxStrings {
    /// en-US: `{isGroupChange, select, true {Entered group {groupTitle}, with {groupCount, plural, one {# option} other {# options}}. } other {}}{optionText}{isSelected, select, true {, selected} other {}}`
    #[must_use]
    pub fn focus_announcement(&self, args: FocusAnnouncementArgs<'_>) -> String {
        self.0.format(
            0,
            &[
                ("isGroupChange", Arg::Bool(args.is_group_change)),
                ("groupTitle", Arg::Str(args.group_title)),
                ("groupCount", Arg::Count(args.group_count)),
                ("optionText", Arg::Str(args.option_text)),
                ("isSelected", Arg::Bool(args.is_selected)),
            ],
        )
    }
    /// en-US: `{optionCount, plural, one {# option} other {# options}} available.`
    #[must_use]
    pub fn count_announcement(&self, option_count: usize) -> String {
        self.0
            .format(1, &[("optionCount", Arg::Count(option_count))])
    }
    /// en-US: `{optionText}, selected`
    #[must_use]
    pub fn selected_announcement(&self, option_text: &str) -> String {
        self.0.format(2, &[("optionText", Arg::Str(option_text))])
    }
    /// en-US: `Show suggestions`
    #[must_use]
    pub fn button_label(&self) -> String {
        self.0.format(3, &[])
    }
    /// en-US: `Suggestions`
    #[must_use]
    pub fn listbox_label(&self) -> String {
        self.0.format(4, &[])
    }
}

/// The arguments of [`ComboBoxStrings::focus_announcement`].
#[derive(Debug, Clone, Copy)]
pub struct FocusAnnouncementArgs<'a> {
    pub is_group_change: bool,
    pub group_title: &'a str,
    pub group_count: usize,
    pub option_text: &'a str,
    pub is_selected: bool,
}
