// Generated by scripts/port-intl-strings.py from react-stately/intl/datepicker/*.json @ 99e6102368. Do not edit.
//! Localized messages of date validation.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Value must be {minValue} or later.",
    "Value must be {maxValue} or earlier.",
    "Start date must be before end date.",
    "Selected date unavailable.",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "يجب أن تكون القيمة {minValue} أو بعد ذلك.",
            "يجب أن تكون القيمة {maxValue} أو قبل ذلك.",
            "تاريخ البدء يجب أن يكون قبل تاريخ الانتهاء.",
            "البيانات المحددة غير متاحة.",
        ],
    ),
    (
        "bg-BG",
        &[
            "Стойността трябва да е {minValue} или по-късно.",
            "Стойността трябва да е {maxValue} или по-ранна.",
            "Началната дата трябва да е преди крайната.",
            "Избраната дата не е налична.",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Hodnota musí být {minValue} nebo pozdější.",
            "Hodnota musí být {maxValue} nebo dřívější.",
            "Datum zahájení musí předcházet datu ukončení.",
            "Vybrané datum není k dispozici.",
        ],
    ),
    (
        "da-DK",
        &[
            "Værdien skal være {minValue} eller nyere.",
            "Værdien skal være {maxValue} eller tidligere.",
            "Startdatoen skal være før slutdatoen.",
            "Den valgte dato er ikke tilgængelig.",
        ],
    ),
    (
        "de-DE",
        &[
            "Der Wert muss {minValue} oder später sein.",
            "Der Wert muss {maxValue} oder früher sein.",
            "Das Startdatum muss vor dem Enddatum liegen.",
            "Das ausgewählte Datum ist nicht verfügbar.",
        ],
    ),
    (
        "el-GR",
        &[
            "Η τιμή πρέπει να είναι {minValue} ή μεταγενέστερη.",
            "Η τιμή πρέπει να είναι {maxValue} ή παλαιότερη.",
            "Η ημερομηνία έναρξης πρέπει να είναι πριν από την ημερομηνία λήξης.",
            "Η επιλεγμένη ημερομηνία δεν είναι διαθέσιμη.",
        ],
    ),
    (
        "es-ES",
        &[
            "El valor debe ser {minValue} o posterior.",
            "El valor debe ser {maxValue} o anterior.",
            "La fecha de inicio debe ser anterior a la fecha de finalización.",
            "Fecha seleccionada no disponible.",
        ],
    ),
    (
        "et-EE",
        &[
            "Väärtus peab olema {minValue} või hilisem.",
            "Väärtus peab olema {maxValue} või varasem.",
            "Alguskuupäev peab olema enne lõppkuupäeva.",
            "Valitud kuupäev pole saadaval.",
        ],
    ),
    (
        "fi-FI",
        &[
            "Arvon on oltava {minValue} tai sitä myöhäisempi.",
            "Arvon on oltava {maxValue} tai sitä aikaisempi.",
            "Aloituspäivän on oltava ennen lopetuspäivää.",
            "Valittu päivämäärä ei ole käytettävissä.",
        ],
    ),
    (
        "fr-FR",
        &[
            "La valeur doit être {minValue} ou ultérieure.",
            "La valeur doit être {maxValue} ou antérieure.",
            "La date de début doit être antérieure à la date de fin.",
            "La date sélectionnée n’est pas disponible.",
        ],
    ),
    (
        "he-IL",
        &[
            "הערך חייב להיות {minValue} או מאוחר יותר.",
            "הערך חייב להיות {maxValue} או מוקדם יותר.",
            "תאריך ההתחלה חייב להיות לפני תאריך הסיום.",
            "התאריך הנבחר אינו זמין.",
        ],
    ),
    (
        "hr-HR",
        &[
            "Vrijednost mora biti {minValue} ili kasnije.",
            "Vrijednost mora biti {maxValue} ili ranije.",
            "Datum početka mora biti prije datuma završetka.",
            "Odabrani datum nije dostupan.",
        ],
    ),
    (
        "hu-HU",
        &[
            "Az értéknek {minValue} vagy későbbinek kell lennie.",
            "Az értéknek {maxValue} vagy korábbinak kell lennie.",
            "A kezdő dátumnak a befejező dátumnál korábbinak kell lennie.",
            "A kiválasztott dátum nem érhető el.",
        ],
    ),
    (
        "it-IT",
        &[
            "Il valore deve essere {minValue} o successivo.",
            "Il valore deve essere {maxValue} o precedente.",
            "La data di inizio deve essere antecedente alla data di fine.",
            "Data selezionata non disponibile.",
        ],
    ),
    (
        "ja-JP",
        &[
            "値は {minValue} 以上にする必要があります。",
            "値は {maxValue} 以下にする必要があります。",
            "開始日は終了日より前にする必要があります。",
            "選択した日付は使用できません。",
        ],
    ),
    (
        "ko-KR",
        &[
            "값은 {minValue} 이후여야 합니다.",
            "값은 {maxValue} 이전이어야 합니다.",
            "시작일은 종료일 이전이어야 합니다.",
            "선택한 날짜를 사용할 수 없습니다.",
        ],
    ),
    (
        "lt-LT",
        &[
            "Reikšmė turi būti {minValue} arba naujesnė.",
            "Reikšmė turi būti {maxValue} arba ankstesnė.",
            "Pradžios data turi būti ankstesnė nei pabaigos data.",
            "Pasirinkta data nepasiekiama.",
        ],
    ),
    (
        "lv-LV",
        &[
            "Vērtībai ir jābūt {minValue} vai vēlākai.",
            "Vērtībai ir jābūt {maxValue} vai agrākai.",
            "Sākuma datumam ir jābūt pirms beigu datuma.",
            "Atlasītais datums nav pieejams.",
        ],
    ),
    (
        "nb-NO",
        &[
            "Verdien må være {minValue} eller senere.",
            "Verdien må være {maxValue} eller tidligere.",
            "Startdatoen må være før sluttdatoen.",
            "Valgt dato utilgjengelig.",
        ],
    ),
    (
        "nl-NL",
        &[
            "Waarde moet {minValue} of later zijn.",
            "Waarde moet {maxValue} of eerder zijn.",
            "De startdatum moet voor de einddatum liggen.",
            "Geselecteerde datum niet beschikbaar.",
        ],
    ),
    (
        "pl-PL",
        &[
            "Wartość musi mieć wartość {minValue} lub późniejszą.",
            "Wartość musi mieć wartość {maxValue} lub wcześniejszą.",
            "Data rozpoczęcia musi być wcześniejsza niż data zakończenia.",
            "Wybrana data jest niedostępna.",
        ],
    ),
    (
        "pt-BR",
        &[
            "O valor deve ser {minValue} ou posterior.",
            "O valor deve ser {maxValue} ou anterior.",
            "A data inicial deve ser anterior à data final.",
            "Data selecionada indisponível.",
        ],
    ),
    (
        "pt-PT",
        &[
            "O valor tem de ser {minValue} ou posterior.",
            "O valor tem de ser {maxValue} ou anterior.",
            "A data de início deve ser anterior à data de fim.",
            "Data selecionada indisponível.",
        ],
    ),
    (
        "ro-RO",
        &[
            "Valoarea trebuie să fie {minValue} sau ulterioară.",
            "Valoarea trebuie să fie {maxValue} sau anterioară.",
            "Data de început trebuie să fie anterioară datei de sfârșit.",
            "Data selectată nu este disponibilă.",
        ],
    ),
    (
        "ru-RU",
        &[
            "Значение должно быть не раньше {minValue}.",
            "Значение должно быть не позже {maxValue}.",
            "Дата начала должна предшествовать дате окончания.",
            "Выбранная дата недоступна.",
        ],
    ),
    (
        "sk-SK",
        &[
            "Hodnota musí byť {minValue} alebo neskoršia.",
            "Hodnota musí byť {maxValue} alebo skoršia.",
            "Dátum začiatku musí byť skorší ako dátum konca.",
            "Vybratý dátum je nedostupný.",
        ],
    ),
    (
        "sl-SI",
        &[
            "Vrednost mora biti {minValue} ali novejša.",
            "Vrednost mora biti {maxValue} ali starejša.",
            "Začetni datum mora biti pred končnim datumom.",
            "Izbrani datum ni na voljo.",
        ],
    ),
    (
        "sr-SP",
        &[
            "Vrednost mora da bude {minValue} ili novija.",
            "Vrednost mora da bude {maxValue} ili starija.",
            "Datum početka mora biti pre datuma završetka.",
            "Izabrani datum nije dostupan.",
        ],
    ),
    (
        "sv-SE",
        &[
            "Värdet måste vara {minValue} eller senare.",
            "Värdet måste vara {maxValue} eller tidigare.",
            "Startdatumet måste vara före slutdatumet.",
            "Det valda datumet är inte tillgängligt.",
        ],
    ),
    (
        "tr-TR",
        &[
            "Değer, {minValue} veya sonrası olmalıdır.",
            "Değer, {maxValue} veya öncesi olmalıdır.",
            "Başlangıç tarihi bitiş tarihinden önce olmalıdır.",
            "Seçilen tarih kullanılamıyor.",
        ],
    ),
    (
        "uk-UA",
        &[
            "Значення має бути не раніше {minValue}.",
            "Значення має бути не пізніше {maxValue}.",
            "Дата початку має передувати даті завершення.",
            "Вибрана дата недоступна.",
        ],
    ),
    (
        "zh-CN",
        &[
            "值必须是 {minValue} 或更晚日期。",
            "值必须是 {maxValue} 或更早日期。",
            "开始日期必须早于结束日期。",
            "所选日期不可用。",
        ],
    ),
    (
        "zh-TW",
        &[
            "值必須是 {minValue} 或更晚。",
            "值必須是 {maxValue} 或更早。",
            "開始日期必須在結束日期之前。",
            "所選日期無法使用。",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "rangeUnderflow",
        "rangeOverflow",
        "rangeReversed",
        "unavailableDate",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of date validation, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct DateValidationStrings(Strings);

impl LocalizedStrings for DateValidationStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl DateValidationStrings {
    /// en-US: `Value must be {minValue} or later.`
    #[must_use]
    pub fn range_underflow(&self, min_value: &str) -> String {
        self.0.format(0, &[("minValue", Arg::Str(min_value))])
    }
    /// en-US: `Value must be {maxValue} or earlier.`
    #[must_use]
    pub fn range_overflow(&self, max_value: &str) -> String {
        self.0.format(1, &[("maxValue", Arg::Str(max_value))])
    }
    /// en-US: `Start date must be before end date.`
    #[must_use]
    pub fn range_reversed(&self) -> String {
        self.0.format(2, &[])
    }
    /// en-US: `Selected date unavailable.`
    #[must_use]
    pub fn unavailable_date(&self) -> String {
        self.0.format(3, &[])
    }
}
