// Generated by scripts/port-intl-strings.py from react-aria/intl/datepicker/*.json @ 99e6102368. Do not edit.
//! Localized messages of date fields and pickers.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "era",
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "second",
    "AM/PM",
    "Calendar",
    "Start Date",
    "End Date",
    "day of the week",
    "time zone",
    "Selected Date: {date}",
    "Selected Range: {startDate} to {endDate}",
    "Selected Time: {time}",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "العصر",
            "السنة",
            "الشهر",
            "يوم",
            "الساعات",
            "الدقائق",
            "الثواني",
            "ص/م",
            "التقويم",
            "تاريخ البدء",
            "تاريخ الانتهاء",
            "اليوم",
            "التوقيت",
            "تاريخ محدد: {date}",
            "المدى الزمني المحدد: {startDate} إلى {endDate}",
            "الوقت المحدد: {time}",
        ],
    ),
    (
        "bg-BG",
        &[
            "ера",
            "година",
            "месец",
            "ден",
            "час",
            "минута",
            "секунда",
            "пр.об./сл.об.",
            "Календар",
            "Начална дата",
            "Крайна дата",
            "ден от седмицата",
            "часова зона",
            "Избрана дата: {date}",
            "Избран диапазон: {startDate} до {endDate}",
            "Избрано време: {time}",
        ],
    ),
    (
        "cs-CZ",
        &[
            "letopočet",
            "rok",
            "měsíc",
            "den",
            "hodina",
            "minuta",
            "sekunda",
            "část dne",
            "Kalendář",
            "Počáteční datum",
            "Konečné datum",
            "den v týdnu",
            "časové pásmo",
            "Vybrané datum: {date}",
            "Vybrané období: {startDate} až {endDate}",
            "Vybraný čas: {time}",
        ],
    ),
    (
        "da-DK",
        &[
            "æra",
            "år",
            "måned",
            "dag",
            "time",
            "minut",
            "sekund",
            "AM/PM",
            "Kalender",
            "Startdato",
            "Slutdato",
            "ugedag",
            "tidszone",
            "Valgt dato: {date}",
            "Valgt interval: {startDate} til {endDate}",
            "Valgt tidspunkt: {time}",
        ],
    ),
    (
        "de-DE",
        &[
            "Epoche",
            "Jahr",
            "Monat",
            "Tag",
            "Stunde",
            "Minute",
            "Sekunde",
            "Tageshälfte",
            "Kalender",
            "Startdatum",
            "Enddatum",
            "Wochentag",
            "Zeitzone",
            "Ausgewähltes Datum: {date}",
            "Ausgewählter Bereich: {startDate} bis {endDate}",
            "Ausgewählte Zeit: {time}",
        ],
    ),
    (
        "el-GR",
        &[
            "περίοδος",
            "έτος",
            "μήνας",
            "ημέρα",
            "ώρα",
            "λεπτό",
            "δευτερόλεπτο",
            "π.μ./μ.μ.",
            "Ημερολόγιο",
            "Ημερομηνία έναρξης",
            "Ημερομηνία λήξης",
            "καθημερινή",
            "ζώνη ώρας",
            "Επιλεγμένη ημερομηνία: {date}",
            "Επιλεγμένο εύρος: {startDate} έως {endDate}",
            "Επιλεγμένη ώρα: {time}",
        ],
    ),
    (
        "es-ES",
        &[
            "era",
            "año",
            "mes",
            "día",
            "hora",
            "minuto",
            "segundo",
            "a.\u{a0}m./p.\u{a0}m.",
            "Calendario",
            "Fecha de inicio",
            "Fecha final",
            "día de la semana",
            "zona horaria",
            "Fecha seleccionada: {date}",
            "Rango seleccionado: {startDate} a {endDate}",
            "Hora seleccionada: {time}",
        ],
    ),
    (
        "et-EE",
        &[
            "ajastu",
            "aasta",
            "kuu",
            "päev",
            "tund",
            "minut",
            "sekund",
            "enne/pärast lõunat",
            "Kalender",
            "Alguskuupäev",
            "Lõppkuupäev",
            "nädalapäev",
            "ajavöönd",
            "Valitud kuupäev: {date}",
            "Valitud vahemik: {startDate} kuni {endDate}",
            "Valitud aeg: {time}",
        ],
    ),
    (
        "fi-FI",
        &[
            "aikakausi",
            "vuosi",
            "kuukausi",
            "päivä",
            "tunti",
            "minuutti",
            "sekunti",
            "vuorokaudenaika",
            "Kalenteri",
            "Alkamispäivä",
            "Päättymispäivä",
            "viikonpäivä",
            "aikavyöhyke",
            "Valittu päivämäärä: {date}",
            "Valittu aikaväli: {startDate} – {endDate}",
            "Valittu aika: {time}",
        ],
    ),
    (
        "fr-FR",
        &[
            "ère",
            "année",
            "mois",
            "jour",
            "heure",
            "minute",
            "seconde",
            "cadran",
            "Calendrier",
            "Date de début",
            "Date de fin",
            "jour de la semaine",
            "fuseau horaire",
            "Date sélectionnée\u{a0}: {date}",
            "Plage sélectionnée\u{a0}: {startDate} au {endDate}",
            "Heure choisie\u{a0}: {time}",
        ],
    ),
    (
        "he-IL",
        &[
            "תקופה",
            "שנה",
            "חודש",
            "יום",
            "שעה",
            "דקה",
            "שנייה",
            "לפנה״צ/אחה״צ",
            "לוח שנה",
            "תאריך התחלה",
            "תאריך סיום",
            "יום בשבוע",
            "אזור זמן",
            "תאריך נבחר: {date}",
            "טווח נבחר: {startDate} עד {endDate}",
            "זמן נבחר: {time}",
        ],
    ),
    (
        "hr-HR",
        &[
            "era",
            "godina",
            "mjesec",
            "dan",
            "sat",
            "minuta",
            "sekunda",
            "AM/PM",
            "Kalendar",
            "Datum početka",
            "Datum završetka",
            "dan u tjednu",
            "vremenska zona",
            "Odabrani datum: {date}",
            "Odabrani raspon: {startDate} do {endDate}",
            "Odabrano vrijeme: {time}",
        ],
    ),
    (
        "hu-HU",
        &[
            "éra",
            "év",
            "hónap",
            "nap",
            "óra",
            "perc",
            "másodperc",
            "napszak",
            "Naptár",
            "Kezdő dátum",
            "Befejező dátum",
            "hét napja",
            "időzóna",
            "Kijelölt dátum: {date}",
            "Kijelölt tartomány: {startDate}–{endDate}",
            "Kijelölt idő: {time}",
        ],
    ),
    (
        "it-IT",
        &[
            "era",
            "anno",
            "mese",
            "giorno",
            "ora",
            "minuto",
            "secondo",
            "AM/PM",
            "Calendario",
            "Data iniziale",
            "Data finale",
            "giorno della settimana",
            "fuso orario",
            "Data selezionata: {date}",
            "Intervallo selezionato: da {startDate} a {endDate}",
            "Ora selezionata: {time}",
        ],
    ),
    (
        "ja-JP",
        &[
            "時代",
            "年",
            "月",
            "日",
            "時",
            "分",
            "秒",
            "午前/午後",
            "カレンダー",
            "開始日",
            "終了日",
            "曜日",
            "タイムゾーン",
            "選択した日付 : {date}",
            "選択範囲 : {startDate} から {endDate}",
            "選択した時間 : {time}",
        ],
    ),
    (
        "ko-KR",
        &[
            "연호",
            "년",
            "월",
            "일",
            "시",
            "분",
            "초",
            "오전/오후",
            "달력",
            "시작일",
            "종료일",
            "요일",
            "시간대",
            "선택 일자: {date}",
            "선택 범위: {startDate} ~ {endDate}",
            "선택 시간: {time}",
        ],
    ),
    (
        "lt-LT",
        &[
            "era",
            "metai",
            "mėnuo",
            "diena",
            "valanda",
            "minutė",
            "sekundė",
            "iki pietų / po pietų",
            "Kalendorius",
            "Pradžios data",
            "Pabaigos data",
            "savaitės diena",
            "laiko juosta",
            "Pasirinkta data: {date}",
            "Pasirinktas intervalas: nuo {startDate} iki {endDate}",
            "Pasirinktas laikas: {time}",
        ],
    ),
    (
        "lv-LV",
        &[
            "ēra",
            "gads",
            "mēnesis",
            "diena",
            "stundas",
            "minūtes",
            "sekundes",
            "priekšpusdienā/pēcpusdienā",
            "Kalendārs",
            "Sākuma datums",
            "Beigu datums",
            "nedēļas diena",
            "laika josla",
            "Atlasītais datums: {date}",
            "Atlasītais diapazons: no {startDate} līdz {endDate}",
            "Atlasītais laiks: {time}",
        ],
    ),
    (
        "nb-NO",
        &[
            "tidsalder",
            "år",
            "måned",
            "dag",
            "time",
            "minutt",
            "sekund",
            "a.m./p.m.",
            "Kalender",
            "Startdato",
            "Sluttdato",
            "ukedag",
            "tidssone",
            "Valgt dato: {date}",
            "Valgt område: {startDate} til {endDate}",
            "Valgt tid: {time}",
        ],
    ),
    (
        "nl-NL",
        &[
            "tijdperk",
            "jaar",
            "maand",
            "dag",
            "uur",
            "minuut",
            "seconde",
            "a.m./p.m.",
            "Kalender",
            "Startdatum",
            "Einddatum",
            "dag van de week",
            "tijdzone",
            "Geselecteerde datum: {date}",
            "Geselecteerd bereik: {startDate} tot {endDate}",
            "Geselecteerde tijd: {time}",
        ],
    ),
    (
        "pl-PL",
        &[
            "era",
            "rok",
            "miesiąc",
            "dzień",
            "godzina",
            "minuta",
            "sekunda",
            "rano / po południu / wieczorem",
            "Kalendarz",
            "Data początkowa",
            "Data końcowa",
            "dzień tygodnia",
            "strefa czasowa",
            "Wybrana data: {date}",
            "Wybrany zakres: {startDate} do {endDate}",
            "Wybrany czas: {time}",
        ],
    ),
    (
        "pt-BR",
        &[
            "era",
            "ano",
            "mês",
            "dia",
            "hora",
            "minuto",
            "segundo",
            "AM/PM",
            "Calendário",
            "Data inicial",
            "Data final",
            "dia da semana",
            "fuso horário",
            "Data selecionada: {date}",
            "Intervalo selecionado: {startDate} a {endDate}",
            "Hora selecionada: {time}",
        ],
    ),
    (
        "pt-PT",
        &[
            "era",
            "ano",
            "mês",
            "dia",
            "hora",
            "minuto",
            "segundo",
            "am/pm",
            "Calendário",
            "Data de Início",
            "Data de Término",
            "dia da semana",
            "fuso horário",
            "Data selecionada: {date}",
            "Intervalo selecionado: {startDate} a {endDate}",
            "Hora selecionada: {time}",
        ],
    ),
    (
        "ro-RO",
        &[
            "eră",
            "an",
            "lună",
            "zi",
            "oră",
            "minut",
            "secundă",
            "a.m/p.m.",
            "Calendar",
            "Dată început",
            "Dată final",
            "ziua din săptămână",
            "fus orar",
            "Dată selectată: {date}",
            "Interval selectat: de la {startDate} până la {endDate}",
            "Ora selectată: {time}",
        ],
    ),
    (
        "ru-RU",
        &[
            "эра",
            "год",
            "месяц",
            "день",
            "час",
            "минута",
            "секунда",
            "AM/PM",
            "Календарь",
            "Дата начала",
            "Дата окончания",
            "день недели",
            "часовой пояс",
            "Выбранная дата: {date}",
            "Выбранный диапазон: с {startDate} по {endDate}",
            "Выбранное время: {time}",
        ],
    ),
    (
        "sk-SK",
        &[
            "letopočet",
            "rok",
            "mesiac",
            "deň",
            "hodina",
            "minúta",
            "sekunda",
            "AM/PM",
            "Kalendár",
            "Dátum začatia",
            "Dátum ukončenia",
            "deň týždňa",
            "časové pásmo",
            "Vybratý dátum: {date}",
            "Vybratý rozsah: od {startDate} do {endDate}",
            "Vybratý čas: {time}",
        ],
    ),
    (
        "sl-SI",
        &[
            "doba",
            "leto",
            "mesec",
            "dan",
            "ura",
            "minuta",
            "sekunda",
            "dop/pop",
            "Koledar",
            "Datum začetka",
            "Datum konca",
            "dan v tednu",
            "časovni pas",
            "Izbrani datum: {date}",
            "Izbrano območje: {startDate} do {endDate}",
            "Izbrani čas: {time}",
        ],
    ),
    (
        "sr-SP",
        &[
            "ера",
            "година",
            "месец",
            "дан",
            "сат",
            "минут",
            "секунд",
            "пре подне/по подне",
            "Kalendar",
            "Datum početka",
            "Datum završetka",
            "дан у недељи",
            "временска зона",
            "Izabrani datum: {date}",
            "Izabrani opseg: od {startDate} do {endDate}",
            "Izabrano vreme: {time}",
        ],
    ),
    (
        "sv-SE",
        &[
            "era",
            "år",
            "månad",
            "dag",
            "timme",
            "minut",
            "sekund",
            "fm/em",
            "Kalender",
            "Startdatum",
            "Slutdatum",
            "veckodag",
            "tidszon",
            "Valt datum: {date}",
            "Valt intervall: {startDate} till {endDate}",
            "Vald tid: {time}",
        ],
    ),
    (
        "tr-TR",
        &[
            "çağ",
            "yıl",
            "ay",
            "gün",
            "saat",
            "dakika",
            "saniye",
            "ÖÖ/ÖS",
            "Takvim",
            "Başlangıç Tarihi",
            "Bitiş Tarihi",
            "haftanın günü",
            "saat dilimi",
            "Seçilen Tarih: {date}",
            "Seçilen Aralık: {startDate} - {endDate}",
            "Seçilen Zaman: {time}",
        ],
    ),
    (
        "uk-UA",
        &[
            "ера",
            "рік",
            "місяць",
            "день",
            "година",
            "хвилина",
            "секунда",
            "дп/пп",
            "Календар",
            "Дата початку",
            "Дата завершення",
            "день тижня",
            "часовий пояс",
            "Вибрана дата: {date}",
            "Вибраний діапазон: {startDate} — {endDate}",
            "Вибраний час: {time}",
        ],
    ),
    (
        "zh-CN",
        &[
            "纪元",
            "年",
            "月",
            "日",
            "小时",
            "分钟",
            "秒",
            "上午/下午",
            "日历",
            "开始日期",
            "结束日期",
            "工作日",
            "时区",
            "选定的日期：{date}",
            "选定的范围：{startDate} 至 {endDate}",
            "选定的时间：{time}",
        ],
    ),
    (
        "zh-TW",
        &[
            "纪元",
            "年",
            "月",
            "日",
            "小时",
            "分钟",
            "秒",
            "上午/下午",
            "日曆",
            "開始日期",
            "結束日期",
            "工作日",
            "时区",
            "選定的日期：{date}",
            "選定的範圍：{startDate} 至 {endDate}",
            "選定的時間：{time}",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "era",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "second",
        "dayPeriod",
        "calendar",
        "startDate",
        "endDate",
        "weekday",
        "timeZoneName",
        "selectedDateDescription",
        "selectedRangeDescription",
        "selectedTimeDescription",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of date fields and pickers, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct DatePickerStrings(Strings);

impl LocalizedStrings for DatePickerStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl DatePickerStrings {
    /// en-US: `era`
    #[must_use]
    pub fn era(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `year`
    #[must_use]
    pub fn year(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `month`
    #[must_use]
    pub fn month(&self) -> String {
        self.0.format(2, &[])
    }
    /// en-US: `day`
    #[must_use]
    pub fn day(&self) -> String {
        self.0.format(3, &[])
    }
    /// en-US: `hour`
    #[must_use]
    pub fn hour(&self) -> String {
        self.0.format(4, &[])
    }
    /// en-US: `minute`
    #[must_use]
    pub fn minute(&self) -> String {
        self.0.format(5, &[])
    }
    /// en-US: `second`
    #[must_use]
    pub fn second(&self) -> String {
        self.0.format(6, &[])
    }
    /// en-US: `AM/PM`
    #[must_use]
    pub fn day_period(&self) -> String {
        self.0.format(7, &[])
    }
    /// en-US: `Calendar`
    #[must_use]
    pub fn calendar(&self) -> String {
        self.0.format(8, &[])
    }
    /// en-US: `Start Date`
    #[must_use]
    pub fn start_date(&self) -> String {
        self.0.format(9, &[])
    }
    /// en-US: `End Date`
    #[must_use]
    pub fn end_date(&self) -> String {
        self.0.format(10, &[])
    }
    /// en-US: `day of the week`
    #[must_use]
    pub fn weekday(&self) -> String {
        self.0.format(11, &[])
    }
    /// en-US: `time zone`
    #[must_use]
    pub fn time_zone_name(&self) -> String {
        self.0.format(12, &[])
    }
    /// en-US: `Selected Date: {date}`
    #[must_use]
    pub fn selected_date_description(&self, date: &str) -> String {
        self.0.format(13, &[("date", Arg::Str(date))])
    }
    /// en-US: `Selected Range: {startDate} to {endDate}`
    #[must_use]
    pub fn selected_range_description(&self, args: SelectedRangeDescriptionArgs<'_>) -> String {
        self.0.format(
            14,
            &[
                ("startDate", Arg::Str(args.start_date)),
                ("endDate", Arg::Str(args.end_date)),
            ],
        )
    }
    /// en-US: `Selected Time: {time}`
    #[must_use]
    pub fn selected_time_description(&self, time: &str) -> String {
        self.0.format(15, &[("time", Arg::Str(time))])
    }
}

/// The arguments of [`DatePickerStrings::selected_range_description`].
#[derive(Debug, Clone, Copy)]
pub struct SelectedRangeDescriptionArgs<'a> {
    pub start_date: &'a str,
    pub end_date: &'a str,
}
