// Generated by scripts/port-intl-strings.py from react-aria/intl/grid/*.json @ 99e6102368. Do not edit.
//! Localized messages of grids.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "{item} not selected.",
    "Select",
    "{count, plural, =0 {No items selected} one {# item selected} other {# items selected}}.",
    "All items selected.",
    "{item} selected.",
    "Long press to enter selection mode.",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "{item} غير المحدد",
            "تحديد",
            "{count, plural, =0 {لم يتم تحديد عناصر} one {# عنصر محدد} other {# عنصر محدد}}.",
            "جميع العناصر المحددة.",
            "{item} المحدد",
            "اضغط مطولًا للدخول إلى وضع التحديد.",
        ],
    ),
    (
        "bg-BG",
        &[
            "{item} не е избран.",
            "Изберете",
            "{count, plural, =0 {Няма избрани елементи} one {# избран елемент} other {# избрани елементи}}.",
            "Всички елементи са избрани.",
            "{item} избран.",
            "Натиснете и задръжте за да влезете в избирателен режим.",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Položka {item} není vybrána.",
            "Vybrat",
            "{count, plural, =0 {Nevybrány žádné položky} one {Vybrána # položka} other {Vybráno # položek}}.",
            "Vybrány všechny položky.",
            "Vybrána položka {item}.",
            "Dlouhým stisknutím přejdete do režimu výběru.",
        ],
    ),
    (
        "da-DK",
        &[
            "{item} ikke valgt.",
            "Vælg",
            "{count, plural, =0 {Ingen elementer valgt} one {# element valgt} other {# elementer valgt}}.",
            "Alle elementer valgt.",
            "{item} valgt.",
            "Lav et langt tryk for at aktivere valgtilstand.",
        ],
    ),
    (
        "de-DE",
        &[
            "{item} nicht ausgewählt.",
            "Auswählen",
            "{count, plural, =0 {Keine Elemente ausgewählt} one {# Element ausgewählt} other {# Elemente ausgewählt}}.",
            "Alle Elemente ausgewählt.",
            "{item} ausgewählt.",
            "Gedrückt halten, um Auswahlmodus zu öffnen.",
        ],
    ),
    (
        "el-GR",
        &[
            "Δεν επιλέχθηκε το στοιχείο {item}.",
            "Επιλογή",
            "{count, plural, =0 {Δεν επιλέχθηκαν στοιχεία} one {Επιλέχθηκε # στοιχείο} other {Επιλέχθηκαν # στοιχεία}}.",
            "Επιλέχθηκαν όλα τα στοιχεία.",
            "Επιλέχθηκε το στοιχείο {item}.",
            "Πατήστε παρατεταμένα για να μπείτε σε λειτουργία επιλογής.",
        ],
    ),
    (
        "es-ES",
        &[
            "{item} no seleccionado.",
            "Seleccionar",
            "{count, plural, =0 {Ningún elemento seleccionado} one {# elemento seleccionado} other {# elementos seleccionados}}.",
            "Todos los elementos seleccionados.",
            "{item} seleccionado.",
            "Mantenga pulsado para abrir el modo de selección.",
        ],
    ),
    (
        "et-EE",
        &[
            "{item} pole valitud.",
            "Vali",
            "{count, plural, =0 {Üksusi pole valitud} one {# üksus valitud} other {# üksust valitud}}.",
            "Kõik üksused valitud.",
            "{item} valitud.",
            "Valikurežiimi sisenemiseks vajutage pikalt.",
        ],
    ),
    (
        "fi-FI",
        &[
            "Kohdetta {item} ei valittu.",
            "Valitse",
            "{count, plural, =0 {Ei yhtään kohdetta valittu} one {# kohde valittu} other {# kohdetta valittu}}.",
            "Kaikki kohteet valittu.",
            "{item} valittu.",
            "Siirry valintatilaan painamalla pitkään.",
        ],
    ),
    (
        "fr-FR",
        &[
            "{item} non sélectionné.",
            "Sélectionner",
            "{count, plural, =0 {Aucun élément sélectionné} one {# élément sélectionné} other {# éléments sélectionnés}}.",
            "Tous les éléments sélectionnés.",
            "{item} sélectionné.",
            "Appuyez de manière prolongée pour passer en mode de sélection.",
        ],
    ),
    (
        "he-IL",
        &[
            "{item} לא נבחר.",
            "בחר",
            "{count, plural, =0 {לא נבחרו פריטים} one {פריט # נבחר} other {# פריטים נבחרו}}.",
            "כל הפריטים נבחרו.",
            "{item} נבחר.",
            "הקשה ארוכה לכניסה למצב בחירה.",
        ],
    ),
    (
        "hr-HR",
        &[
            "Stavka {item} nije odabrana.",
            "Odaberite",
            "{count, plural, =0 {Nije odabrana nijedna stavka} one {Odabrana je # stavka} other {Odabrano je # stavki}}.",
            "Odabrane su sve stavke.",
            "Stavka {item} je odabrana.",
            "Dugo pritisnite za ulazak u način odabira.",
        ],
    ),
    (
        "hu-HU",
        &[
            "{item} nincs kijelölve.",
            "Kijelölés",
            "{count, plural, =0 {Egy elem sincs kijelölve} one {# elem kijelölve} other {# elem kijelölve}}.",
            "Az összes elem kijelölve.",
            "{item} kijelölve.",
            "Nyomja hosszan a kijelöléshez.",
        ],
    ),
    (
        "it-IT",
        &[
            "{item} non selezionato.",
            "Seleziona",
            "{count, plural, =0 {Nessun elemento selezionato} one {# elemento selezionato} other {# elementi selezionati}}.",
            "Tutti gli elementi selezionati.",
            "{item} selezionato.",
            "Premi a lungo per passare alla modalità di selezione.",
        ],
    ),
    (
        "ja-JP",
        &[
            "{item} が選択されていません。",
            "選択",
            "{count, plural, =0 {項目が選択されていません} one {# 項目を選択しました} other {# 項目を選択しました}}。",
            "すべての項目を選択しました。",
            "{item} を選択しました。",
            "長押しして選択モードを開きます。",
        ],
    ),
    (
        "ko-KR",
        &[
            "{item}이(가) 선택되지 않았습니다.",
            "선택",
            "{count, plural, =0 {선택된 항목이 없습니다} one {#개 항목이 선택되었습니다} other {#개 항목이 선택되었습니다}}.",
            "모든 항목이 선택되었습니다.",
            "{item}이(가) 선택되었습니다.",
            "선택 모드로 들어가려면 길게 누르십시오.",
        ],
    ),
    (
        "lt-LT",
        &[
            "{item} nepasirinkta.",
            "Pasirinkti",
            "{count, plural, =0 {Nepasirinktas nė vienas elementas} one {Pasirinktas # elementas} other {Pasirinkta elementų: #}}.",
            "Pasirinkti visi elementai.",
            "Pasirinkta: {item}.",
            "Norėdami įjungti pasirinkimo režimą, paspauskite ir palaikykite.",
        ],
    ),
    (
        "lv-LV",
        &[
            "Vienums {item} nav atlasīts.",
            "Atlasīt",
            "{count, plural, =0 {Nav atlasīts neviens vienums} one {Atlasīto vienumu skaits: #} other {Atlasīto vienumu skaits: #}}.",
            "Atlasīti visi vienumi.",
            "Atlasīts vienums {item}.",
            "Ilgi turiet nospiestu. lai ieslēgtu atlases režīmu.",
        ],
    ),
    (
        "nb-NO",
        &[
            "{item} er ikke valgt.",
            "Velg",
            "{count, plural, =0 {Ingen elementer er valgt} one {# element er valgt} other {# elementer er valgt}}.",
            "Alle elementer er valgt.",
            "{item} er valgt.",
            "Bruk et langt trykk for å gå inn i valgmodus.",
        ],
    ),
    (
        "nl-NL",
        &[
            "{item} niet geselecteerd.",
            "Selecteren",
            "{count, plural, =0 {Geen items geselecteerd} one {# item geselecteerd} other {# items geselecteerd}}.",
            "Alle items geselecteerd.",
            "{item} geselecteerd.",
            "Druk lang om de selectiemodus te openen.",
        ],
    ),
    (
        "pl-PL",
        &[
            "Nie zaznaczono {item}.",
            "Zaznacz",
            "{count, plural, =0 {Nie zaznaczono żadnych elementów} one {# zaznaczony element} other {# zaznaczonych elementów}}.",
            "Wszystkie zaznaczone elementy.",
            "Zaznaczono {item}.",
            "Naciśnij i przytrzymaj, aby wejść do trybu wyboru.",
        ],
    ),
    (
        "pt-BR",
        &[
            "{item} não selecionado.",
            "Selecionar",
            "{count, plural, =0 {Nenhum item selecionado} one {# item selecionado} other {# itens selecionados}}.",
            "Todos os itens selecionados.",
            "{item} selecionado.",
            "Mantenha pressionado para entrar no modo de seleção.",
        ],
    ),
    (
        "pt-PT",
        &[
            "{item} não selecionado.",
            "Selecionar",
            "{count, plural, =0 {Nenhum item selecionado} one {# item selecionado} other {# itens selecionados}}.",
            "Todos os itens selecionados.",
            "{item} selecionado.",
            "Prima continuamente para entrar no modo de seleção.",
        ],
    ),
    (
        "ro-RO",
        &[
            "{item} neselectat.",
            "Selectare",
            "{count, plural, =0 {Niciun element selectat} one {# element selectat} other {# elemente selectate}}.",
            "Toate elementele selectate.",
            "{item} selectat.",
            "Apăsați lung pentru a intra în modul de selectare.",
        ],
    ),
    (
        "ru-RU",
        &[
            "{item} не выбрано.",
            "Выбрать",
            "{count, plural, =0 {Нет выбранных элементов} one {# элемент выбран} other {# элементов выбрано}}.",
            "Выбраны все элементы.",
            "{item} выбрано.",
            "Нажмите и удерживайте для входа в режим выбора.",
        ],
    ),
    (
        "sk-SK",
        &[
            "Nevybraté položky: {item}.",
            "Vybrať",
            "{count, plural, =0 {Žiadne vybraté položky} one {# vybratá položka} other {Počet vybratých položiek:#}}.",
            "Všetky vybraté položky.",
            "Vybraté položky: {item}.",
            "Dlhším stlačením prejdite do režimu výberu.",
        ],
    ),
    (
        "sl-SI",
        &[
            "Element {item} ni izbran.",
            "Izberite",
            "{count, plural, =0 {Noben element ni izbran} one {# element je izbran} other {# elementov je izbranih}}.",
            "Vsi elementi so izbrani.",
            "Element {item} je izbran.",
            "Za izbirni način pritisnite in dlje časa držite.",
        ],
    ),
    (
        "sr-SP",
        &[
            "{item} nije izabrano.",
            "Izaberite",
            "{count, plural, =0 {Nije izabrana nijedna stavka} one {Izabrana je # stavka} other {Izabrano je # stavki}}.",
            "Izabrane su sve stavke.",
            "{item} je izabrano.",
            "Dugo pritisnite za ulazak u režim biranja.",
        ],
    ),
    (
        "sv-SE",
        &[
            "{item} ej markerat.",
            "Markera",
            "{count, plural, =0 {Inga markerade objekt} one {# markerat objekt} other {# markerade objekt}}.",
            "Alla markerade objekt.",
            "{item} markerat.",
            "Tryck länge när du vill öppna väljarläge.",
        ],
    ),
    (
        "tr-TR",
        &[
            "{item} seçilmedi.",
            "Seç",
            "{count, plural, =0 {Hiçbir öge seçilmedi} one {# öge seçildi} other {# öge seçildi}}.",
            "Tüm ögeler seçildi.",
            "{item} seçildi.",
            "Seçim moduna girmek için uzun basın.",
        ],
    ),
    (
        "uk-UA",
        &[
            "{item} не вибрано.",
            "Вибрати",
            "{count, plural, =0 {Жодних елементів не вибрано} one {# елемент вибрано} other {Вибрано елементів: #}}.",
            "Усі елементи вибрано.",
            "{item} вибрано.",
            "Виконайте довге натиснення, щоб перейти в режим вибору.",
        ],
    ),
    (
        "zh-CN",
        &[
            "未选择 {item}。",
            "选择",
            "{count, plural, =0 {未选择项目} one {已选择 # 个项目} other {已选择 # 个项目}}。",
            "已选择所有项目。",
            "已选择 {item}。",
            "长按以进入选择模式。",
        ],
    ),
    (
        "zh-TW",
        &[
            "未選取「{item}」。",
            "選取",
            "{count, plural, =0 {未選取任何項目} one {已選取 # 個項目} other {已選取 # 個項目}}。",
            "已選取所有項目。",
            "已選取「{item}」。",
            "長按以進入選擇模式。",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "deselectedItem",
        "select",
        "selectedCount",
        "selectedAll",
        "selectedItem",
        "longPressToSelect",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of grids, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct GridStrings(Strings);

impl LocalizedStrings for GridStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl GridStrings {
    /// en-US: `{item} not selected.`
    #[must_use]
    pub fn deselected_item(&self, item: &str) -> String {
        self.0.format(0, &[("item", Arg::Str(item))])
    }
    /// en-US: `Select`
    #[must_use]
    pub fn select(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `{count, plural, =0 {No items selected} one {# item selected} other {# items selected}}.`
    #[must_use]
    pub fn selected_count(&self, count: usize) -> String {
        self.0.format(2, &[("count", Arg::Count(count))])
    }
    /// en-US: `All items selected.`
    #[must_use]
    pub fn selected_all(&self) -> String {
        self.0.format(3, &[])
    }
    /// en-US: `{item} selected.`
    #[must_use]
    pub fn selected_item(&self, item: &str) -> String {
        self.0.format(4, &[("item", Arg::Str(item))])
    }
    /// en-US: `Long press to enter selection mode.`
    #[must_use]
    pub fn long_press_to_select(&self) -> String {
        self.0.format(5, &[])
    }
}
