// Generated by scripts/port-intl-strings.py @ 99e6102368. Do not edit.

mod atoms;
mod breadcrumbs;
mod calendar;
mod color;
mod color_names;
mod combobox;
mod date_validation;
mod datepicker;
mod dnd;
mod grid;
mod menu;
mod numberfield;
mod overlays;
mod searchfield;
mod spinbutton;
mod table;
mod tag;
mod toast;
mod tree;

pub use atoms::AtomStrings;
pub use breadcrumbs::BreadcrumbsStrings;
pub use calendar::{CalendarStrings, DateRangeArgs};
pub use color::{ColorInputLabelArgs, ColorNameAndValueArgs, ColorStrings};
pub use color_names::{ColorNameArgs, ColorNameStrings, TransparentColorNameArgs};
pub use combobox::{ComboBoxStrings, FocusAnnouncementArgs};
pub use date_validation::DateValidationStrings;
pub use datepicker::{DatePickerStrings, SelectedRangeDescriptionArgs};
pub use dnd::{DndStrings, InsertBetweenArgs};
pub use grid::GridStrings;
pub use menu::MenuStrings;
pub use numberfield::NumberFieldStrings;
pub use overlays::OverlayStrings;
pub use searchfield::SearchFieldStrings;
pub use spinbutton::SpinButtonStrings;
pub use table::TableStrings;
pub use tag::TagStrings;
pub use toast::ToastStrings;
pub use tree::TreeStrings;

/// Every bundle, for the tests.
#[cfg(test)]
pub(super) fn all() -> Vec<&'static super::Bundle> {
    use super::LocalizedStrings;
    vec![
        BreadcrumbsStrings::bundle(),
        CalendarStrings::bundle(),
        ColorStrings::bundle(),
        ColorNameStrings::bundle(),
        ComboBoxStrings::bundle(),
        DatePickerStrings::bundle(),
        DateValidationStrings::bundle(),
        DndStrings::bundle(),
        GridStrings::bundle(),
        MenuStrings::bundle(),
        NumberFieldStrings::bundle(),
        OverlayStrings::bundle(),
        SearchFieldStrings::bundle(),
        SpinButtonStrings::bundle(),
        TableStrings::bundle(),
        TagStrings::bundle(),
        ToastStrings::bundle(),
        TreeStrings::bundle(),
        AtomStrings::bundle(),
    ]
}
