// Generated by scripts/port-intl-strings.py from react-aria/intl/numberfield/*.json @ 99e6102368. Do not edit.
//! Localized messages of number fields.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Decrease {fieldLabel}",
    "Increase {fieldLabel}",
    "Number field",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &["خفض {fieldLabel}", "زيادة {fieldLabel}", "حقل رقمي"],
    ),
    (
        "bg-BG",
        &[
            "Намаляване {fieldLabel}",
            "Усилване {fieldLabel}",
            "Номер на полето",
        ],
    ),
    (
        "cs-CZ",
        &["Snížit {fieldLabel}", "Zvýšit {fieldLabel}", "Číselné pole"],
    ),
    (
        "da-DK",
        &["Reducer {fieldLabel}", "Øg {fieldLabel}", "Talfelt"],
    ),
    (
        "de-DE",
        &[
            "{fieldLabel} verringern",
            "{fieldLabel} erhöhen",
            "Nummernfeld",
        ],
    ),
    (
        "el-GR",
        &[
            "Μείωση {fieldLabel}",
            "Αύξηση {fieldLabel}",
            "Πεδίο αριθμού",
        ],
    ),
    (
        "es-ES",
        &[
            "Reducir {fieldLabel}",
            "Aumentar {fieldLabel}",
            "Campo de número",
        ],
    ),
    (
        "et-EE",
        &[
            "Vähenda {fieldLabel}",
            "Suurenda {fieldLabel}",
            "Numbri väli",
        ],
    ),
    (
        "fi-FI",
        &["Vähennä {fieldLabel}", "Lisää {fieldLabel}", "Numerokenttä"],
    ),
    (
        "fr-FR",
        &[
            "Diminuer {fieldLabel}",
            "Augmenter {fieldLabel}",
            "Champ de nombre",
        ],
    ),
    (
        "he-IL",
        &["הקטן {fieldLabel}", "הגדל {fieldLabel}", "שדה מספר"],
    ),
    (
        "hr-HR",
        &["Smanji {fieldLabel}", "Povećaj {fieldLabel}", "Polje broja"],
    ),
    (
        "hu-HU",
        &[
            "{fieldLabel} csökkentése",
            "{fieldLabel} növelése",
            "Számmező",
        ],
    ),
    (
        "it-IT",
        &[
            "Riduci {fieldLabel}",
            "Aumenta {fieldLabel}",
            "Campo numero",
        ],
    ),
    (
        "ja-JP",
        &["{fieldLabel}を縮小", "{fieldLabel}を拡大", "数値フィールド"],
    ),
    (
        "ko-KR",
        &["{fieldLabel} 감소", "{fieldLabel} 증가", "번호 필드"],
    ),
    (
        "lt-LT",
        &[
            "Sumažinti {fieldLabel}",
            "Padidinti {fieldLabel}",
            "Numerio laukas",
        ],
    ),
    (
        "lv-LV",
        &[
            "Samazināšana {fieldLabel}",
            "Palielināšana {fieldLabel}",
            "Skaitļu lauks",
        ],
    ),
    (
        "nb-NO",
        &["Reduser {fieldLabel}", "Øk {fieldLabel}", "Tallfelt"],
    ),
    (
        "nl-NL",
        &[
            "{fieldLabel} verlagen",
            "{fieldLabel} verhogen",
            "Getalveld",
        ],
    ),
    (
        "pl-PL",
        &[
            "Zmniejsz {fieldLabel}",
            "Zwiększ {fieldLabel}",
            "Pole numeru",
        ],
    ),
    (
        "pt-BR",
        &[
            "Diminuir {fieldLabel}",
            "Aumentar {fieldLabel}",
            "Campo de número",
        ],
    ),
    (
        "pt-PT",
        &[
            "Diminuir {fieldLabel}",
            "Aumentar {fieldLabel}",
            "Campo numérico",
        ],
    ),
    (
        "ro-RO",
        &[
            "Scădere {fieldLabel}",
            "Creștere {fieldLabel}",
            "Câmp numeric",
        ],
    ),
    (
        "ru-RU",
        &[
            "Уменьшение {fieldLabel}",
            "Увеличение {fieldLabel}",
            "Числовое поле",
        ],
    ),
    (
        "sk-SK",
        &["Znížiť {fieldLabel}", "Zvýšiť {fieldLabel}", "Číselné pole"],
    ),
    (
        "sl-SI",
        &[
            "Upadati {fieldLabel}",
            "Povečajte {fieldLabel}",
            "Številčno polje",
        ],
    ),
    (
        "sr-SP",
        &["Smanji {fieldLabel}", "Povećaj {fieldLabel}", "Polje broja"],
    ),
    (
        "sv-SE",
        &["Minska {fieldLabel}", "Öka {fieldLabel}", "Nummerfält"],
    ),
    (
        "tr-TR",
        &["{fieldLabel} azalt", "{fieldLabel} arttır", "Sayı alanı"],
    ),
    (
        "uk-UA",
        &[
            "Зменшити {fieldLabel}",
            "Збільшити {fieldLabel}",
            "Поле номера",
        ],
    ),
    (
        "zh-CN",
        &["降低 {fieldLabel}", "提高 {fieldLabel}", "数字字段"],
    ),
    (
        "zh-TW",
        &["縮小 {fieldLabel}", "放大 {fieldLabel}", "數字欄位"],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["decrease", "increase", "numberField"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of number fields, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct NumberFieldStrings(Strings);

impl LocalizedStrings for NumberFieldStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl NumberFieldStrings {
    /// en-US: `Decrease {fieldLabel}`
    #[must_use]
    pub fn decrease(&self, field_label: &str) -> String {
        self.0.format(0, &[("fieldLabel", Arg::Str(field_label))])
    }
    /// en-US: `Increase {fieldLabel}`
    #[must_use]
    pub fn increase(&self, field_label: &str) -> String {
        self.0.format(1, &[("fieldLabel", Arg::Str(field_label))])
    }
    /// en-US: `Number field`
    #[must_use]
    pub fn number_field(&self) -> String {
        self.0.format(2, &[])
    }
}
