// Generated by scripts/port-intl-strings.py from react-aria/intl/overlays/*.json @ 99e6102368. Do not edit.
//! Localized messages of overlays.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Dismiss"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["تجاهل"]),
    ("bg-BG", &["Отхвърляне"]),
    ("cs-CZ", &["Odstranit"]),
    ("da-DK", &["Luk"]),
    ("de-DE", &["Schließen"]),
    ("el-GR", &["Απόρριψη"]),
    ("es-ES", &["Descartar"]),
    ("et-EE", &["Lõpeta"]),
    ("fi-FI", &["Hylkää"]),
    ("fr-FR", &["Rejeter"]),
    ("he-IL", &["התעלם"]),
    ("hr-HR", &["Odbaci"]),
    ("hu-HU", &["Elutasítás"]),
    ("it-IT", &["Ignora"]),
    ("ja-JP", &["閉じる"]),
    ("ko-KR", &["무시"]),
    ("lt-LT", &["Atmesti"]),
    ("lv-LV", &["Nerādīt"]),
    ("nb-NO", &["Lukk"]),
    ("nl-NL", &["Negeren"]),
    ("pl-PL", &["Zignoruj"]),
    ("pt-BR", &["Descartar"]),
    ("pt-PT", &["Dispensar"]),
    ("ro-RO", &["Revocare"]),
    ("ru-RU", &["Пропустить"]),
    ("sk-SK", &["Zrušiť"]),
    ("sl-SI", &["Opusti"]),
    ("sr-SP", &["Odbaci"]),
    ("sv-SE", &["Avvisa"]),
    ("tr-TR", &["Kapat"]),
    ("uk-UA", &["Скасувати"]),
    ("zh-CN", &["取消"]),
    ("zh-TW", &["關閉"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["dismiss"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of overlays, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct OverlayStrings(Strings);

impl LocalizedStrings for OverlayStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl OverlayStrings {
    /// en-US: `Dismiss`
    #[must_use]
    pub fn dismiss(&self) -> String {
        self.0.format(0, &[])
    }
}
