// Generated by scripts/port-intl-strings.py from react-aria/intl/searchfield/*.json @ 99e6102368. Do not edit.
//! Localized messages of search fields.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Clear search"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["مسح البحث"]),
    ("bg-BG", &["Изчистване на търсене"]),
    ("cs-CZ", &["Vymazat hledání"]),
    ("da-DK", &["Ryd søgning"]),
    ("de-DE", &["Suche zurücksetzen"]),
    ("el-GR", &["Απαλοιφή αναζήτησης"]),
    ("es-ES", &["Borrar búsqueda"]),
    ("et-EE", &["Tühjenda otsing"]),
    ("fi-FI", &["Tyhjennä haku"]),
    ("fr-FR", &["Effacer la recherche"]),
    ("he-IL", &["נקה חיפוש"]),
    ("hr-HR", &["Obriši pretragu"]),
    ("hu-HU", &["Keresés törlése"]),
    ("it-IT", &["Cancella ricerca"]),
    ("ja-JP", &["検索をクリア"]),
    ("ko-KR", &["검색 지우기"]),
    ("lt-LT", &["Išvalyti iešką"]),
    ("lv-LV", &["Notīrīt meklēšanu"]),
    ("nb-NO", &["Tøm søk"]),
    ("nl-NL", &["Zoekactie wissen"]),
    ("pl-PL", &["Wyczyść zawartość wyszukiwania"]),
    ("pt-BR", &["Limpar pesquisa"]),
    ("pt-PT", &["Limpar pesquisa"]),
    ("ro-RO", &["Ştergeţi căutarea"]),
    ("ru-RU", &["Очистить поиск"]),
    ("sk-SK", &["Vymazať vyhľadávanie"]),
    ("sl-SI", &["Počisti iskanje"]),
    ("sr-SP", &["Obriši pretragu"]),
    ("sv-SE", &["Rensa sökning"]),
    ("tr-TR", &["Aramayı temizle"]),
    ("uk-UA", &["Очистити пошук"]),
    ("zh-CN", &["清除搜索"]),
    ("zh-TW", &["清除搜尋條件"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["Clear search"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of search fields, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct SearchFieldStrings(Strings);

impl LocalizedStrings for SearchFieldStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl SearchFieldStrings {
    /// en-US: `Clear search`
    #[must_use]
    pub fn clear_search(&self) -> String {
        self.0.format(0, &[])
    }
}
