// Generated by scripts/port-intl-strings.py from react-aria/intl/spinbutton/*.json @ 99e6102368. Do not edit.
//! Localized messages of spin buttons.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Empty"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["فارغ"]),
    ("bg-BG", &["Изпразни"]),
    ("cs-CZ", &["Prázdné"]),
    ("da-DK", &["Tom"]),
    ("de-DE", &["Leer"]),
    ("el-GR", &["Άδειο"]),
    ("es-ES", &["Vacío"]),
    ("et-EE", &["Tühjenda"]),
    ("fi-FI", &["Tyhjä"]),
    ("fr-FR", &["Vide"]),
    ("he-IL", &["ריק"]),
    ("hr-HR", &["Prazno"]),
    ("hu-HU", &["Üres"]),
    ("it-IT", &["Vuoto"]),
    ("ja-JP", &["空"]),
    ("ko-KR", &["비어 있음"]),
    ("lt-LT", &["Tuščias"]),
    ("lv-LV", &["Tukšs"]),
    ("nb-NO", &["Tom"]),
    ("nl-NL", &["Leeg"]),
    ("pl-PL", &["Pusty"]),
    ("pt-BR", &["Vazio"]),
    ("pt-PT", &["Vazio"]),
    ("ro-RO", &["Gol"]),
    ("ru-RU", &["Не заполнено"]),
    ("sk-SK", &["Prázdne"]),
    ("sl-SI", &["Prazen"]),
    ("sr-SP", &["Prazno"]),
    ("sv-SE", &["Tomt"]),
    ("tr-TR", &["Boş"]),
    ("uk-UA", &["Пусто"]),
    ("zh-CN", &["空"]),
    ("zh-TW", &["空白"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["Empty"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of spin buttons, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct SpinButtonStrings(Strings);

impl LocalizedStrings for SpinButtonStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl SpinButtonStrings {
    /// en-US: `Empty`
    #[must_use]
    pub fn empty(&self) -> String {
        self.0.format(0, &[])
    }
}
