// Generated by scripts/port-intl-strings.py from react-aria/intl/table/*.json @ 99e6102368. Do not edit.
//! Localized messages of tables.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Select",
    "Select All",
    "sortable column",
    "ascending",
    "descending",
    "sorted by column {columnName} in ascending order",
    "sorted by column {columnName} in descending order",
    "{value} pixels",
    "Press Enter to start resizing",
    "Expand",
    "Collapse",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &[
            "تحديد",
            "تحديد الكل",
            "عمود قابل للترتيب",
            "تصاعدي",
            "تنازلي",
            "ترتيب حسب العمود {columnName} بترتيب تصاعدي",
            "ترتيب حسب العمود {columnName} بترتيب تنازلي",
            "{value} بالبكسل",
            "اضغط على مفتاح Enter لبدء تغيير الحجم",
            "تمديد",
            "طي",
        ],
    ),
    (
        "bg-BG",
        &[
            "Изберете",
            "Изберете всичко",
            "сортираща колона",
            "възходящ",
            "низходящ",
            "сортирано по колона {columnName} във възходящ ред",
            "сортирано по колона {columnName} в низходящ ред",
            "{value} пиксела",
            "Натиснете „Enter“, за да започнете да преоразмерявате",
            "Разширяване",
            "Свиване",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Vybrat",
            "Vybrat vše",
            "sloupec s možností řazení",
            "vzestupně",
            "sestupně",
            "řazeno vzestupně podle sloupce {columnName}",
            "řazeno sestupně podle sloupce {columnName}",
            "{value} pixelů",
            "Stisknutím klávesy Enter začnete měnit velikost",
            "Roztáhnout",
            "Sbalit",
        ],
    ),
    (
        "da-DK",
        &[
            "Vælg",
            "Vælg alle",
            "sorterbar kolonne",
            "stigende",
            "faldende",
            "sorteret efter kolonne {columnName} i stigende rækkefølge",
            "sorteret efter kolonne {columnName} i faldende rækkefølge",
            "{value} pixels",
            "Tryk på Enter for at ændre størrelse",
            "Udvid",
            "Skjul",
        ],
    ),
    (
        "de-DE",
        &[
            "Auswählen",
            "Alles auswählen",
            "sortierbare Spalte",
            "aufsteigend",
            "absteigend",
            "sortiert nach Spalte {columnName} in aufsteigender Reihenfolge",
            "sortiert nach Spalte {columnName} in absteigender Reihenfolge",
            "{value} Pixel",
            "Eingabetaste zum Starten der Größenänderung drücken",
            "Erweitern",
            "Reduzieren",
        ],
    ),
    (
        "el-GR",
        &[
            "Επιλογή",
            "Επιλογή όλων",
            "Στήλη διαλογής",
            "αύξουσα",
            "φθίνουσα",
            "διαλογή ανά στήλη {columnName} σε αύξουσα σειρά",
            "διαλογή ανά στήλη {columnName} σε φθίνουσα σειρά",
            "{value} pixel",
            "Πατήστε Enter για έναρξη της αλλαγής μεγέθους",
            "Ανάπτυξη",
            "Σύμπτυξη",
        ],
    ),
    (
        "es-ES",
        &[
            "Seleccionar",
            "Seleccionar todos",
            "columna ordenable",
            "ascendente",
            "descendente",
            "ordenado por columna {columnName} en sentido ascendente",
            "ordenado por columna {columnName} en orden descendente",
            "{value} píxeles",
            "Pulse Intro para empezar a redimensionar",
            "Ampliar",
            "Contraer",
        ],
    ),
    (
        "et-EE",
        &[
            "Vali",
            "Vali kõik",
            "sorditav veerg",
            "tõusev järjestus",
            "laskuv järjestus",
            "sorditud veeru järgi {columnName} tõusvas järjestuses",
            "sorditud veeru järgi {columnName} laskuvas järjestuses",
            "{value} pikslit",
            "Suuruse muutmise alustamiseks vajutage klahvi Enter",
            "Laienda",
            "Ahenda",
        ],
    ),
    (
        "fi-FI",
        &[
            "Valitse",
            "Valitse kaikki",
            "lajiteltava sarake",
            "nouseva",
            "laskeva",
            "lajiteltu sarakkeen {columnName} mukaan nousevassa järjestyksessä",
            "lajiteltu sarakkeen {columnName} mukaan laskevassa järjestyksessä",
            "{value} pikseliä",
            "Aloita koon muutos painamalla Enter-näppäintä",
            "Laajenna",
            "Pienennä",
        ],
    ),
    (
        "fr-FR",
        &[
            "Sélectionner",
            "Sélectionner tout",
            "colonne triable",
            "croissant",
            "décroissant",
            "trié en fonction de la colonne\u{a0}{columnName} par ordre croissant",
            "trié en fonction de la colonne\u{a0}{columnName} par ordre décroissant",
            "{value}\u{a0}pixels",
            "Appuyez sur Entrée pour commencer le redimensionnement.",
            "Développer",
            "Réduire",
        ],
    ),
    (
        "he-IL",
        &[
            "בחר",
            "בחר הכול",
            "עמודה שניתן למיין",
            "עולה",
            "יורד",
            "מוין לפי עמודה {columnName} בסדר עולה",
            "מוין לפי עמודה {columnName} בסדר יורד",
            "{value} פיקסלים",
            "הקש Enter כדי לשנות את הגודל",
            "הרחב",
            "כווץ",
        ],
    ),
    (
        "hr-HR",
        &[
            "Odaberite",
            "Odaberite sve",
            "stupac koji se može razvrstati",
            "rastući",
            "padajući",
            "razvrstano po stupcima {columnName} rastućem redoslijedom",
            "razvrstano po stupcima {columnName} padajućim redoslijedom",
            "{value} piksela",
            "Pritisnite Enter da biste započeli promenu veličine",
            "Proširi",
            "Sažmi",
        ],
    ),
    (
        "hu-HU",
        &[
            "Kijelölés",
            "Összes kijelölése",
            "rendezendő oszlop",
            "növekvő",
            "csökkenő",
            "rendezve a(z) {columnName} oszlop szerint, növekvő sorrendben",
            "rendezve a(z) {columnName} oszlop szerint, csökkenő sorrendben",
            "{value} képpont",
            "Nyomja le az Enter billentyűt az átméretezés megkezdéséhez",
            "Kibontás",
            "Összecsukás",
        ],
    ),
    (
        "it-IT",
        &[
            "Seleziona",
            "Seleziona tutto",
            "colonna ordinabile",
            "crescente",
            "decrescente",
            "in ordine crescente in base alla colonna {columnName}",
            "in ordine decrescente in base alla colonna {columnName}",
            "{value} pixel",
            "Premi Invio per iniziare a ridimensionare",
            "Espandi",
            "Comprimi",
        ],
    ),
    (
        "ja-JP",
        &[
            "選択",
            "すべて選択",
            "並べ替え可能な列",
            "昇順",
            "降順",
            "列 {columnName} を昇順で並べ替え",
            "列 {columnName} を降順で並べ替え",
            "{value} ピクセル",
            "Enter キーを押してサイズ変更を開始",
            "展開",
            "折りたたむ",
        ],
    ),
    (
        "ko-KR",
        &[
            "선택",
            "모두 선택",
            "정렬 가능한 열",
            "오름차순",
            "내림차순",
            "{columnName} 열을 기준으로 오름차순으로 정렬됨",
            "{columnName} 열을 기준으로 내림차순으로 정렬됨",
            "{value} 픽셀",
            "크기 조정을 시작하려면 Enter를 누르세요.",
            "펼치기",
            "접기",
        ],
    ),
    (
        "lt-LT",
        &[
            "Pasirinkti",
            "Pasirinkti viską",
            "rikiuojamas stulpelis",
            "didėjančia tvarka",
            "mažėjančia tvarka",
            "surikiuota pagal stulpelį {columnName} didėjančia tvarka",
            "surikiuota pagal stulpelį {columnName} mažėjančia tvarka",
            "{value} piks.",
            "Paspauskite „Enter“, kad pradėtumėte keisti dydį",
            "Išskleisti",
            "Sutraukti",
        ],
    ),
    (
        "lv-LV",
        &[
            "Atlasīt",
            "Atlasīt visu",
            "kārtojamā kolonna",
            "augošā secībā",
            "dilstošā secībā",
            "kārtots pēc kolonnas {columnName} augošā secībā",
            "kārtots pēc kolonnas {columnName} dilstošā secībā",
            "{value} pikseļi",
            "Nospiediet Enter, lai sāktu izmēru mainīšanu",
            "Izvērst",
            "Sakļaut",
        ],
    ),
    (
        "nb-NO",
        &[
            "Velg",
            "Velg alle",
            "kolonne som kan sorteres",
            "stigende",
            "synkende",
            "sortert etter kolonne {columnName} i stigende rekkefølge",
            "sortert etter kolonne {columnName} i synkende rekkefølge",
            "{value} piksler",
            "Trykk på Enter for å starte størrelsesendring",
            "Utvid",
            "Skjul",
        ],
    ),
    (
        "nl-NL",
        &[
            "Selecteren",
            "Alles selecteren",
            "sorteerbare kolom",
            "oplopend",
            "aflopend",
            "gesorteerd in oplopende volgorde in kolom {columnName}",
            "gesorteerd in aflopende volgorde in kolom {columnName}",
            "{value} pixels",
            "Druk op Enter om het formaat te wijzigen",
            "Uitvouwen",
            "Samenvouwen",
        ],
    ),
    (
        "pl-PL",
        &[
            "Zaznacz",
            "Zaznacz wszystko",
            "kolumna z możliwością sortowania",
            "rosnąco",
            "malejąco",
            "posortowano według kolumny {columnName} w porządku rosnącym",
            "posortowano według kolumny {columnName} w porządku malejącym",
            "Liczba pikseli: {value}",
            "Naciśnij Enter, aby rozpocząć zmienianie rozmiaru",
            "Rozwiń",
            "Zwiń",
        ],
    ),
    (
        "pt-BR",
        &[
            "Selecionar",
            "Selecionar tudo",
            "coluna classificável",
            "crescente",
            "decrescente",
            "classificado pela coluna {columnName} em ordem crescente",
            "classificado pela coluna {columnName} em ordem decrescente",
            "{value} pixels",
            "Pressione Enter para começar a redimensionar",
            "Expandir",
            "Recolher",
        ],
    ),
    (
        "pt-PT",
        &[
            "Selecionar",
            "Selecionar tudo",
            "Coluna ordenável",
            "ascendente",
            "descendente",
            "Ordenar por coluna {columnName} em ordem ascendente",
            "Ordenar por coluna {columnName} em ordem descendente",
            "{value} pixels",
            "Prima Enter para iniciar o redimensionamento",
            "Expandir",
            "Colapsar",
        ],
    ),
    (
        "ro-RO",
        &[
            "Selectare",
            "Selectare totală",
            "coloană sortabilă",
            "crescătoare",
            "descrescătoare",
            "sortate după coloana {columnName} în ordine crescătoare",
            "sortate după coloana {columnName} în ordine descrescătoare",
            "{value} pixeli",
            "Apăsați pe Enter pentru a începe redimensionarea",
            "Extindeți",
            "Restrângeți",
        ],
    ),
    (
        "ru-RU",
        &[
            "Выбрать",
            "Выбрать все",
            "сортируемый столбец",
            "возрастание",
            "убывание",
            "сортировать столбец {columnName} в порядке возрастания",
            "сортировать столбец {columnName} в порядке убывания",
            "{value} пикс.",
            "Нажмите клавишу Enter для начала изменения размеров",
            "Развернуть",
            "Свернуть",
        ],
    ),
    (
        "sk-SK",
        &[
            "Vybrať",
            "Vybrať všetko",
            "zoraditeľný stĺpec",
            "vzostupne",
            "zostupne",
            "zoradené zostupne podľa stĺpca {columnName}",
            "zoradené zostupne podľa stĺpca {columnName}",
            "Počet pixelov: {value}",
            "Stlačením klávesu Enter začnete zmenu veľkosti",
            "Rozbaliť",
            "Zbaliť",
        ],
    ),
    (
        "sl-SI",
        &[
            "Izberite",
            "Izberite vse",
            "razvrstljivi stolpec",
            "naraščajoče",
            "padajoče",
            "razvrščeno po stolpcu {columnName} v naraščajočem vrstnem redu",
            "razvrščeno po stolpcu {columnName} v padajočem vrstnem redu",
            "{value} slikovnih pik",
            "Pritisnite tipko Enter da začnete spreminjati velikost",
            "Razširi",
            "Strni",
        ],
    ),
    (
        "sr-SP",
        &[
            "Izaberite",
            "Izaberite sve",
            "kolona koja se može sortirati",
            "rastući",
            "padajući",
            "sortirano po kolonama {columnName} rastućim redosledom",
            "sortirano po kolonama {columnName} padajućim redosledom",
            "{value} piksela",
            "Pritisnite Enter da biste započeli promenu veličine",
            "Proširi",
            "Skupi",
        ],
    ),
    (
        "sv-SE",
        &[
            "Markera",
            "Markera allt",
            "sorterbar kolumn",
            "stigande",
            "fallande",
            "sorterat på kolumn {columnName} i stigande ordning",
            "sorterat på kolumn {columnName} i fallande ordning",
            "{value} pixlar",
            "Tryck på Retur för att börja ändra storlek",
            "Expandera",
            "Dölj",
        ],
    ),
    (
        "tr-TR",
        &[
            "Seç",
            "Tümünü Seç",
            "Sıralanabilir sütun",
            "artan sırada",
            "azalan sırada",
            "{columnName} sütuna göre artan düzende sırala",
            "{columnName} sütuna göre azalan düzende sırala",
            "{value} piksel",
            "Yeniden boyutlandırmak için Enter'a basın",
            "Genişlet",
            "Daralt",
        ],
    ),
    (
        "uk-UA",
        &[
            "Вибрати",
            "Вибрати все",
            "сортувальний стовпець",
            "висхідний",
            "низхідний",
            "відсортовано за стовпцем {columnName} у висхідному порядку",
            "відсортовано за стовпцем {columnName} у низхідному порядку",
            "{value} пікс.",
            "Натисніть Enter, щоб почати зміну розміру",
            "Розгорнути",
            "Згорнути",
        ],
    ),
    (
        "zh-CN",
        &[
            "选择",
            "全选",
            "可排序的列",
            "升序",
            "降序",
            "按列 {columnName} 升序排序",
            "按列 {columnName} 降序排序",
            "{value} 像素",
            "按 Enter 开始调整大小。",
            "扩展",
            "折叠",
        ],
    ),
    (
        "zh-TW",
        &[
            "選取",
            "全選",
            "可排序的欄",
            "遞增",
            "遞減",
            "已依據「{columnName}」欄遞增排序",
            "已依據「{columnName}」欄遞減排序",
            "{value} 像素",
            "按 Enter 鍵以開始調整大小",
            "展開",
            "收合",
        ],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &[
        "select",
        "selectAll",
        "sortable",
        "ascending",
        "descending",
        "ascendingSort",
        "descendingSort",
        "columnSize",
        "resizerDescription",
        "expand",
        "collapse",
    ],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of tables, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct TableStrings(Strings);

impl LocalizedStrings for TableStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl TableStrings {
    /// en-US: `Select`
    #[must_use]
    pub fn select(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `Select All`
    #[must_use]
    pub fn select_all(&self) -> String {
        self.0.format(1, &[])
    }
    /// en-US: `sortable column`
    #[must_use]
    pub fn sortable(&self) -> String {
        self.0.format(2, &[])
    }
    /// en-US: `ascending`
    #[must_use]
    pub fn ascending(&self) -> String {
        self.0.format(3, &[])
    }
    /// en-US: `descending`
    #[must_use]
    pub fn descending(&self) -> String {
        self.0.format(4, &[])
    }
    /// en-US: `sorted by column {columnName} in ascending order`
    #[must_use]
    pub fn ascending_sort(&self, column_name: &str) -> String {
        self.0.format(5, &[("columnName", Arg::Str(column_name))])
    }
    /// en-US: `sorted by column {columnName} in descending order`
    #[must_use]
    pub fn descending_sort(&self, column_name: &str) -> String {
        self.0.format(6, &[("columnName", Arg::Str(column_name))])
    }
    /// en-US: `{value} pixels`
    #[must_use]
    pub fn column_size(&self, value: &str) -> String {
        self.0.format(7, &[("value", Arg::Str(value))])
    }
    /// en-US: `Press Enter to start resizing`
    #[must_use]
    pub fn resizer_description(&self) -> String {
        self.0.format(8, &[])
    }
    /// en-US: `Expand`
    #[must_use]
    pub fn expand(&self) -> String {
        self.0.format(9, &[])
    }
    /// en-US: `Collapse`
    #[must_use]
    pub fn collapse(&self) -> String {
        self.0.format(10, &[])
    }
}
