// Generated by scripts/port-intl-strings.py from react-aria/intl/tag/*.json @ 99e6102368. Do not edit.
//! Localized messages of tag groups.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Press Delete to remove tag.", "Remove"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["اضغط على مفتاح DELETE لإزالة علامة.", "إزالة"]),
    (
        "bg-BG",
        &["Натиснете Delete, за да премахнете маркера.", "Премахване"],
    ),
    (
        "cs-CZ",
        &["Stisknutím klávesy Delete odeberete značku.", "Odebrat"],
    ),
    ("da-DK", &["Tryk på Slet for at fjerne tag.", "Fjern"]),
    (
        "de-DE",
        &[
            "Auf „Löschen“ drücken, um das Tag zu entfernen.",
            "Entfernen",
        ],
    ),
    (
        "el-GR",
        &[
            "Πατήστε Διαγραφή για να καταργήσετε την ετικέτα.",
            "Κατάργηση",
        ],
    ),
    (
        "es-ES",
        &["Pulse Eliminar para quitar la etiqueta.", "Quitar"],
    ),
    (
        "et-EE",
        &[
            "Sildi eemaldamiseks vajutage kustutusklahvi Delete.",
            "Eemalda",
        ],
    ),
    (
        "fi-FI",
        &["Poista tunniste painamalla Poista-painiketta.", "Poista"],
    ),
    (
        "fr-FR",
        &[
            "Appuyez sur Supprimer pour supprimer l’étiquette.",
            "Supprimer",
        ],
    ),
    ("he-IL", &["לחץ על מחק כדי להסיר תג.", "הסר"]),
    (
        "hr-HR",
        &["Pritisnite Delete za uklanjanje oznake.", "Ukloni"],
    ),
    (
        "hu-HU",
        &[
            "Nyomja meg a Delete billentyűt a címke eltávolításához.",
            "Eltávolítás",
        ],
    ),
    ("it-IT", &["Premi Elimina per rimuovere il tag.", "Rimuovi"]),
    (
        "ja-JP",
        &["タグを削除するには、Delete キーを押します。", "削除"],
    ),
    (
        "ko-KR",
        &["태그를 제거하려면 Delete 키를 누르십시오.", "제거"],
    ),
    (
        "lt-LT",
        &[
            "Norėdami pašalinti žymą, paspauskite „Delete“ klavišą.",
            "Pašalinti",
        ],
    ),
    (
        "lv-LV",
        &["Nospiediet Delete [Dzēst], lai noņemtu tagu.", "Noņemt"],
    ),
    ("nb-NO", &["Trykk på Slett for å fjerne taggen.", "Fjern"]),
    (
        "nl-NL",
        &[
            "Druk op Verwijderen om de tag te verwijderen.",
            "Verwijderen",
        ],
    ),
    ("pl-PL", &["Naciśnij Usuń, aby usunąć znacznik.", "Usuń"]),
    (
        "pt-BR",
        &["Pressione Delete para remover a tag.", "Remover"],
    ),
    ("pt-PT", &["Prima Delete para eliminar a tag.", "Eliminar"]),
    (
        "ro-RO",
        &[
            "Apăsați pe Delete (Ștergere) pentru a elimina eticheta.",
            "Îndepărtaţi",
        ],
    ),
    ("ru-RU", &["Нажмите DELETE, чтобы удалить тег.", "Удалить"]),
    (
        "sk-SK",
        &[
            "Ak chcete odstrániť značku, stlačte kláves Delete.",
            "Odstrániť",
        ],
    ),
    (
        "sl-SI",
        &["Pritisnite Delete, da odstranite oznako.", "Odstrani"],
    ),
    (
        "sr-SP",
        &["Pritisnite Obriši da biste uklonili oznaku.", "Ukloni"],
    ),
    (
        "sv-SE",
        &["Tryck på Radera för att ta bort taggen.", "Ta bort"],
    ),
    (
        "tr-TR",
        &["Etiketi kaldırmak için Sil tuşuna basın.", "Kaldır"],
    ),
    (
        "uk-UA",
        &["Натисніть Delete, щоб вилучити тег.", "Вилучити"],
    ),
    ("zh-CN", &["按下“删除”以删除标记。", "删除"]),
    ("zh-TW", &["按 Delete 鍵以移除標記。", "移除"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["removeDescription", "removeButtonLabel"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of tag groups, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct TagStrings(Strings);

impl LocalizedStrings for TagStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl TagStrings {
    /// en-US: `Press Delete to remove tag.`
    #[must_use]
    pub fn remove_description(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `Remove`
    #[must_use]
    pub fn remove_button_label(&self) -> String {
        self.0.format(1, &[])
    }
}
