// Generated by scripts/port-intl-strings.py from react-aria/intl/toast/*.json @ 99e6102368. Do not edit.
//! Localized messages of toasts.

use crate::utils::intl_strings::{Arg, Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &[
    "Close",
    "{count, plural, one {# notification} other {# notifications}}.",
];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    (
        "ar-AE",
        &["إغلاق", "{count, plural, one {# إشعار} other {# إشعارات}}."],
    ),
    (
        "bg-BG",
        &[
            "Затвори",
            "{count, plural, one {# известие} other {# известия}}.",
        ],
    ),
    (
        "cs-CZ",
        &[
            "Zavřít",
            "{count, plural, one {# oznámení} other {# oznámení}}.",
        ],
    ),
    (
        "da-DK",
        &["Luk", "{count, plural, one {# besked} other {# beskeder}}."],
    ),
    (
        "de-DE",
        &[
            "Schließen",
            "{count, plural, one {# Benachrichtigung} other {# Benachrichtigungen}}.",
        ],
    ),
    (
        "el-GR",
        &[
            "Κλείσιμο",
            "{count, plural, one {# ειδοποίηση} other {# ειδοποιήσεις}}.",
        ],
    ),
    (
        "es-ES",
        &[
            "Cerrar",
            "{count, plural, one {# notificación} other {# notificaciones}}.",
        ],
    ),
    (
        "et-EE",
        &["Sule", "{count, plural, one {# teatis} other {# teatist}}."],
    ),
    (
        "fi-FI",
        &[
            "Sulje",
            "{count, plural, one {# ilmoitus} other {# ilmoitusta}}.",
        ],
    ),
    (
        "fr-FR",
        &[
            "Fermer",
            "{count, plural, one {# notification} other {# notifications}}.",
        ],
    ),
    (
        "he-IL",
        &["סגור", "{count, plural, one {# התראה} other {# התראות}}."],
    ),
    (
        "hr-HR",
        &[
            "Zatvori",
            "{count, plural, one {# obavijest} other {# obavijesti}}.",
        ],
    ),
    (
        "hu-HU",
        &[
            "Bezárás",
            "{count, plural, one {# értesítés} other {# értesítés}}.",
        ],
    ),
    (
        "it-IT",
        &[
            "Chiudi",
            "{count, plural, one {# notifica} other {# notifiche}}.",
        ],
    ),
    (
        "ja-JP",
        &[
            "閉じる",
            "{count, plural, one {# 個の通知} other {# 個の通知}}。",
        ],
    ),
    (
        "ko-KR",
        &["닫기", "{count, plural, one {#개 알림} other {#개 알림}}."],
    ),
    (
        "lt-LT",
        &[
            "Uždaryti",
            "{count, plural, one {# pranešimas} other {# pranešimai}}.",
        ],
    ),
    (
        "lv-LV",
        &[
            "Aizvērt",
            "{count, plural, one {# paziņojums} other {# paziņojumi}}.",
        ],
    ),
    (
        "nb-NO",
        &[
            "Lukk",
            "{count, plural, one {# varsling} other {# varsler}}.",
        ],
    ),
    (
        "nl-NL",
        &[
            "Sluiten",
            "{count, plural, one {# melding} other {# meldingen}}.",
        ],
    ),
    (
        "pl-PL",
        &[
            "Zamknij",
            "{count, plural, one {# powiadomienie} few {# powiadomienia} many {# powiadomień} other {# powiadomienia}}.",
        ],
    ),
    (
        "pt-BR",
        &[
            "Fechar",
            "{count, plural, one {# notificação} other {# notificações}}.",
        ],
    ),
    (
        "pt-PT",
        &[
            "Fechar",
            "{count, plural, one {# notificação} other {# notificações}}.",
        ],
    ),
    (
        "ro-RO",
        &[
            "Închideţi",
            "{count, plural, one {# notificare} other {# notificări}}.",
        ],
    ),
    (
        "ru-RU",
        &[
            "Закрыть",
            "{count, plural, one {# уведомление} other {# уведомления}}.",
        ],
    ),
    (
        "sk-SK",
        &[
            "Zatvoriť",
            "{count, plural, one {# oznámenie} few {# oznámenia} other {# oznámení}}.",
        ],
    ),
    (
        "sl-SI",
        &[
            "Zapri",
            "{count, plural, one {# obvestilo} two {# obvestili} few {# obvestila} other {# obvestil}}.",
        ],
    ),
    (
        "sr-SP",
        &[
            "Zatvori",
            "{count, plural, one {# obaveštenje} other {# obaveštenja}}.",
        ],
    ),
    (
        "sv-SE",
        &[
            "Stäng",
            "{count, plural, one {# meddelande} other {# meddelanden}}.",
        ],
    ),
    (
        "tr-TR",
        &[
            "Kapat",
            "{count, plural, one {# bildirim} other {# bildirim}}.",
        ],
    ),
    (
        "uk-UA",
        &[
            "Закрити",
            "{count, plural, one {# сповіщення} other {# сповіщення}}.",
        ],
    ),
    (
        "zh-CN",
        &["关闭", "{count, plural, one {# 个通知} other {# 个通知}}。"],
    ),
    (
        "zh-TW",
        &["關閉", "{count, plural, one {# 個通知} other {# 個通知}}。"],
    ),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["close", "notifications"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of toasts, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct ToastStrings(Strings);

impl LocalizedStrings for ToastStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl ToastStrings {
    /// en-US: `Close`
    #[must_use]
    pub fn close(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `{count, plural, one {# notification} other {# notifications}}.`
    #[must_use]
    pub fn notifications(&self, count: usize) -> String {
        self.0.format(1, &[("count", Arg::Count(count))])
    }
}
