// Generated by scripts/port-intl-strings.py from react-aria/intl/tree/*.json @ 99e6102368. Do not edit.
//! Localized messages of trees.

use crate::utils::intl_strings::{Bundle, LocalizedStrings, Strings};

const EN_US: &[&str] = &["Expand", "Collapse"];

#[cfg(feature = "intl-strings")]
const OTHER: &[(&str, &[&str])] = &[
    ("ar-AE", &["تمديد", "طي"]),
    ("bg-BG", &["Разширяване", "Свиване"]),
    ("cs-CZ", &["Roztáhnout", "Sbalit"]),
    ("da-DK", &["Udvid", "Skjul"]),
    ("de-DE", &["Erweitern", "Reduzieren"]),
    ("el-GR", &["Ανάπτυξη", "Σύμπτυξη"]),
    ("es-ES", &["Expandir", "Contraer"]),
    ("et-EE", &["Laienda", "Ahenda"]),
    ("fi-FI", &["Laajenna", "Pienennä"]),
    ("fr-FR", &["Développer", "Réduire"]),
    ("he-IL", &["הרחב", "כווץ"]),
    ("hr-HR", &["Proširi", "Sažmi"]),
    ("hu-HU", &["Kibontás", "Összecsukás"]),
    ("it-IT", &["Espandi", "Comprimi"]),
    ("ja-JP", &["展開", "折りたたむ"]),
    ("ko-KR", &["펼치기", "접기"]),
    ("lt-LT", &["Išskleisti", "Sutraukti"]),
    ("lv-LV", &["Izvērst", "Sakļaut"]),
    ("nb-NO", &["Utvid", "Skjul"]),
    ("nl-NL", &["Uitvouwen", "Samenvouwen"]),
    ("pl-PL", &["Rozwiń", "Zwiń"]),
    ("pt-BR", &["Expandir", "Recolher"]),
    ("pt-PT", &["Expandir", "Colapsar"]),
    ("ro-RO", &["Extindeți", "Restrângeți"]),
    ("ru-RU", &["Развернуть", "Свернуть"]),
    ("sk-SK", &["Rozbaliť", "Zbaliť"]),
    ("sl-SI", &["Razširi", "Strni"]),
    ("sr-SP", &["Proširi", " Skupi"]),
    ("sv-SE", &["Expandera", "Dölj"]),
    ("tr-TR", &["Genişlet", "Daralt"]),
    ("uk-UA", &["Розгорнути", "Згорнути"]),
    ("zh-CN", &["扩展", "折叠"]),
    ("zh-TW", &["展開", "收合"]),
];
#[cfg(not(feature = "intl-strings"))]
const OTHER: &[(&str, &[&str])] = &[];

static BUNDLE: Bundle = Bundle {
    keys: &["expand", "collapse"],
    en_us: EN_US,
    other: OTHER,
};

/// Localized messages of trees, in the locale they were created for
/// ([`use_localized_strings`](crate::utils::intl_strings::use_localized_strings)).
#[derive(Debug, Clone, PartialEq)]
pub struct TreeStrings(Strings);

impl LocalizedStrings for TreeStrings {
    fn bundle() -> &'static Bundle {
        &BUNDLE
    }

    fn new(strings: Strings) -> Self {
        Self(strings)
    }

    fn strings(&self) -> &Strings {
        &self.0
    }
}

impl TreeStrings {
    /// en-US: `Expand`
    #[must_use]
    pub fn expand(&self) -> String {
        self.0.format(0, &[])
    }
    /// en-US: `Collapse`
    #[must_use]
    pub fn collapse(&self) -> String {
        self.0.format(1, &[])
    }
}
