use std::{borrow::Cow, convert::Infallible, str::FromStr};

use strum::{EnumIter, IntoEnumIterator};

use crate::Language;

/// A keyboard key.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, EnumIter)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    ArrowUp,
    ArrowRight,
    ArrowDown,
    ArrowLeft,
    Plus,
    Star,
    Dash,
    Underscore,
    Slash,
    Backslash,
    Dot,
    Comma,
    Colon,
    Semicolon,
    Hash,
    Escape,
    Enter,
    Backspace,
    Control,
    Alt,
    Shift,
    CapsLock,
    Command,
    Option,
    Tab,
    Tilde,
    Fn,
    Space,
    Home,
    End,
    PageUp,
    PageDown,
    Delete,
    Meta,
    Insert,
    ContextMenu,
    NumLock,
    PrintScreen,
    ScrollLock,
    Pause,
    /// Any other key value.
    ///
    /// Used both for custom display labels in the <Kbd> component (as `Cow::Borrowed`)
    /// and as a catch-all for unrecognized `KeyboardEvent.key()` values (as `Cow::Owned`).
    Other(Cow<'static, str>),
}

impl Key {
    pub fn known_keys() -> impl Iterator<Item = Key> {
        Self::iter().filter(|key| {
            std::mem::discriminant(key) != std::mem::discriminant(&Key::Other(Cow::Borrowed("")))
        })
    }

    /// Returns the display string for this key in the given language.
    pub fn display(&self, _lang: Language) -> &str {
        match self {
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::W => "W",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::N0 => "0",
            Self::N1 => "1",
            Self::N2 => "2",
            Self::N3 => "3",
            Self::N4 => "4",
            Self::N5 => "5",
            Self::N6 => "6",
            Self::N7 => "7",
            Self::N8 => "8",
            Self::N9 => "9",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::ArrowUp => "↑",
            Self::ArrowRight => "→",
            Self::ArrowDown => "↓",
            Self::ArrowLeft => "←",
            Self::Plus => "+",
            Self::Star => "*",
            Self::Dash => "-",
            Self::Underscore => "_",
            Self::Slash => "/",
            Self::Backslash => "\\",
            Self::Dot => ".",
            Self::Comma => ",",
            Self::Colon => ":",
            Self::Semicolon => ";",
            Self::Hash => "#",
            Self::Escape => "Esc",
            Self::Enter => "Enter",
            Self::Backspace => "Backspace",
            Self::Control => "Ctrl",
            Self::Alt => "Alt",
            Self::Shift => "⇧",
            Self::CapsLock => "⇪",
            Self::Command => "⌘",
            Self::Option => "⌥",
            Self::Tab => "↹",
            Self::Tilde => "~",
            Self::Fn => "fn",
            Self::Space => "Space",
            Self::Home => "Home",
            Self::End => "End",
            Self::PageUp => "PgUp",
            Self::PageDown => "PgDn",
            Self::Delete => "Del",
            Self::Meta => "Meta",
            Self::Insert => "Ins",
            Self::ContextMenu => "Menu",
            Self::NumLock => "NumLk",
            Self::PrintScreen => "PrtSc",
            Self::ScrollLock => "ScrLk",
            Self::Pause => "Pause",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl FromStr for Key {
    type Err = Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            // Single letters (lowercase and uppercase map to the same key).
            "a" | "A" => Key::A,
            "b" | "B" => Key::B,
            "c" | "C" => Key::C,
            "d" | "D" => Key::D,
            "e" | "E" => Key::E,
            "f" | "F" => Key::F,
            "g" | "G" => Key::G,
            "h" | "H" => Key::H,
            "i" | "I" => Key::I,
            "j" | "J" => Key::J,
            "k" | "K" => Key::K,
            "l" | "L" => Key::L,
            "m" | "M" => Key::M,
            "n" | "N" => Key::N,
            "o" | "O" => Key::O,
            "p" | "P" => Key::P,
            "q" | "Q" => Key::Q,
            "r" | "R" => Key::R,
            "s" | "S" => Key::S,
            "t" | "T" => Key::T,
            "u" | "U" => Key::U,
            "v" | "V" => Key::V,
            "w" | "W" => Key::W,
            "x" | "X" => Key::X,
            "y" | "Y" => Key::Y,
            "z" | "Z" => Key::Z,
            // Digits
            "0" => Key::N0,
            "1" => Key::N1,
            "2" => Key::N2,
            "3" => Key::N3,
            "4" => Key::N4,
            "5" => Key::N5,
            "6" => Key::N6,
            "7" => Key::N7,
            "8" => Key::N8,
            "9" => Key::N9,
            // Function keys
            "F1" => Key::F1,
            "F2" => Key::F2,
            "F3" => Key::F3,
            "F4" => Key::F4,
            "F5" => Key::F5,
            "F6" => Key::F6,
            "F7" => Key::F7,
            "F8" => Key::F8,
            "F9" => Key::F9,
            "F10" => Key::F10,
            "F11" => Key::F11,
            "F12" => Key::F12,
            // Arrow keys
            "ArrowUp" => Key::ArrowUp,
            "ArrowRight" => Key::ArrowRight,
            "ArrowDown" => Key::ArrowDown,
            "ArrowLeft" => Key::ArrowLeft,
            // Special keys
            " " | "Spacebar" | "Space" => Key::Space,
            "Enter" => Key::Enter,
            "Escape" => Key::Escape,
            "Tab" => Key::Tab,
            "Backspace" => Key::Backspace,
            "Delete" => Key::Delete,
            "Home" => Key::Home,
            "End" => Key::End,
            "PageUp" => Key::PageUp,
            "PageDown" => Key::PageDown,
            "Meta" => Key::Meta,
            "Control" => Key::Control,
            "Alt" => Key::Alt,
            "Shift" => Key::Shift,
            "CapsLock" => Key::CapsLock,
            "Insert" => Key::Insert,
            "ContextMenu" => Key::ContextMenu,
            "NumLock" => Key::NumLock,
            "PrintScreen" => Key::PrintScreen,
            "ScrollLock" => Key::ScrollLock,
            "Pause" => Key::Pause,
            // Punctuation
            "+" => Key::Plus,
            "*" => Key::Star,
            "-" => Key::Dash,
            "_" => Key::Underscore,
            "/" => Key::Slash,
            "\\" => Key::Backslash,
            "." => Key::Dot,
            "," => Key::Comma,
            ":" => Key::Colon,
            ";" => Key::Semicolon,
            "#" => Key::Hash,
            "~" => Key::Tilde,
            // Unrecognized
            other => Key::Other(Cow::Owned(other.to_owned())),
        })
    }
}
