use std::borrow::Cow;

use leptos::tachys::html::style::{style, IntoStyleValue};

use crate::utils::styles::StyleProperty;

/// CSS property names represented as an enum.
///
/// Each variant maps to its kebab-case CSS property name via `AsRef<str>`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Style {
    AlignContent,
    AlignItems,
    AlignSelf,
    Animation,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationTimingFunction,
    Appearance,
    AspectRatio,
    BackdropFilter,
    BackfaceVisibility,
    Background,
    BackgroundAttachment,
    BackgroundBlendMode,
    BackgroundClip,
    BackgroundColor,
    BackgroundImage,
    BackgroundOrigin,
    BackgroundPosition,
    BackgroundRepeat,
    BackgroundSize,
    BlockSize,
    Border,
    BorderBlock,
    BorderBlockColor,
    BorderBlockEnd,
    BorderBlockEndColor,
    BorderBlockEndStyle,
    BorderBlockEndWidth,
    BorderBlockStart,
    BorderBlockStartColor,
    BorderBlockStartStyle,
    BorderBlockStartWidth,
    BorderBlockStyle,
    BorderBlockWidth,
    BorderBottom,
    BorderBottomColor,
    BorderBottomLeftRadius,
    BorderBottomRightRadius,
    BorderBottomStyle,
    BorderBottomWidth,
    BorderCollapse,
    BorderColor,
    BorderImage,
    BorderImageOutset,
    BorderImageRepeat,
    BorderImageSlice,
    BorderImageSource,
    BorderImageWidth,
    BorderInline,
    BorderInlineColor,
    BorderInlineEnd,
    BorderInlineEndColor,
    BorderInlineEndStyle,
    BorderInlineEndWidth,
    BorderInlineStart,
    BorderInlineStartColor,
    BorderInlineStartStyle,
    BorderInlineStartWidth,
    BorderInlineStyle,
    BorderInlineWidth,
    BorderLeft,
    BorderLeftColor,
    BorderLeftStyle,
    BorderLeftWidth,
    BorderRadius,
    BorderRight,
    BorderRightColor,
    BorderRightStyle,
    BorderRightWidth,
    BorderSpacing,
    BorderStyle,
    BorderTop,
    BorderTopColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderTopStyle,
    BorderTopWidth,
    BorderWidth,
    Bottom,
    BoxDecorationBreak,
    BoxShadow,
    BoxSizing,
    BreakAfter,
    BreakBefore,
    BreakInside,
    CaptionSide,
    CaretColor,
    Clear,
    Clip,
    ClipPath,
    Color,
    ColorScheme,
    ColumnCount,
    ColumnFill,
    ColumnGap,
    ColumnRule,
    ColumnRuleColor,
    ColumnRuleStyle,
    ColumnRuleWidth,
    ColumnSpan,
    ColumnWidth,
    Columns,
    Contain,
    Content,
    ContentVisibility,
    CounterIncrement,
    CounterReset,
    CounterSet,
    Cursor,
    Direction,
    Display,
    EmptyCells,
    Filter,
    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    Float,
    Font,
    FontFamily,
    FontFeatureSettings,
    FontKerning,
    FontOpticalSizing,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontSynthesis,
    FontVariant,
    FontVariantCaps,
    FontVariantEastAsian,
    FontVariantLigatures,
    FontVariantNumeric,
    FontVariationSettings,
    FontWeight,
    Gap,
    Grid,
    GridArea,
    GridAutoColumns,
    GridAutoFlow,
    GridAutoRows,
    GridColumn,
    GridColumnEnd,
    GridColumnStart,
    GridRow,
    GridRowEnd,
    GridRowStart,
    GridTemplate,
    GridTemplateAreas,
    GridTemplateColumns,
    GridTemplateRows,
    Height,
    Hyphens,
    ImageOrientation,
    ImageRendering,
    InlineSize,
    Inset,
    InsetBlock,
    InsetBlockEnd,
    InsetBlockStart,
    InsetInline,
    InsetInlineEnd,
    InsetInlineStart,
    Isolation,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Left,
    LetterSpacing,
    LineBreak,
    LineHeight,
    ListStyle,
    ListStyleImage,
    ListStylePosition,
    ListStyleType,
    Margin,
    MarginBlock,
    MarginBlockEnd,
    MarginBlockStart,
    MarginBottom,
    MarginInline,
    MarginInlineEnd,
    MarginInlineStart,
    MarginLeft,
    MarginRight,
    MarginTop,
    Mask,
    MaskImage,
    MaxBlockSize,
    MaxHeight,
    MaxInlineSize,
    MaxWidth,
    MinBlockSize,
    MinHeight,
    MinInlineSize,
    MinWidth,
    MixBlendMode,
    ObjectFit,
    ObjectPosition,
    Offset,
    OffsetAnchor,
    OffsetDistance,
    OffsetPath,
    OffsetRotate,
    Opacity,
    Order,
    Orphans,
    Outline,
    OutlineColor,
    OutlineOffset,
    OutlineStyle,
    OutlineWidth,
    Overflow,
    OverflowAnchor,
    OverflowWrap,
    OverflowX,
    OverflowY,
    OverscrollBehavior,
    OverscrollBehaviorBlock,
    OverscrollBehaviorInline,
    OverscrollBehaviorX,
    OverscrollBehaviorY,
    Padding,
    PaddingBlock,
    PaddingBlockEnd,
    PaddingBlockStart,
    PaddingBottom,
    PaddingInline,
    PaddingInlineEnd,
    PaddingInlineStart,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    PageBreakAfter,
    PageBreakBefore,
    PageBreakInside,
    Perspective,
    PerspectiveOrigin,
    PlaceContent,
    PlaceItems,
    PlaceSelf,
    PointerEvents,
    Position,
    Quotes,
    Resize,
    Right,
    Rotate,
    RowGap,
    Scale,
    ScrollBehavior,
    ScrollMargin,
    ScrollMarginBlock,
    ScrollMarginBlockEnd,
    ScrollMarginBlockStart,
    ScrollMarginBottom,
    ScrollMarginInline,
    ScrollMarginInlineEnd,
    ScrollMarginInlineStart,
    ScrollMarginLeft,
    ScrollMarginRight,
    ScrollMarginTop,
    ScrollPadding,
    ScrollPaddingBlock,
    ScrollPaddingBlockEnd,
    ScrollPaddingBlockStart,
    ScrollPaddingBottom,
    ScrollPaddingInline,
    ScrollPaddingInlineEnd,
    ScrollPaddingInlineStart,
    ScrollPaddingLeft,
    ScrollPaddingRight,
    ScrollPaddingTop,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollSnapType,
    ScrollbarColor,
    ScrollbarGutter,
    ScrollbarWidth,
    ShapeImageThreshold,
    ShapeMargin,
    ShapeOutside,
    TabSize,
    TableLayout,
    TextAlign,
    TextAlignLast,
    TextCombineUpright,
    TextDecoration,
    TextDecorationColor,
    TextDecorationLine,
    TextDecorationSkipInk,
    TextDecorationStyle,
    TextDecorationThickness,
    TextEmphasis,
    TextEmphasisColor,
    TextEmphasisPosition,
    TextEmphasisStyle,
    TextIndent,
    TextJustify,
    TextOrientation,
    TextOverflow,
    TextRendering,
    TextShadow,
    TextTransform,
    TextUnderlineOffset,
    TextUnderlinePosition,
    Top,
    TouchAction,
    Transform,
    TransformBox,
    TransformOrigin,
    TransformStyle,
    Transition,
    TransitionDelay,
    TransitionDuration,
    TransitionProperty,
    TransitionTimingFunction,
    Translate,
    UnicodeBidi,
    UserSelect,
    VerticalAlign,
    Visibility,
    WhiteSpace,
    Widows,
    Width,
    WillChange,
    WordBreak,
    WordSpacing,
    WritingMode,
    ZIndex,
}

impl Style {
    /// Returns the CSS property name as a static string slice.
    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AlignContent => "align-content",
            Self::AlignItems => "align-items",
            Self::AlignSelf => "align-self",
            Self::Animation => "animation",
            Self::AnimationDelay => "animation-delay",
            Self::AnimationDirection => "animation-direction",
            Self::AnimationDuration => "animation-duration",
            Self::AnimationFillMode => "animation-fill-mode",
            Self::AnimationIterationCount => "animation-iteration-count",
            Self::AnimationName => "animation-name",
            Self::AnimationPlayState => "animation-play-state",
            Self::AnimationTimingFunction => "animation-timing-function",
            Self::Appearance => "appearance",
            Self::AspectRatio => "aspect-ratio",
            Self::BackdropFilter => "backdrop-filter",
            Self::BackfaceVisibility => "backface-visibility",
            Self::Background => "background",
            Self::BackgroundAttachment => "background-attachment",
            Self::BackgroundBlendMode => "background-blend-mode",
            Self::BackgroundClip => "background-clip",
            Self::BackgroundColor => "background-color",
            Self::BackgroundImage => "background-image",
            Self::BackgroundOrigin => "background-origin",
            Self::BackgroundPosition => "background-position",
            Self::BackgroundRepeat => "background-repeat",
            Self::BackgroundSize => "background-size",
            Self::BlockSize => "block-size",
            Self::Border => "border",
            Self::BorderBlock => "border-block",
            Self::BorderBlockColor => "border-block-color",
            Self::BorderBlockEnd => "border-block-end",
            Self::BorderBlockEndColor => "border-block-end-color",
            Self::BorderBlockEndStyle => "border-block-end-style",
            Self::BorderBlockEndWidth => "border-block-end-width",
            Self::BorderBlockStart => "border-block-start",
            Self::BorderBlockStartColor => "border-block-start-color",
            Self::BorderBlockStartStyle => "border-block-start-style",
            Self::BorderBlockStartWidth => "border-block-start-width",
            Self::BorderBlockStyle => "border-block-style",
            Self::BorderBlockWidth => "border-block-width",
            Self::BorderBottom => "border-bottom",
            Self::BorderBottomColor => "border-bottom-color",
            Self::BorderBottomLeftRadius => "border-bottom-left-radius",
            Self::BorderBottomRightRadius => "border-bottom-right-radius",
            Self::BorderBottomStyle => "border-bottom-style",
            Self::BorderBottomWidth => "border-bottom-width",
            Self::BorderCollapse => "border-collapse",
            Self::BorderColor => "border-color",
            Self::BorderImage => "border-image",
            Self::BorderImageOutset => "border-image-outset",
            Self::BorderImageRepeat => "border-image-repeat",
            Self::BorderImageSlice => "border-image-slice",
            Self::BorderImageSource => "border-image-source",
            Self::BorderImageWidth => "border-image-width",
            Self::BorderInline => "border-inline",
            Self::BorderInlineColor => "border-inline-color",
            Self::BorderInlineEnd => "border-inline-end",
            Self::BorderInlineEndColor => "border-inline-end-color",
            Self::BorderInlineEndStyle => "border-inline-end-style",
            Self::BorderInlineEndWidth => "border-inline-end-width",
            Self::BorderInlineStart => "border-inline-start",
            Self::BorderInlineStartColor => "border-inline-start-color",
            Self::BorderInlineStartStyle => "border-inline-start-style",
            Self::BorderInlineStartWidth => "border-inline-start-width",
            Self::BorderInlineStyle => "border-inline-style",
            Self::BorderInlineWidth => "border-inline-width",
            Self::BorderLeft => "border-left",
            Self::BorderLeftColor => "border-left-color",
            Self::BorderLeftStyle => "border-left-style",
            Self::BorderLeftWidth => "border-left-width",
            Self::BorderRadius => "border-radius",
            Self::BorderRight => "border-right",
            Self::BorderRightColor => "border-right-color",
            Self::BorderRightStyle => "border-right-style",
            Self::BorderRightWidth => "border-right-width",
            Self::BorderSpacing => "border-spacing",
            Self::BorderStyle => "border-style",
            Self::BorderTop => "border-top",
            Self::BorderTopColor => "border-top-color",
            Self::BorderTopLeftRadius => "border-top-left-radius",
            Self::BorderTopRightRadius => "border-top-right-radius",
            Self::BorderTopStyle => "border-top-style",
            Self::BorderTopWidth => "border-top-width",
            Self::BorderWidth => "border-width",
            Self::Bottom => "bottom",
            Self::BoxDecorationBreak => "box-decoration-break",
            Self::BoxShadow => "box-shadow",
            Self::BoxSizing => "box-sizing",
            Self::BreakAfter => "break-after",
            Self::BreakBefore => "break-before",
            Self::BreakInside => "break-inside",
            Self::CaptionSide => "caption-side",
            Self::CaretColor => "caret-color",
            Self::Clear => "clear",
            Self::Clip => "clip",
            Self::ClipPath => "clip-path",
            Self::Color => "color",
            Self::ColorScheme => "color-scheme",
            Self::ColumnCount => "column-count",
            Self::ColumnFill => "column-fill",
            Self::ColumnGap => "column-gap",
            Self::ColumnRule => "column-rule",
            Self::ColumnRuleColor => "column-rule-color",
            Self::ColumnRuleStyle => "column-rule-style",
            Self::ColumnRuleWidth => "column-rule-width",
            Self::ColumnSpan => "column-span",
            Self::ColumnWidth => "column-width",
            Self::Columns => "columns",
            Self::Contain => "contain",
            Self::Content => "content",
            Self::ContentVisibility => "content-visibility",
            Self::CounterIncrement => "counter-increment",
            Self::CounterReset => "counter-reset",
            Self::CounterSet => "counter-set",
            Self::Cursor => "cursor",
            Self::Direction => "direction",
            Self::Display => "display",
            Self::EmptyCells => "empty-cells",
            Self::Filter => "filter",
            Self::Flex => "flex",
            Self::FlexBasis => "flex-basis",
            Self::FlexDirection => "flex-direction",
            Self::FlexFlow => "flex-flow",
            Self::FlexGrow => "flex-grow",
            Self::FlexShrink => "flex-shrink",
            Self::FlexWrap => "flex-wrap",
            Self::Float => "float",
            Self::Font => "font",
            Self::FontFamily => "font-family",
            Self::FontFeatureSettings => "font-feature-settings",
            Self::FontKerning => "font-kerning",
            Self::FontOpticalSizing => "font-optical-sizing",
            Self::FontSize => "font-size",
            Self::FontSizeAdjust => "font-size-adjust",
            Self::FontStretch => "font-stretch",
            Self::FontStyle => "font-style",
            Self::FontSynthesis => "font-synthesis",
            Self::FontVariant => "font-variant",
            Self::FontVariantCaps => "font-variant-caps",
            Self::FontVariantEastAsian => "font-variant-east-asian",
            Self::FontVariantLigatures => "font-variant-ligatures",
            Self::FontVariantNumeric => "font-variant-numeric",
            Self::FontVariationSettings => "font-variation-settings",
            Self::FontWeight => "font-weight",
            Self::Gap => "gap",
            Self::Grid => "grid",
            Self::GridArea => "grid-area",
            Self::GridAutoColumns => "grid-auto-columns",
            Self::GridAutoFlow => "grid-auto-flow",
            Self::GridAutoRows => "grid-auto-rows",
            Self::GridColumn => "grid-column",
            Self::GridColumnEnd => "grid-column-end",
            Self::GridColumnStart => "grid-column-start",
            Self::GridRow => "grid-row",
            Self::GridRowEnd => "grid-row-end",
            Self::GridRowStart => "grid-row-start",
            Self::GridTemplate => "grid-template",
            Self::GridTemplateAreas => "grid-template-areas",
            Self::GridTemplateColumns => "grid-template-columns",
            Self::GridTemplateRows => "grid-template-rows",
            Self::Height => "height",
            Self::Hyphens => "hyphens",
            Self::ImageOrientation => "image-orientation",
            Self::ImageRendering => "image-rendering",
            Self::InlineSize => "inline-size",
            Self::Inset => "inset",
            Self::InsetBlock => "inset-block",
            Self::InsetBlockEnd => "inset-block-end",
            Self::InsetBlockStart => "inset-block-start",
            Self::InsetInline => "inset-inline",
            Self::InsetInlineEnd => "inset-inline-end",
            Self::InsetInlineStart => "inset-inline-start",
            Self::Isolation => "isolation",
            Self::JustifyContent => "justify-content",
            Self::JustifyItems => "justify-items",
            Self::JustifySelf => "justify-self",
            Self::Left => "left",
            Self::LetterSpacing => "letter-spacing",
            Self::LineBreak => "line-break",
            Self::LineHeight => "line-height",
            Self::ListStyle => "list-style",
            Self::ListStyleImage => "list-style-image",
            Self::ListStylePosition => "list-style-position",
            Self::ListStyleType => "list-style-type",
            Self::Margin => "margin",
            Self::MarginBlock => "margin-block",
            Self::MarginBlockEnd => "margin-block-end",
            Self::MarginBlockStart => "margin-block-start",
            Self::MarginBottom => "margin-bottom",
            Self::MarginInline => "margin-inline",
            Self::MarginInlineEnd => "margin-inline-end",
            Self::MarginInlineStart => "margin-inline-start",
            Self::MarginLeft => "margin-left",
            Self::MarginRight => "margin-right",
            Self::MarginTop => "margin-top",
            Self::Mask => "mask",
            Self::MaskImage => "mask-image",
            Self::MaxBlockSize => "max-block-size",
            Self::MaxHeight => "max-height",
            Self::MaxInlineSize => "max-inline-size",
            Self::MaxWidth => "max-width",
            Self::MinBlockSize => "min-block-size",
            Self::MinHeight => "min-height",
            Self::MinInlineSize => "min-inline-size",
            Self::MinWidth => "min-width",
            Self::MixBlendMode => "mix-blend-mode",
            Self::ObjectFit => "object-fit",
            Self::ObjectPosition => "object-position",
            Self::Offset => "offset",
            Self::OffsetAnchor => "offset-anchor",
            Self::OffsetDistance => "offset-distance",
            Self::OffsetPath => "offset-path",
            Self::OffsetRotate => "offset-rotate",
            Self::Opacity => "opacity",
            Self::Order => "order",
            Self::Orphans => "orphans",
            Self::Outline => "outline",
            Self::OutlineColor => "outline-color",
            Self::OutlineOffset => "outline-offset",
            Self::OutlineStyle => "outline-style",
            Self::OutlineWidth => "outline-width",
            Self::Overflow => "overflow",
            Self::OverflowAnchor => "overflow-anchor",
            Self::OverflowWrap => "overflow-wrap",
            Self::OverflowX => "overflow-x",
            Self::OverflowY => "overflow-y",
            Self::OverscrollBehavior => "overscroll-behavior",
            Self::OverscrollBehaviorBlock => "overscroll-behavior-block",
            Self::OverscrollBehaviorInline => "overscroll-behavior-inline",
            Self::OverscrollBehaviorX => "overscroll-behavior-x",
            Self::OverscrollBehaviorY => "overscroll-behavior-y",
            Self::Padding => "padding",
            Self::PaddingBlock => "padding-block",
            Self::PaddingBlockEnd => "padding-block-end",
            Self::PaddingBlockStart => "padding-block-start",
            Self::PaddingBottom => "padding-bottom",
            Self::PaddingInline => "padding-inline",
            Self::PaddingInlineEnd => "padding-inline-end",
            Self::PaddingInlineStart => "padding-inline-start",
            Self::PaddingLeft => "padding-left",
            Self::PaddingRight => "padding-right",
            Self::PaddingTop => "padding-top",
            Self::PageBreakAfter => "page-break-after",
            Self::PageBreakBefore => "page-break-before",
            Self::PageBreakInside => "page-break-inside",
            Self::Perspective => "perspective",
            Self::PerspectiveOrigin => "perspective-origin",
            Self::PlaceContent => "place-content",
            Self::PlaceItems => "place-items",
            Self::PlaceSelf => "place-self",
            Self::PointerEvents => "pointer-events",
            Self::Position => "position",
            Self::Quotes => "quotes",
            Self::Resize => "resize",
            Self::Right => "right",
            Self::Rotate => "rotate",
            Self::RowGap => "row-gap",
            Self::Scale => "scale",
            Self::ScrollBehavior => "scroll-behavior",
            Self::ScrollMargin => "scroll-margin",
            Self::ScrollMarginBlock => "scroll-margin-block",
            Self::ScrollMarginBlockEnd => "scroll-margin-block-end",
            Self::ScrollMarginBlockStart => "scroll-margin-block-start",
            Self::ScrollMarginBottom => "scroll-margin-bottom",
            Self::ScrollMarginInline => "scroll-margin-inline",
            Self::ScrollMarginInlineEnd => "scroll-margin-inline-end",
            Self::ScrollMarginInlineStart => "scroll-margin-inline-start",
            Self::ScrollMarginLeft => "scroll-margin-left",
            Self::ScrollMarginRight => "scroll-margin-right",
            Self::ScrollMarginTop => "scroll-margin-top",
            Self::ScrollPadding => "scroll-padding",
            Self::ScrollPaddingBlock => "scroll-padding-block",
            Self::ScrollPaddingBlockEnd => "scroll-padding-block-end",
            Self::ScrollPaddingBlockStart => "scroll-padding-block-start",
            Self::ScrollPaddingBottom => "scroll-padding-bottom",
            Self::ScrollPaddingInline => "scroll-padding-inline",
            Self::ScrollPaddingInlineEnd => "scroll-padding-inline-end",
            Self::ScrollPaddingInlineStart => "scroll-padding-inline-start",
            Self::ScrollPaddingLeft => "scroll-padding-left",
            Self::ScrollPaddingRight => "scroll-padding-right",
            Self::ScrollPaddingTop => "scroll-padding-top",
            Self::ScrollSnapAlign => "scroll-snap-align",
            Self::ScrollSnapStop => "scroll-snap-stop",
            Self::ScrollSnapType => "scroll-snap-type",
            Self::ScrollbarColor => "scrollbar-color",
            Self::ScrollbarGutter => "scrollbar-gutter",
            Self::ScrollbarWidth => "scrollbar-width",
            Self::ShapeImageThreshold => "shape-image-threshold",
            Self::ShapeMargin => "shape-margin",
            Self::ShapeOutside => "shape-outside",
            Self::TabSize => "tab-size",
            Self::TableLayout => "table-layout",
            Self::TextAlign => "text-align",
            Self::TextAlignLast => "text-align-last",
            Self::TextCombineUpright => "text-combine-upright",
            Self::TextDecoration => "text-decoration",
            Self::TextDecorationColor => "text-decoration-color",
            Self::TextDecorationLine => "text-decoration-line",
            Self::TextDecorationSkipInk => "text-decoration-skip-ink",
            Self::TextDecorationStyle => "text-decoration-style",
            Self::TextDecorationThickness => "text-decoration-thickness",
            Self::TextEmphasis => "text-emphasis",
            Self::TextEmphasisColor => "text-emphasis-color",
            Self::TextEmphasisPosition => "text-emphasis-position",
            Self::TextEmphasisStyle => "text-emphasis-style",
            Self::TextIndent => "text-indent",
            Self::TextJustify => "text-justify",
            Self::TextOrientation => "text-orientation",
            Self::TextOverflow => "text-overflow",
            Self::TextRendering => "text-rendering",
            Self::TextShadow => "text-shadow",
            Self::TextTransform => "text-transform",
            Self::TextUnderlineOffset => "text-underline-offset",
            Self::TextUnderlinePosition => "text-underline-position",
            Self::Top => "top",
            Self::TouchAction => "touch-action",
            Self::Transform => "transform",
            Self::TransformBox => "transform-box",
            Self::TransformOrigin => "transform-origin",
            Self::TransformStyle => "transform-style",
            Self::Transition => "transition",
            Self::TransitionDelay => "transition-delay",
            Self::TransitionDuration => "transition-duration",
            Self::TransitionProperty => "transition-property",
            Self::TransitionTimingFunction => "transition-timing-function",
            Self::Translate => "translate",
            Self::UnicodeBidi => "unicode-bidi",
            Self::UserSelect => "user-select",
            Self::VerticalAlign => "vertical-align",
            Self::Visibility => "visibility",
            Self::WhiteSpace => "white-space",
            Self::Widows => "widows",
            Self::Width => "width",
            Self::WillChange => "will-change",
            Self::WordBreak => "word-break",
            Self::WordSpacing => "word-spacing",
            Self::WritingMode => "writing-mode",
            Self::ZIndex => "z-index",
        }
    }
}

impl AsRef<str> for Style {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl From<Style> for &'static str {
    fn from(style: Style) -> Self {
        style.as_str()
    }
}

impl From<Style> for StyleProperty {
    fn from(style: Style) -> Self {
        Cow::Borrowed(style.as_str())
    }
}

// TODO: Should more styles be concrete types?
/// Marker for the "touch-action" style.
///
/// # Example
/// ```ignore
/// pub type UsePressAttrs = (
///     Style<(TouchActionStyle, &'static str)>,
/// );
///
/// impl UsePressProps {
///     /// Convert to spreadable attributes for Leptos views.
///     #[must_use]
///     pub fn into_attrs(self) -> UsePressAttrs {
///         (
///             TouchActionStyle::with_value("pan-x pan-y pinch-zoom"),
///         )
///     }
/// }
/// ```
#[derive(Debug, Clone, Copy)]
pub struct TouchActionStyle;
impl AsRef<str> for TouchActionStyle {
    fn as_ref(&self) -> &str {
        Style::TouchAction.as_ref()
    }
}
impl TouchActionStyle {
    pub fn with_value<V: IntoStyleValue>(
        value: V,
    ) -> leptos::tachys::html::style::Style<(Self, V)> {
        style((Self, value.into()))
    }
}
